
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BarisFakturPenjualan` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model BarisFakturPenjualan
 * 
 */
export type BarisFakturPenjualanModel = runtime.Types.Result.DefaultSelection<Prisma.$BarisFakturPenjualanPayload>

export type AggregateBarisFakturPenjualan = {
  _count: BarisFakturPenjualanCountAggregateOutputType | null
  _avg: BarisFakturPenjualanAvgAggregateOutputType | null
  _sum: BarisFakturPenjualanSumAggregateOutputType | null
  _min: BarisFakturPenjualanMinAggregateOutputType | null
  _max: BarisFakturPenjualanMaxAggregateOutputType | null
}

export type BarisFakturPenjualanAvgAggregateOutputType = {
  jumlah: runtime.Decimal | null
  harga: runtime.Decimal | null
  subtotal: runtime.Decimal | null
}

export type BarisFakturPenjualanSumAggregateOutputType = {
  jumlah: runtime.Decimal | null
  harga: runtime.Decimal | null
  subtotal: runtime.Decimal | null
}

export type BarisFakturPenjualanMinAggregateOutputType = {
  id: string | null
  fakturId: string | null
  barangId: string | null
  jumlah: runtime.Decimal | null
  harga: runtime.Decimal | null
  subtotal: runtime.Decimal | null
}

export type BarisFakturPenjualanMaxAggregateOutputType = {
  id: string | null
  fakturId: string | null
  barangId: string | null
  jumlah: runtime.Decimal | null
  harga: runtime.Decimal | null
  subtotal: runtime.Decimal | null
}

export type BarisFakturPenjualanCountAggregateOutputType = {
  id: number
  fakturId: number
  barangId: number
  jumlah: number
  harga: number
  subtotal: number
  _all: number
}


export type BarisFakturPenjualanAvgAggregateInputType = {
  jumlah?: true
  harga?: true
  subtotal?: true
}

export type BarisFakturPenjualanSumAggregateInputType = {
  jumlah?: true
  harga?: true
  subtotal?: true
}

export type BarisFakturPenjualanMinAggregateInputType = {
  id?: true
  fakturId?: true
  barangId?: true
  jumlah?: true
  harga?: true
  subtotal?: true
}

export type BarisFakturPenjualanMaxAggregateInputType = {
  id?: true
  fakturId?: true
  barangId?: true
  jumlah?: true
  harga?: true
  subtotal?: true
}

export type BarisFakturPenjualanCountAggregateInputType = {
  id?: true
  fakturId?: true
  barangId?: true
  jumlah?: true
  harga?: true
  subtotal?: true
  _all?: true
}

export type BarisFakturPenjualanAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BarisFakturPenjualan to aggregate.
   */
  where?: Prisma.BarisFakturPenjualanWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BarisFakturPenjualans to fetch.
   */
  orderBy?: Prisma.BarisFakturPenjualanOrderByWithRelationInput | Prisma.BarisFakturPenjualanOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BarisFakturPenjualanWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BarisFakturPenjualans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BarisFakturPenjualans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BarisFakturPenjualans
  **/
  _count?: true | BarisFakturPenjualanCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: BarisFakturPenjualanAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: BarisFakturPenjualanSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BarisFakturPenjualanMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BarisFakturPenjualanMaxAggregateInputType
}

export type GetBarisFakturPenjualanAggregateType<T extends BarisFakturPenjualanAggregateArgs> = {
      [P in keyof T & keyof AggregateBarisFakturPenjualan]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBarisFakturPenjualan[P]>
    : Prisma.GetScalarType<T[P], AggregateBarisFakturPenjualan[P]>
}




export type BarisFakturPenjualanGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BarisFakturPenjualanWhereInput
  orderBy?: Prisma.BarisFakturPenjualanOrderByWithAggregationInput | Prisma.BarisFakturPenjualanOrderByWithAggregationInput[]
  by: Prisma.BarisFakturPenjualanScalarFieldEnum[] | Prisma.BarisFakturPenjualanScalarFieldEnum
  having?: Prisma.BarisFakturPenjualanScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BarisFakturPenjualanCountAggregateInputType | true
  _avg?: BarisFakturPenjualanAvgAggregateInputType
  _sum?: BarisFakturPenjualanSumAggregateInputType
  _min?: BarisFakturPenjualanMinAggregateInputType
  _max?: BarisFakturPenjualanMaxAggregateInputType
}

export type BarisFakturPenjualanGroupByOutputType = {
  id: string
  fakturId: string
  barangId: string
  jumlah: runtime.Decimal
  harga: runtime.Decimal
  subtotal: runtime.Decimal
  _count: BarisFakturPenjualanCountAggregateOutputType | null
  _avg: BarisFakturPenjualanAvgAggregateOutputType | null
  _sum: BarisFakturPenjualanSumAggregateOutputType | null
  _min: BarisFakturPenjualanMinAggregateOutputType | null
  _max: BarisFakturPenjualanMaxAggregateOutputType | null
}

export type GetBarisFakturPenjualanGroupByPayload<T extends BarisFakturPenjualanGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BarisFakturPenjualanGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BarisFakturPenjualanGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BarisFakturPenjualanGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BarisFakturPenjualanGroupByOutputType[P]>
      }
    >
  >



export type BarisFakturPenjualanWhereInput = {
  AND?: Prisma.BarisFakturPenjualanWhereInput | Prisma.BarisFakturPenjualanWhereInput[]
  OR?: Prisma.BarisFakturPenjualanWhereInput[]
  NOT?: Prisma.BarisFakturPenjualanWhereInput | Prisma.BarisFakturPenjualanWhereInput[]
  id?: Prisma.StringFilter<"BarisFakturPenjualan"> | string
  fakturId?: Prisma.StringFilter<"BarisFakturPenjualan"> | string
  barangId?: Prisma.StringFilter<"BarisFakturPenjualan"> | string
  jumlah?: Prisma.DecimalFilter<"BarisFakturPenjualan"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  harga?: Prisma.DecimalFilter<"BarisFakturPenjualan"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  subtotal?: Prisma.DecimalFilter<"BarisFakturPenjualan"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  faktur?: Prisma.XOR<Prisma.FakturPenjualanScalarRelationFilter, Prisma.FakturPenjualanWhereInput>
  barang?: Prisma.XOR<Prisma.BarangScalarRelationFilter, Prisma.BarangWhereInput>
}

export type BarisFakturPenjualanOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  fakturId?: Prisma.SortOrder
  barangId?: Prisma.SortOrder
  jumlah?: Prisma.SortOrder
  harga?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
  faktur?: Prisma.FakturPenjualanOrderByWithRelationInput
  barang?: Prisma.BarangOrderByWithRelationInput
}

export type BarisFakturPenjualanWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.BarisFakturPenjualanWhereInput | Prisma.BarisFakturPenjualanWhereInput[]
  OR?: Prisma.BarisFakturPenjualanWhereInput[]
  NOT?: Prisma.BarisFakturPenjualanWhereInput | Prisma.BarisFakturPenjualanWhereInput[]
  fakturId?: Prisma.StringFilter<"BarisFakturPenjualan"> | string
  barangId?: Prisma.StringFilter<"BarisFakturPenjualan"> | string
  jumlah?: Prisma.DecimalFilter<"BarisFakturPenjualan"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  harga?: Prisma.DecimalFilter<"BarisFakturPenjualan"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  subtotal?: Prisma.DecimalFilter<"BarisFakturPenjualan"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  faktur?: Prisma.XOR<Prisma.FakturPenjualanScalarRelationFilter, Prisma.FakturPenjualanWhereInput>
  barang?: Prisma.XOR<Prisma.BarangScalarRelationFilter, Prisma.BarangWhereInput>
}, "id">

export type BarisFakturPenjualanOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  fakturId?: Prisma.SortOrder
  barangId?: Prisma.SortOrder
  jumlah?: Prisma.SortOrder
  harga?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
  _count?: Prisma.BarisFakturPenjualanCountOrderByAggregateInput
  _avg?: Prisma.BarisFakturPenjualanAvgOrderByAggregateInput
  _max?: Prisma.BarisFakturPenjualanMaxOrderByAggregateInput
  _min?: Prisma.BarisFakturPenjualanMinOrderByAggregateInput
  _sum?: Prisma.BarisFakturPenjualanSumOrderByAggregateInput
}

export type BarisFakturPenjualanScalarWhereWithAggregatesInput = {
  AND?: Prisma.BarisFakturPenjualanScalarWhereWithAggregatesInput | Prisma.BarisFakturPenjualanScalarWhereWithAggregatesInput[]
  OR?: Prisma.BarisFakturPenjualanScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BarisFakturPenjualanScalarWhereWithAggregatesInput | Prisma.BarisFakturPenjualanScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"BarisFakturPenjualan"> | string
  fakturId?: Prisma.StringWithAggregatesFilter<"BarisFakturPenjualan"> | string
  barangId?: Prisma.StringWithAggregatesFilter<"BarisFakturPenjualan"> | string
  jumlah?: Prisma.DecimalWithAggregatesFilter<"BarisFakturPenjualan"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  harga?: Prisma.DecimalWithAggregatesFilter<"BarisFakturPenjualan"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  subtotal?: Prisma.DecimalWithAggregatesFilter<"BarisFakturPenjualan"> | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type BarisFakturPenjualanCreateInput = {
  id?: string
  jumlah: runtime.Decimal | runtime.DecimalJsLike | number | string
  harga: runtime.Decimal | runtime.DecimalJsLike | number | string
  subtotal: runtime.Decimal | runtime.DecimalJsLike | number | string
  faktur: Prisma.FakturPenjualanCreateNestedOneWithoutBarisInput
  barang: Prisma.BarangCreateNestedOneWithoutBarisFakturPenjualanInput
}

export type BarisFakturPenjualanUncheckedCreateInput = {
  id?: string
  fakturId: string
  barangId: string
  jumlah: runtime.Decimal | runtime.DecimalJsLike | number | string
  harga: runtime.Decimal | runtime.DecimalJsLike | number | string
  subtotal: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type BarisFakturPenjualanUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  jumlah?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  harga?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  subtotal?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  faktur?: Prisma.FakturPenjualanUpdateOneRequiredWithoutBarisNestedInput
  barang?: Prisma.BarangUpdateOneRequiredWithoutBarisFakturPenjualanNestedInput
}

export type BarisFakturPenjualanUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fakturId?: Prisma.StringFieldUpdateOperationsInput | string
  barangId?: Prisma.StringFieldUpdateOperationsInput | string
  jumlah?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  harga?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  subtotal?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type BarisFakturPenjualanCreateManyInput = {
  id?: string
  fakturId: string
  barangId: string
  jumlah: runtime.Decimal | runtime.DecimalJsLike | number | string
  harga: runtime.Decimal | runtime.DecimalJsLike | number | string
  subtotal: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type BarisFakturPenjualanUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  jumlah?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  harga?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  subtotal?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type BarisFakturPenjualanUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fakturId?: Prisma.StringFieldUpdateOperationsInput | string
  barangId?: Prisma.StringFieldUpdateOperationsInput | string
  jumlah?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  harga?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  subtotal?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type BarisFakturPenjualanListRelationFilter = {
  every?: Prisma.BarisFakturPenjualanWhereInput
  some?: Prisma.BarisFakturPenjualanWhereInput
  none?: Prisma.BarisFakturPenjualanWhereInput
}

export type BarisFakturPenjualanOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BarisFakturPenjualanCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fakturId?: Prisma.SortOrder
  barangId?: Prisma.SortOrder
  jumlah?: Prisma.SortOrder
  harga?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
}

export type BarisFakturPenjualanAvgOrderByAggregateInput = {
  jumlah?: Prisma.SortOrder
  harga?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
}

export type BarisFakturPenjualanMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fakturId?: Prisma.SortOrder
  barangId?: Prisma.SortOrder
  jumlah?: Prisma.SortOrder
  harga?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
}

export type BarisFakturPenjualanMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fakturId?: Prisma.SortOrder
  barangId?: Prisma.SortOrder
  jumlah?: Prisma.SortOrder
  harga?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
}

export type BarisFakturPenjualanSumOrderByAggregateInput = {
  jumlah?: Prisma.SortOrder
  harga?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
}

export type BarisFakturPenjualanCreateNestedManyWithoutBarangInput = {
  create?: Prisma.XOR<Prisma.BarisFakturPenjualanCreateWithoutBarangInput, Prisma.BarisFakturPenjualanUncheckedCreateWithoutBarangInput> | Prisma.BarisFakturPenjualanCreateWithoutBarangInput[] | Prisma.BarisFakturPenjualanUncheckedCreateWithoutBarangInput[]
  connectOrCreate?: Prisma.BarisFakturPenjualanCreateOrConnectWithoutBarangInput | Prisma.BarisFakturPenjualanCreateOrConnectWithoutBarangInput[]
  createMany?: Prisma.BarisFakturPenjualanCreateManyBarangInputEnvelope
  connect?: Prisma.BarisFakturPenjualanWhereUniqueInput | Prisma.BarisFakturPenjualanWhereUniqueInput[]
}

export type BarisFakturPenjualanUncheckedCreateNestedManyWithoutBarangInput = {
  create?: Prisma.XOR<Prisma.BarisFakturPenjualanCreateWithoutBarangInput, Prisma.BarisFakturPenjualanUncheckedCreateWithoutBarangInput> | Prisma.BarisFakturPenjualanCreateWithoutBarangInput[] | Prisma.BarisFakturPenjualanUncheckedCreateWithoutBarangInput[]
  connectOrCreate?: Prisma.BarisFakturPenjualanCreateOrConnectWithoutBarangInput | Prisma.BarisFakturPenjualanCreateOrConnectWithoutBarangInput[]
  createMany?: Prisma.BarisFakturPenjualanCreateManyBarangInputEnvelope
  connect?: Prisma.BarisFakturPenjualanWhereUniqueInput | Prisma.BarisFakturPenjualanWhereUniqueInput[]
}

export type BarisFakturPenjualanUpdateManyWithoutBarangNestedInput = {
  create?: Prisma.XOR<Prisma.BarisFakturPenjualanCreateWithoutBarangInput, Prisma.BarisFakturPenjualanUncheckedCreateWithoutBarangInput> | Prisma.BarisFakturPenjualanCreateWithoutBarangInput[] | Prisma.BarisFakturPenjualanUncheckedCreateWithoutBarangInput[]
  connectOrCreate?: Prisma.BarisFakturPenjualanCreateOrConnectWithoutBarangInput | Prisma.BarisFakturPenjualanCreateOrConnectWithoutBarangInput[]
  upsert?: Prisma.BarisFakturPenjualanUpsertWithWhereUniqueWithoutBarangInput | Prisma.BarisFakturPenjualanUpsertWithWhereUniqueWithoutBarangInput[]
  createMany?: Prisma.BarisFakturPenjualanCreateManyBarangInputEnvelope
  set?: Prisma.BarisFakturPenjualanWhereUniqueInput | Prisma.BarisFakturPenjualanWhereUniqueInput[]
  disconnect?: Prisma.BarisFakturPenjualanWhereUniqueInput | Prisma.BarisFakturPenjualanWhereUniqueInput[]
  delete?: Prisma.BarisFakturPenjualanWhereUniqueInput | Prisma.BarisFakturPenjualanWhereUniqueInput[]
  connect?: Prisma.BarisFakturPenjualanWhereUniqueInput | Prisma.BarisFakturPenjualanWhereUniqueInput[]
  update?: Prisma.BarisFakturPenjualanUpdateWithWhereUniqueWithoutBarangInput | Prisma.BarisFakturPenjualanUpdateWithWhereUniqueWithoutBarangInput[]
  updateMany?: Prisma.BarisFakturPenjualanUpdateManyWithWhereWithoutBarangInput | Prisma.BarisFakturPenjualanUpdateManyWithWhereWithoutBarangInput[]
  deleteMany?: Prisma.BarisFakturPenjualanScalarWhereInput | Prisma.BarisFakturPenjualanScalarWhereInput[]
}

export type BarisFakturPenjualanUncheckedUpdateManyWithoutBarangNestedInput = {
  create?: Prisma.XOR<Prisma.BarisFakturPenjualanCreateWithoutBarangInput, Prisma.BarisFakturPenjualanUncheckedCreateWithoutBarangInput> | Prisma.BarisFakturPenjualanCreateWithoutBarangInput[] | Prisma.BarisFakturPenjualanUncheckedCreateWithoutBarangInput[]
  connectOrCreate?: Prisma.BarisFakturPenjualanCreateOrConnectWithoutBarangInput | Prisma.BarisFakturPenjualanCreateOrConnectWithoutBarangInput[]
  upsert?: Prisma.BarisFakturPenjualanUpsertWithWhereUniqueWithoutBarangInput | Prisma.BarisFakturPenjualanUpsertWithWhereUniqueWithoutBarangInput[]
  createMany?: Prisma.BarisFakturPenjualanCreateManyBarangInputEnvelope
  set?: Prisma.BarisFakturPenjualanWhereUniqueInput | Prisma.BarisFakturPenjualanWhereUniqueInput[]
  disconnect?: Prisma.BarisFakturPenjualanWhereUniqueInput | Prisma.BarisFakturPenjualanWhereUniqueInput[]
  delete?: Prisma.BarisFakturPenjualanWhereUniqueInput | Prisma.BarisFakturPenjualanWhereUniqueInput[]
  connect?: Prisma.BarisFakturPenjualanWhereUniqueInput | Prisma.BarisFakturPenjualanWhereUniqueInput[]
  update?: Prisma.BarisFakturPenjualanUpdateWithWhereUniqueWithoutBarangInput | Prisma.BarisFakturPenjualanUpdateWithWhereUniqueWithoutBarangInput[]
  updateMany?: Prisma.BarisFakturPenjualanUpdateManyWithWhereWithoutBarangInput | Prisma.BarisFakturPenjualanUpdateManyWithWhereWithoutBarangInput[]
  deleteMany?: Prisma.BarisFakturPenjualanScalarWhereInput | Prisma.BarisFakturPenjualanScalarWhereInput[]
}

export type BarisFakturPenjualanCreateNestedManyWithoutFakturInput = {
  create?: Prisma.XOR<Prisma.BarisFakturPenjualanCreateWithoutFakturInput, Prisma.BarisFakturPenjualanUncheckedCreateWithoutFakturInput> | Prisma.BarisFakturPenjualanCreateWithoutFakturInput[] | Prisma.BarisFakturPenjualanUncheckedCreateWithoutFakturInput[]
  connectOrCreate?: Prisma.BarisFakturPenjualanCreateOrConnectWithoutFakturInput | Prisma.BarisFakturPenjualanCreateOrConnectWithoutFakturInput[]
  createMany?: Prisma.BarisFakturPenjualanCreateManyFakturInputEnvelope
  connect?: Prisma.BarisFakturPenjualanWhereUniqueInput | Prisma.BarisFakturPenjualanWhereUniqueInput[]
}

export type BarisFakturPenjualanUncheckedCreateNestedManyWithoutFakturInput = {
  create?: Prisma.XOR<Prisma.BarisFakturPenjualanCreateWithoutFakturInput, Prisma.BarisFakturPenjualanUncheckedCreateWithoutFakturInput> | Prisma.BarisFakturPenjualanCreateWithoutFakturInput[] | Prisma.BarisFakturPenjualanUncheckedCreateWithoutFakturInput[]
  connectOrCreate?: Prisma.BarisFakturPenjualanCreateOrConnectWithoutFakturInput | Prisma.BarisFakturPenjualanCreateOrConnectWithoutFakturInput[]
  createMany?: Prisma.BarisFakturPenjualanCreateManyFakturInputEnvelope
  connect?: Prisma.BarisFakturPenjualanWhereUniqueInput | Prisma.BarisFakturPenjualanWhereUniqueInput[]
}

export type BarisFakturPenjualanUpdateManyWithoutFakturNestedInput = {
  create?: Prisma.XOR<Prisma.BarisFakturPenjualanCreateWithoutFakturInput, Prisma.BarisFakturPenjualanUncheckedCreateWithoutFakturInput> | Prisma.BarisFakturPenjualanCreateWithoutFakturInput[] | Prisma.BarisFakturPenjualanUncheckedCreateWithoutFakturInput[]
  connectOrCreate?: Prisma.BarisFakturPenjualanCreateOrConnectWithoutFakturInput | Prisma.BarisFakturPenjualanCreateOrConnectWithoutFakturInput[]
  upsert?: Prisma.BarisFakturPenjualanUpsertWithWhereUniqueWithoutFakturInput | Prisma.BarisFakturPenjualanUpsertWithWhereUniqueWithoutFakturInput[]
  createMany?: Prisma.BarisFakturPenjualanCreateManyFakturInputEnvelope
  set?: Prisma.BarisFakturPenjualanWhereUniqueInput | Prisma.BarisFakturPenjualanWhereUniqueInput[]
  disconnect?: Prisma.BarisFakturPenjualanWhereUniqueInput | Prisma.BarisFakturPenjualanWhereUniqueInput[]
  delete?: Prisma.BarisFakturPenjualanWhereUniqueInput | Prisma.BarisFakturPenjualanWhereUniqueInput[]
  connect?: Prisma.BarisFakturPenjualanWhereUniqueInput | Prisma.BarisFakturPenjualanWhereUniqueInput[]
  update?: Prisma.BarisFakturPenjualanUpdateWithWhereUniqueWithoutFakturInput | Prisma.BarisFakturPenjualanUpdateWithWhereUniqueWithoutFakturInput[]
  updateMany?: Prisma.BarisFakturPenjualanUpdateManyWithWhereWithoutFakturInput | Prisma.BarisFakturPenjualanUpdateManyWithWhereWithoutFakturInput[]
  deleteMany?: Prisma.BarisFakturPenjualanScalarWhereInput | Prisma.BarisFakturPenjualanScalarWhereInput[]
}

export type BarisFakturPenjualanUncheckedUpdateManyWithoutFakturNestedInput = {
  create?: Prisma.XOR<Prisma.BarisFakturPenjualanCreateWithoutFakturInput, Prisma.BarisFakturPenjualanUncheckedCreateWithoutFakturInput> | Prisma.BarisFakturPenjualanCreateWithoutFakturInput[] | Prisma.BarisFakturPenjualanUncheckedCreateWithoutFakturInput[]
  connectOrCreate?: Prisma.BarisFakturPenjualanCreateOrConnectWithoutFakturInput | Prisma.BarisFakturPenjualanCreateOrConnectWithoutFakturInput[]
  upsert?: Prisma.BarisFakturPenjualanUpsertWithWhereUniqueWithoutFakturInput | Prisma.BarisFakturPenjualanUpsertWithWhereUniqueWithoutFakturInput[]
  createMany?: Prisma.BarisFakturPenjualanCreateManyFakturInputEnvelope
  set?: Prisma.BarisFakturPenjualanWhereUniqueInput | Prisma.BarisFakturPenjualanWhereUniqueInput[]
  disconnect?: Prisma.BarisFakturPenjualanWhereUniqueInput | Prisma.BarisFakturPenjualanWhereUniqueInput[]
  delete?: Prisma.BarisFakturPenjualanWhereUniqueInput | Prisma.BarisFakturPenjualanWhereUniqueInput[]
  connect?: Prisma.BarisFakturPenjualanWhereUniqueInput | Prisma.BarisFakturPenjualanWhereUniqueInput[]
  update?: Prisma.BarisFakturPenjualanUpdateWithWhereUniqueWithoutFakturInput | Prisma.BarisFakturPenjualanUpdateWithWhereUniqueWithoutFakturInput[]
  updateMany?: Prisma.BarisFakturPenjualanUpdateManyWithWhereWithoutFakturInput | Prisma.BarisFakturPenjualanUpdateManyWithWhereWithoutFakturInput[]
  deleteMany?: Prisma.BarisFakturPenjualanScalarWhereInput | Prisma.BarisFakturPenjualanScalarWhereInput[]
}

export type BarisFakturPenjualanCreateWithoutBarangInput = {
  id?: string
  jumlah: runtime.Decimal | runtime.DecimalJsLike | number | string
  harga: runtime.Decimal | runtime.DecimalJsLike | number | string
  subtotal: runtime.Decimal | runtime.DecimalJsLike | number | string
  faktur: Prisma.FakturPenjualanCreateNestedOneWithoutBarisInput
}

export type BarisFakturPenjualanUncheckedCreateWithoutBarangInput = {
  id?: string
  fakturId: string
  jumlah: runtime.Decimal | runtime.DecimalJsLike | number | string
  harga: runtime.Decimal | runtime.DecimalJsLike | number | string
  subtotal: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type BarisFakturPenjualanCreateOrConnectWithoutBarangInput = {
  where: Prisma.BarisFakturPenjualanWhereUniqueInput
  create: Prisma.XOR<Prisma.BarisFakturPenjualanCreateWithoutBarangInput, Prisma.BarisFakturPenjualanUncheckedCreateWithoutBarangInput>
}

export type BarisFakturPenjualanCreateManyBarangInputEnvelope = {
  data: Prisma.BarisFakturPenjualanCreateManyBarangInput | Prisma.BarisFakturPenjualanCreateManyBarangInput[]
  skipDuplicates?: boolean
}

export type BarisFakturPenjualanUpsertWithWhereUniqueWithoutBarangInput = {
  where: Prisma.BarisFakturPenjualanWhereUniqueInput
  update: Prisma.XOR<Prisma.BarisFakturPenjualanUpdateWithoutBarangInput, Prisma.BarisFakturPenjualanUncheckedUpdateWithoutBarangInput>
  create: Prisma.XOR<Prisma.BarisFakturPenjualanCreateWithoutBarangInput, Prisma.BarisFakturPenjualanUncheckedCreateWithoutBarangInput>
}

export type BarisFakturPenjualanUpdateWithWhereUniqueWithoutBarangInput = {
  where: Prisma.BarisFakturPenjualanWhereUniqueInput
  data: Prisma.XOR<Prisma.BarisFakturPenjualanUpdateWithoutBarangInput, Prisma.BarisFakturPenjualanUncheckedUpdateWithoutBarangInput>
}

export type BarisFakturPenjualanUpdateManyWithWhereWithoutBarangInput = {
  where: Prisma.BarisFakturPenjualanScalarWhereInput
  data: Prisma.XOR<Prisma.BarisFakturPenjualanUpdateManyMutationInput, Prisma.BarisFakturPenjualanUncheckedUpdateManyWithoutBarangInput>
}

export type BarisFakturPenjualanScalarWhereInput = {
  AND?: Prisma.BarisFakturPenjualanScalarWhereInput | Prisma.BarisFakturPenjualanScalarWhereInput[]
  OR?: Prisma.BarisFakturPenjualanScalarWhereInput[]
  NOT?: Prisma.BarisFakturPenjualanScalarWhereInput | Prisma.BarisFakturPenjualanScalarWhereInput[]
  id?: Prisma.StringFilter<"BarisFakturPenjualan"> | string
  fakturId?: Prisma.StringFilter<"BarisFakturPenjualan"> | string
  barangId?: Prisma.StringFilter<"BarisFakturPenjualan"> | string
  jumlah?: Prisma.DecimalFilter<"BarisFakturPenjualan"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  harga?: Prisma.DecimalFilter<"BarisFakturPenjualan"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  subtotal?: Prisma.DecimalFilter<"BarisFakturPenjualan"> | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type BarisFakturPenjualanCreateWithoutFakturInput = {
  id?: string
  jumlah: runtime.Decimal | runtime.DecimalJsLike | number | string
  harga: runtime.Decimal | runtime.DecimalJsLike | number | string
  subtotal: runtime.Decimal | runtime.DecimalJsLike | number | string
  barang: Prisma.BarangCreateNestedOneWithoutBarisFakturPenjualanInput
}

export type BarisFakturPenjualanUncheckedCreateWithoutFakturInput = {
  id?: string
  barangId: string
  jumlah: runtime.Decimal | runtime.DecimalJsLike | number | string
  harga: runtime.Decimal | runtime.DecimalJsLike | number | string
  subtotal: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type BarisFakturPenjualanCreateOrConnectWithoutFakturInput = {
  where: Prisma.BarisFakturPenjualanWhereUniqueInput
  create: Prisma.XOR<Prisma.BarisFakturPenjualanCreateWithoutFakturInput, Prisma.BarisFakturPenjualanUncheckedCreateWithoutFakturInput>
}

export type BarisFakturPenjualanCreateManyFakturInputEnvelope = {
  data: Prisma.BarisFakturPenjualanCreateManyFakturInput | Prisma.BarisFakturPenjualanCreateManyFakturInput[]
  skipDuplicates?: boolean
}

export type BarisFakturPenjualanUpsertWithWhereUniqueWithoutFakturInput = {
  where: Prisma.BarisFakturPenjualanWhereUniqueInput
  update: Prisma.XOR<Prisma.BarisFakturPenjualanUpdateWithoutFakturInput, Prisma.BarisFakturPenjualanUncheckedUpdateWithoutFakturInput>
  create: Prisma.XOR<Prisma.BarisFakturPenjualanCreateWithoutFakturInput, Prisma.BarisFakturPenjualanUncheckedCreateWithoutFakturInput>
}

export type BarisFakturPenjualanUpdateWithWhereUniqueWithoutFakturInput = {
  where: Prisma.BarisFakturPenjualanWhereUniqueInput
  data: Prisma.XOR<Prisma.BarisFakturPenjualanUpdateWithoutFakturInput, Prisma.BarisFakturPenjualanUncheckedUpdateWithoutFakturInput>
}

export type BarisFakturPenjualanUpdateManyWithWhereWithoutFakturInput = {
  where: Prisma.BarisFakturPenjualanScalarWhereInput
  data: Prisma.XOR<Prisma.BarisFakturPenjualanUpdateManyMutationInput, Prisma.BarisFakturPenjualanUncheckedUpdateManyWithoutFakturInput>
}

export type BarisFakturPenjualanCreateManyBarangInput = {
  id?: string
  fakturId: string
  jumlah: runtime.Decimal | runtime.DecimalJsLike | number | string
  harga: runtime.Decimal | runtime.DecimalJsLike | number | string
  subtotal: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type BarisFakturPenjualanUpdateWithoutBarangInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  jumlah?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  harga?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  subtotal?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  faktur?: Prisma.FakturPenjualanUpdateOneRequiredWithoutBarisNestedInput
}

export type BarisFakturPenjualanUncheckedUpdateWithoutBarangInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fakturId?: Prisma.StringFieldUpdateOperationsInput | string
  jumlah?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  harga?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  subtotal?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type BarisFakturPenjualanUncheckedUpdateManyWithoutBarangInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fakturId?: Prisma.StringFieldUpdateOperationsInput | string
  jumlah?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  harga?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  subtotal?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type BarisFakturPenjualanCreateManyFakturInput = {
  id?: string
  barangId: string
  jumlah: runtime.Decimal | runtime.DecimalJsLike | number | string
  harga: runtime.Decimal | runtime.DecimalJsLike | number | string
  subtotal: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type BarisFakturPenjualanUpdateWithoutFakturInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  jumlah?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  harga?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  subtotal?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  barang?: Prisma.BarangUpdateOneRequiredWithoutBarisFakturPenjualanNestedInput
}

export type BarisFakturPenjualanUncheckedUpdateWithoutFakturInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  barangId?: Prisma.StringFieldUpdateOperationsInput | string
  jumlah?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  harga?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  subtotal?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type BarisFakturPenjualanUncheckedUpdateManyWithoutFakturInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  barangId?: Prisma.StringFieldUpdateOperationsInput | string
  jumlah?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  harga?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  subtotal?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}



export type BarisFakturPenjualanSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fakturId?: boolean
  barangId?: boolean
  jumlah?: boolean
  harga?: boolean
  subtotal?: boolean
  faktur?: boolean | Prisma.FakturPenjualanDefaultArgs<ExtArgs>
  barang?: boolean | Prisma.BarangDefaultArgs<ExtArgs>
}, ExtArgs["result"]["barisFakturPenjualan"]>

export type BarisFakturPenjualanSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fakturId?: boolean
  barangId?: boolean
  jumlah?: boolean
  harga?: boolean
  subtotal?: boolean
  faktur?: boolean | Prisma.FakturPenjualanDefaultArgs<ExtArgs>
  barang?: boolean | Prisma.BarangDefaultArgs<ExtArgs>
}, ExtArgs["result"]["barisFakturPenjualan"]>

export type BarisFakturPenjualanSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fakturId?: boolean
  barangId?: boolean
  jumlah?: boolean
  harga?: boolean
  subtotal?: boolean
  faktur?: boolean | Prisma.FakturPenjualanDefaultArgs<ExtArgs>
  barang?: boolean | Prisma.BarangDefaultArgs<ExtArgs>
}, ExtArgs["result"]["barisFakturPenjualan"]>

export type BarisFakturPenjualanSelectScalar = {
  id?: boolean
  fakturId?: boolean
  barangId?: boolean
  jumlah?: boolean
  harga?: boolean
  subtotal?: boolean
}

export type BarisFakturPenjualanOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "fakturId" | "barangId" | "jumlah" | "harga" | "subtotal", ExtArgs["result"]["barisFakturPenjualan"]>
export type BarisFakturPenjualanInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  faktur?: boolean | Prisma.FakturPenjualanDefaultArgs<ExtArgs>
  barang?: boolean | Prisma.BarangDefaultArgs<ExtArgs>
}
export type BarisFakturPenjualanIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  faktur?: boolean | Prisma.FakturPenjualanDefaultArgs<ExtArgs>
  barang?: boolean | Prisma.BarangDefaultArgs<ExtArgs>
}
export type BarisFakturPenjualanIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  faktur?: boolean | Prisma.FakturPenjualanDefaultArgs<ExtArgs>
  barang?: boolean | Prisma.BarangDefaultArgs<ExtArgs>
}

export type $BarisFakturPenjualanPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BarisFakturPenjualan"
  objects: {
    faktur: Prisma.$FakturPenjualanPayload<ExtArgs>
    barang: Prisma.$BarangPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    fakturId: string
    barangId: string
    jumlah: runtime.Decimal
    harga: runtime.Decimal
    subtotal: runtime.Decimal
  }, ExtArgs["result"]["barisFakturPenjualan"]>
  composites: {}
}

export type BarisFakturPenjualanGetPayload<S extends boolean | null | undefined | BarisFakturPenjualanDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BarisFakturPenjualanPayload, S>

export type BarisFakturPenjualanCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BarisFakturPenjualanFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BarisFakturPenjualanCountAggregateInputType | true
  }

export interface BarisFakturPenjualanDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BarisFakturPenjualan'], meta: { name: 'BarisFakturPenjualan' } }
  /**
   * Find zero or one BarisFakturPenjualan that matches the filter.
   * @param {BarisFakturPenjualanFindUniqueArgs} args - Arguments to find a BarisFakturPenjualan
   * @example
   * // Get one BarisFakturPenjualan
   * const barisFakturPenjualan = await prisma.barisFakturPenjualan.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BarisFakturPenjualanFindUniqueArgs>(args: Prisma.SelectSubset<T, BarisFakturPenjualanFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BarisFakturPenjualanClient<runtime.Types.Result.GetResult<Prisma.$BarisFakturPenjualanPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BarisFakturPenjualan that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BarisFakturPenjualanFindUniqueOrThrowArgs} args - Arguments to find a BarisFakturPenjualan
   * @example
   * // Get one BarisFakturPenjualan
   * const barisFakturPenjualan = await prisma.barisFakturPenjualan.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BarisFakturPenjualanFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BarisFakturPenjualanFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BarisFakturPenjualanClient<runtime.Types.Result.GetResult<Prisma.$BarisFakturPenjualanPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BarisFakturPenjualan that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BarisFakturPenjualanFindFirstArgs} args - Arguments to find a BarisFakturPenjualan
   * @example
   * // Get one BarisFakturPenjualan
   * const barisFakturPenjualan = await prisma.barisFakturPenjualan.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BarisFakturPenjualanFindFirstArgs>(args?: Prisma.SelectSubset<T, BarisFakturPenjualanFindFirstArgs<ExtArgs>>): Prisma.Prisma__BarisFakturPenjualanClient<runtime.Types.Result.GetResult<Prisma.$BarisFakturPenjualanPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BarisFakturPenjualan that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BarisFakturPenjualanFindFirstOrThrowArgs} args - Arguments to find a BarisFakturPenjualan
   * @example
   * // Get one BarisFakturPenjualan
   * const barisFakturPenjualan = await prisma.barisFakturPenjualan.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BarisFakturPenjualanFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BarisFakturPenjualanFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BarisFakturPenjualanClient<runtime.Types.Result.GetResult<Prisma.$BarisFakturPenjualanPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BarisFakturPenjualans that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BarisFakturPenjualanFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BarisFakturPenjualans
   * const barisFakturPenjualans = await prisma.barisFakturPenjualan.findMany()
   * 
   * // Get first 10 BarisFakturPenjualans
   * const barisFakturPenjualans = await prisma.barisFakturPenjualan.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const barisFakturPenjualanWithIdOnly = await prisma.barisFakturPenjualan.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BarisFakturPenjualanFindManyArgs>(args?: Prisma.SelectSubset<T, BarisFakturPenjualanFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BarisFakturPenjualanPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BarisFakturPenjualan.
   * @param {BarisFakturPenjualanCreateArgs} args - Arguments to create a BarisFakturPenjualan.
   * @example
   * // Create one BarisFakturPenjualan
   * const BarisFakturPenjualan = await prisma.barisFakturPenjualan.create({
   *   data: {
   *     // ... data to create a BarisFakturPenjualan
   *   }
   * })
   * 
   */
  create<T extends BarisFakturPenjualanCreateArgs>(args: Prisma.SelectSubset<T, BarisFakturPenjualanCreateArgs<ExtArgs>>): Prisma.Prisma__BarisFakturPenjualanClient<runtime.Types.Result.GetResult<Prisma.$BarisFakturPenjualanPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BarisFakturPenjualans.
   * @param {BarisFakturPenjualanCreateManyArgs} args - Arguments to create many BarisFakturPenjualans.
   * @example
   * // Create many BarisFakturPenjualans
   * const barisFakturPenjualan = await prisma.barisFakturPenjualan.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BarisFakturPenjualanCreateManyArgs>(args?: Prisma.SelectSubset<T, BarisFakturPenjualanCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BarisFakturPenjualans and returns the data saved in the database.
   * @param {BarisFakturPenjualanCreateManyAndReturnArgs} args - Arguments to create many BarisFakturPenjualans.
   * @example
   * // Create many BarisFakturPenjualans
   * const barisFakturPenjualan = await prisma.barisFakturPenjualan.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BarisFakturPenjualans and only return the `id`
   * const barisFakturPenjualanWithIdOnly = await prisma.barisFakturPenjualan.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BarisFakturPenjualanCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BarisFakturPenjualanCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BarisFakturPenjualanPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BarisFakturPenjualan.
   * @param {BarisFakturPenjualanDeleteArgs} args - Arguments to delete one BarisFakturPenjualan.
   * @example
   * // Delete one BarisFakturPenjualan
   * const BarisFakturPenjualan = await prisma.barisFakturPenjualan.delete({
   *   where: {
   *     // ... filter to delete one BarisFakturPenjualan
   *   }
   * })
   * 
   */
  delete<T extends BarisFakturPenjualanDeleteArgs>(args: Prisma.SelectSubset<T, BarisFakturPenjualanDeleteArgs<ExtArgs>>): Prisma.Prisma__BarisFakturPenjualanClient<runtime.Types.Result.GetResult<Prisma.$BarisFakturPenjualanPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BarisFakturPenjualan.
   * @param {BarisFakturPenjualanUpdateArgs} args - Arguments to update one BarisFakturPenjualan.
   * @example
   * // Update one BarisFakturPenjualan
   * const barisFakturPenjualan = await prisma.barisFakturPenjualan.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BarisFakturPenjualanUpdateArgs>(args: Prisma.SelectSubset<T, BarisFakturPenjualanUpdateArgs<ExtArgs>>): Prisma.Prisma__BarisFakturPenjualanClient<runtime.Types.Result.GetResult<Prisma.$BarisFakturPenjualanPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BarisFakturPenjualans.
   * @param {BarisFakturPenjualanDeleteManyArgs} args - Arguments to filter BarisFakturPenjualans to delete.
   * @example
   * // Delete a few BarisFakturPenjualans
   * const { count } = await prisma.barisFakturPenjualan.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BarisFakturPenjualanDeleteManyArgs>(args?: Prisma.SelectSubset<T, BarisFakturPenjualanDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BarisFakturPenjualans.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BarisFakturPenjualanUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BarisFakturPenjualans
   * const barisFakturPenjualan = await prisma.barisFakturPenjualan.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BarisFakturPenjualanUpdateManyArgs>(args: Prisma.SelectSubset<T, BarisFakturPenjualanUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BarisFakturPenjualans and returns the data updated in the database.
   * @param {BarisFakturPenjualanUpdateManyAndReturnArgs} args - Arguments to update many BarisFakturPenjualans.
   * @example
   * // Update many BarisFakturPenjualans
   * const barisFakturPenjualan = await prisma.barisFakturPenjualan.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BarisFakturPenjualans and only return the `id`
   * const barisFakturPenjualanWithIdOnly = await prisma.barisFakturPenjualan.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BarisFakturPenjualanUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BarisFakturPenjualanUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BarisFakturPenjualanPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BarisFakturPenjualan.
   * @param {BarisFakturPenjualanUpsertArgs} args - Arguments to update or create a BarisFakturPenjualan.
   * @example
   * // Update or create a BarisFakturPenjualan
   * const barisFakturPenjualan = await prisma.barisFakturPenjualan.upsert({
   *   create: {
   *     // ... data to create a BarisFakturPenjualan
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BarisFakturPenjualan we want to update
   *   }
   * })
   */
  upsert<T extends BarisFakturPenjualanUpsertArgs>(args: Prisma.SelectSubset<T, BarisFakturPenjualanUpsertArgs<ExtArgs>>): Prisma.Prisma__BarisFakturPenjualanClient<runtime.Types.Result.GetResult<Prisma.$BarisFakturPenjualanPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BarisFakturPenjualans.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BarisFakturPenjualanCountArgs} args - Arguments to filter BarisFakturPenjualans to count.
   * @example
   * // Count the number of BarisFakturPenjualans
   * const count = await prisma.barisFakturPenjualan.count({
   *   where: {
   *     // ... the filter for the BarisFakturPenjualans we want to count
   *   }
   * })
  **/
  count<T extends BarisFakturPenjualanCountArgs>(
    args?: Prisma.Subset<T, BarisFakturPenjualanCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BarisFakturPenjualanCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BarisFakturPenjualan.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BarisFakturPenjualanAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BarisFakturPenjualanAggregateArgs>(args: Prisma.Subset<T, BarisFakturPenjualanAggregateArgs>): Prisma.PrismaPromise<GetBarisFakturPenjualanAggregateType<T>>

  /**
   * Group by BarisFakturPenjualan.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BarisFakturPenjualanGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BarisFakturPenjualanGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BarisFakturPenjualanGroupByArgs['orderBy'] }
      : { orderBy?: BarisFakturPenjualanGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BarisFakturPenjualanGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBarisFakturPenjualanGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BarisFakturPenjualan model
 */
readonly fields: BarisFakturPenjualanFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BarisFakturPenjualan.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BarisFakturPenjualanClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  faktur<T extends Prisma.FakturPenjualanDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FakturPenjualanDefaultArgs<ExtArgs>>): Prisma.Prisma__FakturPenjualanClient<runtime.Types.Result.GetResult<Prisma.$FakturPenjualanPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  barang<T extends Prisma.BarangDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BarangDefaultArgs<ExtArgs>>): Prisma.Prisma__BarangClient<runtime.Types.Result.GetResult<Prisma.$BarangPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BarisFakturPenjualan model
 */
export interface BarisFakturPenjualanFieldRefs {
  readonly id: Prisma.FieldRef<"BarisFakturPenjualan", 'String'>
  readonly fakturId: Prisma.FieldRef<"BarisFakturPenjualan", 'String'>
  readonly barangId: Prisma.FieldRef<"BarisFakturPenjualan", 'String'>
  readonly jumlah: Prisma.FieldRef<"BarisFakturPenjualan", 'Decimal'>
  readonly harga: Prisma.FieldRef<"BarisFakturPenjualan", 'Decimal'>
  readonly subtotal: Prisma.FieldRef<"BarisFakturPenjualan", 'Decimal'>
}
    

// Custom InputTypes
/**
 * BarisFakturPenjualan findUnique
 */
export type BarisFakturPenjualanFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarisFakturPenjualan
   */
  select?: Prisma.BarisFakturPenjualanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BarisFakturPenjualan
   */
  omit?: Prisma.BarisFakturPenjualanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BarisFakturPenjualanInclude<ExtArgs> | null
  /**
   * Filter, which BarisFakturPenjualan to fetch.
   */
  where: Prisma.BarisFakturPenjualanWhereUniqueInput
}

/**
 * BarisFakturPenjualan findUniqueOrThrow
 */
export type BarisFakturPenjualanFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarisFakturPenjualan
   */
  select?: Prisma.BarisFakturPenjualanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BarisFakturPenjualan
   */
  omit?: Prisma.BarisFakturPenjualanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BarisFakturPenjualanInclude<ExtArgs> | null
  /**
   * Filter, which BarisFakturPenjualan to fetch.
   */
  where: Prisma.BarisFakturPenjualanWhereUniqueInput
}

/**
 * BarisFakturPenjualan findFirst
 */
export type BarisFakturPenjualanFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarisFakturPenjualan
   */
  select?: Prisma.BarisFakturPenjualanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BarisFakturPenjualan
   */
  omit?: Prisma.BarisFakturPenjualanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BarisFakturPenjualanInclude<ExtArgs> | null
  /**
   * Filter, which BarisFakturPenjualan to fetch.
   */
  where?: Prisma.BarisFakturPenjualanWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BarisFakturPenjualans to fetch.
   */
  orderBy?: Prisma.BarisFakturPenjualanOrderByWithRelationInput | Prisma.BarisFakturPenjualanOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BarisFakturPenjualans.
   */
  cursor?: Prisma.BarisFakturPenjualanWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BarisFakturPenjualans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BarisFakturPenjualans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BarisFakturPenjualans.
   */
  distinct?: Prisma.BarisFakturPenjualanScalarFieldEnum | Prisma.BarisFakturPenjualanScalarFieldEnum[]
}

/**
 * BarisFakturPenjualan findFirstOrThrow
 */
export type BarisFakturPenjualanFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarisFakturPenjualan
   */
  select?: Prisma.BarisFakturPenjualanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BarisFakturPenjualan
   */
  omit?: Prisma.BarisFakturPenjualanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BarisFakturPenjualanInclude<ExtArgs> | null
  /**
   * Filter, which BarisFakturPenjualan to fetch.
   */
  where?: Prisma.BarisFakturPenjualanWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BarisFakturPenjualans to fetch.
   */
  orderBy?: Prisma.BarisFakturPenjualanOrderByWithRelationInput | Prisma.BarisFakturPenjualanOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BarisFakturPenjualans.
   */
  cursor?: Prisma.BarisFakturPenjualanWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BarisFakturPenjualans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BarisFakturPenjualans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BarisFakturPenjualans.
   */
  distinct?: Prisma.BarisFakturPenjualanScalarFieldEnum | Prisma.BarisFakturPenjualanScalarFieldEnum[]
}

/**
 * BarisFakturPenjualan findMany
 */
export type BarisFakturPenjualanFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarisFakturPenjualan
   */
  select?: Prisma.BarisFakturPenjualanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BarisFakturPenjualan
   */
  omit?: Prisma.BarisFakturPenjualanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BarisFakturPenjualanInclude<ExtArgs> | null
  /**
   * Filter, which BarisFakturPenjualans to fetch.
   */
  where?: Prisma.BarisFakturPenjualanWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BarisFakturPenjualans to fetch.
   */
  orderBy?: Prisma.BarisFakturPenjualanOrderByWithRelationInput | Prisma.BarisFakturPenjualanOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BarisFakturPenjualans.
   */
  cursor?: Prisma.BarisFakturPenjualanWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BarisFakturPenjualans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BarisFakturPenjualans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BarisFakturPenjualans.
   */
  distinct?: Prisma.BarisFakturPenjualanScalarFieldEnum | Prisma.BarisFakturPenjualanScalarFieldEnum[]
}

/**
 * BarisFakturPenjualan create
 */
export type BarisFakturPenjualanCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarisFakturPenjualan
   */
  select?: Prisma.BarisFakturPenjualanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BarisFakturPenjualan
   */
  omit?: Prisma.BarisFakturPenjualanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BarisFakturPenjualanInclude<ExtArgs> | null
  /**
   * The data needed to create a BarisFakturPenjualan.
   */
  data: Prisma.XOR<Prisma.BarisFakturPenjualanCreateInput, Prisma.BarisFakturPenjualanUncheckedCreateInput>
}

/**
 * BarisFakturPenjualan createMany
 */
export type BarisFakturPenjualanCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BarisFakturPenjualans.
   */
  data: Prisma.BarisFakturPenjualanCreateManyInput | Prisma.BarisFakturPenjualanCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BarisFakturPenjualan createManyAndReturn
 */
export type BarisFakturPenjualanCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarisFakturPenjualan
   */
  select?: Prisma.BarisFakturPenjualanSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BarisFakturPenjualan
   */
  omit?: Prisma.BarisFakturPenjualanOmit<ExtArgs> | null
  /**
   * The data used to create many BarisFakturPenjualans.
   */
  data: Prisma.BarisFakturPenjualanCreateManyInput | Prisma.BarisFakturPenjualanCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BarisFakturPenjualanIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * BarisFakturPenjualan update
 */
export type BarisFakturPenjualanUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarisFakturPenjualan
   */
  select?: Prisma.BarisFakturPenjualanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BarisFakturPenjualan
   */
  omit?: Prisma.BarisFakturPenjualanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BarisFakturPenjualanInclude<ExtArgs> | null
  /**
   * The data needed to update a BarisFakturPenjualan.
   */
  data: Prisma.XOR<Prisma.BarisFakturPenjualanUpdateInput, Prisma.BarisFakturPenjualanUncheckedUpdateInput>
  /**
   * Choose, which BarisFakturPenjualan to update.
   */
  where: Prisma.BarisFakturPenjualanWhereUniqueInput
}

/**
 * BarisFakturPenjualan updateMany
 */
export type BarisFakturPenjualanUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BarisFakturPenjualans.
   */
  data: Prisma.XOR<Prisma.BarisFakturPenjualanUpdateManyMutationInput, Prisma.BarisFakturPenjualanUncheckedUpdateManyInput>
  /**
   * Filter which BarisFakturPenjualans to update
   */
  where?: Prisma.BarisFakturPenjualanWhereInput
  /**
   * Limit how many BarisFakturPenjualans to update.
   */
  limit?: number
}

/**
 * BarisFakturPenjualan updateManyAndReturn
 */
export type BarisFakturPenjualanUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarisFakturPenjualan
   */
  select?: Prisma.BarisFakturPenjualanSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BarisFakturPenjualan
   */
  omit?: Prisma.BarisFakturPenjualanOmit<ExtArgs> | null
  /**
   * The data used to update BarisFakturPenjualans.
   */
  data: Prisma.XOR<Prisma.BarisFakturPenjualanUpdateManyMutationInput, Prisma.BarisFakturPenjualanUncheckedUpdateManyInput>
  /**
   * Filter which BarisFakturPenjualans to update
   */
  where?: Prisma.BarisFakturPenjualanWhereInput
  /**
   * Limit how many BarisFakturPenjualans to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BarisFakturPenjualanIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * BarisFakturPenjualan upsert
 */
export type BarisFakturPenjualanUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarisFakturPenjualan
   */
  select?: Prisma.BarisFakturPenjualanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BarisFakturPenjualan
   */
  omit?: Prisma.BarisFakturPenjualanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BarisFakturPenjualanInclude<ExtArgs> | null
  /**
   * The filter to search for the BarisFakturPenjualan to update in case it exists.
   */
  where: Prisma.BarisFakturPenjualanWhereUniqueInput
  /**
   * In case the BarisFakturPenjualan found by the `where` argument doesn't exist, create a new BarisFakturPenjualan with this data.
   */
  create: Prisma.XOR<Prisma.BarisFakturPenjualanCreateInput, Prisma.BarisFakturPenjualanUncheckedCreateInput>
  /**
   * In case the BarisFakturPenjualan was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BarisFakturPenjualanUpdateInput, Prisma.BarisFakturPenjualanUncheckedUpdateInput>
}

/**
 * BarisFakturPenjualan delete
 */
export type BarisFakturPenjualanDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarisFakturPenjualan
   */
  select?: Prisma.BarisFakturPenjualanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BarisFakturPenjualan
   */
  omit?: Prisma.BarisFakturPenjualanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BarisFakturPenjualanInclude<ExtArgs> | null
  /**
   * Filter which BarisFakturPenjualan to delete.
   */
  where: Prisma.BarisFakturPenjualanWhereUniqueInput
}

/**
 * BarisFakturPenjualan deleteMany
 */
export type BarisFakturPenjualanDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BarisFakturPenjualans to delete
   */
  where?: Prisma.BarisFakturPenjualanWhereInput
  /**
   * Limit how many BarisFakturPenjualans to delete.
   */
  limit?: number
}

/**
 * BarisFakturPenjualan without action
 */
export type BarisFakturPenjualanDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarisFakturPenjualan
   */
  select?: Prisma.BarisFakturPenjualanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BarisFakturPenjualan
   */
  omit?: Prisma.BarisFakturPenjualanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BarisFakturPenjualanInclude<ExtArgs> | null
}
