
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `HakAksesPeran` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model HakAksesPeran
 * Penyesuaian hak akses per peran (Pengaturan › Hak Akses); bawaan ada di src/lib/hakAkses.ts
 */
export type HakAksesPeranModel = runtime.Types.Result.DefaultSelection<Prisma.$HakAksesPeranPayload>

export type AggregateHakAksesPeran = {
  _count: HakAksesPeranCountAggregateOutputType | null
  _min: HakAksesPeranMinAggregateOutputType | null
  _max: HakAksesPeranMaxAggregateOutputType | null
}

export type HakAksesPeranMinAggregateOutputType = {
  peran: $Enums.PeranPengguna | null
  hak: string | null
  boleh: boolean | null
}

export type HakAksesPeranMaxAggregateOutputType = {
  peran: $Enums.PeranPengguna | null
  hak: string | null
  boleh: boolean | null
}

export type HakAksesPeranCountAggregateOutputType = {
  peran: number
  hak: number
  boleh: number
  _all: number
}


export type HakAksesPeranMinAggregateInputType = {
  peran?: true
  hak?: true
  boleh?: true
}

export type HakAksesPeranMaxAggregateInputType = {
  peran?: true
  hak?: true
  boleh?: true
}

export type HakAksesPeranCountAggregateInputType = {
  peran?: true
  hak?: true
  boleh?: true
  _all?: true
}

export type HakAksesPeranAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which HakAksesPeran to aggregate.
   */
  where?: Prisma.HakAksesPeranWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HakAksesPerans to fetch.
   */
  orderBy?: Prisma.HakAksesPeranOrderByWithRelationInput | Prisma.HakAksesPeranOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.HakAksesPeranWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HakAksesPerans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HakAksesPerans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned HakAksesPerans
  **/
  _count?: true | HakAksesPeranCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: HakAksesPeranMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: HakAksesPeranMaxAggregateInputType
}

export type GetHakAksesPeranAggregateType<T extends HakAksesPeranAggregateArgs> = {
      [P in keyof T & keyof AggregateHakAksesPeran]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateHakAksesPeran[P]>
    : Prisma.GetScalarType<T[P], AggregateHakAksesPeran[P]>
}




export type HakAksesPeranGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.HakAksesPeranWhereInput
  orderBy?: Prisma.HakAksesPeranOrderByWithAggregationInput | Prisma.HakAksesPeranOrderByWithAggregationInput[]
  by: Prisma.HakAksesPeranScalarFieldEnum[] | Prisma.HakAksesPeranScalarFieldEnum
  having?: Prisma.HakAksesPeranScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: HakAksesPeranCountAggregateInputType | true
  _min?: HakAksesPeranMinAggregateInputType
  _max?: HakAksesPeranMaxAggregateInputType
}

export type HakAksesPeranGroupByOutputType = {
  peran: $Enums.PeranPengguna
  hak: string
  boleh: boolean
  _count: HakAksesPeranCountAggregateOutputType | null
  _min: HakAksesPeranMinAggregateOutputType | null
  _max: HakAksesPeranMaxAggregateOutputType | null
}

export type GetHakAksesPeranGroupByPayload<T extends HakAksesPeranGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<HakAksesPeranGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof HakAksesPeranGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], HakAksesPeranGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], HakAksesPeranGroupByOutputType[P]>
      }
    >
  >



export type HakAksesPeranWhereInput = {
  AND?: Prisma.HakAksesPeranWhereInput | Prisma.HakAksesPeranWhereInput[]
  OR?: Prisma.HakAksesPeranWhereInput[]
  NOT?: Prisma.HakAksesPeranWhereInput | Prisma.HakAksesPeranWhereInput[]
  peran?: Prisma.EnumPeranPenggunaFilter<"HakAksesPeran"> | $Enums.PeranPengguna
  hak?: Prisma.StringFilter<"HakAksesPeran"> | string
  boleh?: Prisma.BoolFilter<"HakAksesPeran"> | boolean
}

export type HakAksesPeranOrderByWithRelationInput = {
  peran?: Prisma.SortOrder
  hak?: Prisma.SortOrder
  boleh?: Prisma.SortOrder
}

export type HakAksesPeranWhereUniqueInput = Prisma.AtLeast<{
  peran_hak?: Prisma.HakAksesPeranPeranHakCompoundUniqueInput
  AND?: Prisma.HakAksesPeranWhereInput | Prisma.HakAksesPeranWhereInput[]
  OR?: Prisma.HakAksesPeranWhereInput[]
  NOT?: Prisma.HakAksesPeranWhereInput | Prisma.HakAksesPeranWhereInput[]
  peran?: Prisma.EnumPeranPenggunaFilter<"HakAksesPeran"> | $Enums.PeranPengguna
  hak?: Prisma.StringFilter<"HakAksesPeran"> | string
  boleh?: Prisma.BoolFilter<"HakAksesPeran"> | boolean
}, "peran_hak">

export type HakAksesPeranOrderByWithAggregationInput = {
  peran?: Prisma.SortOrder
  hak?: Prisma.SortOrder
  boleh?: Prisma.SortOrder
  _count?: Prisma.HakAksesPeranCountOrderByAggregateInput
  _max?: Prisma.HakAksesPeranMaxOrderByAggregateInput
  _min?: Prisma.HakAksesPeranMinOrderByAggregateInput
}

export type HakAksesPeranScalarWhereWithAggregatesInput = {
  AND?: Prisma.HakAksesPeranScalarWhereWithAggregatesInput | Prisma.HakAksesPeranScalarWhereWithAggregatesInput[]
  OR?: Prisma.HakAksesPeranScalarWhereWithAggregatesInput[]
  NOT?: Prisma.HakAksesPeranScalarWhereWithAggregatesInput | Prisma.HakAksesPeranScalarWhereWithAggregatesInput[]
  peran?: Prisma.EnumPeranPenggunaWithAggregatesFilter<"HakAksesPeran"> | $Enums.PeranPengguna
  hak?: Prisma.StringWithAggregatesFilter<"HakAksesPeran"> | string
  boleh?: Prisma.BoolWithAggregatesFilter<"HakAksesPeran"> | boolean
}

export type HakAksesPeranCreateInput = {
  peran: $Enums.PeranPengguna
  hak: string
  boleh: boolean
}

export type HakAksesPeranUncheckedCreateInput = {
  peran: $Enums.PeranPengguna
  hak: string
  boleh: boolean
}

export type HakAksesPeranUpdateInput = {
  peran?: Prisma.EnumPeranPenggunaFieldUpdateOperationsInput | $Enums.PeranPengguna
  hak?: Prisma.StringFieldUpdateOperationsInput | string
  boleh?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type HakAksesPeranUncheckedUpdateInput = {
  peran?: Prisma.EnumPeranPenggunaFieldUpdateOperationsInput | $Enums.PeranPengguna
  hak?: Prisma.StringFieldUpdateOperationsInput | string
  boleh?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type HakAksesPeranCreateManyInput = {
  peran: $Enums.PeranPengguna
  hak: string
  boleh: boolean
}

export type HakAksesPeranUpdateManyMutationInput = {
  peran?: Prisma.EnumPeranPenggunaFieldUpdateOperationsInput | $Enums.PeranPengguna
  hak?: Prisma.StringFieldUpdateOperationsInput | string
  boleh?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type HakAksesPeranUncheckedUpdateManyInput = {
  peran?: Prisma.EnumPeranPenggunaFieldUpdateOperationsInput | $Enums.PeranPengguna
  hak?: Prisma.StringFieldUpdateOperationsInput | string
  boleh?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type HakAksesPeranPeranHakCompoundUniqueInput = {
  peran: $Enums.PeranPengguna
  hak: string
}

export type HakAksesPeranCountOrderByAggregateInput = {
  peran?: Prisma.SortOrder
  hak?: Prisma.SortOrder
  boleh?: Prisma.SortOrder
}

export type HakAksesPeranMaxOrderByAggregateInput = {
  peran?: Prisma.SortOrder
  hak?: Prisma.SortOrder
  boleh?: Prisma.SortOrder
}

export type HakAksesPeranMinOrderByAggregateInput = {
  peran?: Prisma.SortOrder
  hak?: Prisma.SortOrder
  boleh?: Prisma.SortOrder
}



export type HakAksesPeranSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  peran?: boolean
  hak?: boolean
  boleh?: boolean
}, ExtArgs["result"]["hakAksesPeran"]>

export type HakAksesPeranSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  peran?: boolean
  hak?: boolean
  boleh?: boolean
}, ExtArgs["result"]["hakAksesPeran"]>

export type HakAksesPeranSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  peran?: boolean
  hak?: boolean
  boleh?: boolean
}, ExtArgs["result"]["hakAksesPeran"]>

export type HakAksesPeranSelectScalar = {
  peran?: boolean
  hak?: boolean
  boleh?: boolean
}

export type HakAksesPeranOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"peran" | "hak" | "boleh", ExtArgs["result"]["hakAksesPeran"]>

export type $HakAksesPeranPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "HakAksesPeran"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    peran: $Enums.PeranPengguna
    hak: string
    boleh: boolean
  }, ExtArgs["result"]["hakAksesPeran"]>
  composites: {}
}

export type HakAksesPeranGetPayload<S extends boolean | null | undefined | HakAksesPeranDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$HakAksesPeranPayload, S>

export type HakAksesPeranCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<HakAksesPeranFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: HakAksesPeranCountAggregateInputType | true
  }

export interface HakAksesPeranDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['HakAksesPeran'], meta: { name: 'HakAksesPeran' } }
  /**
   * Find zero or one HakAksesPeran that matches the filter.
   * @param {HakAksesPeranFindUniqueArgs} args - Arguments to find a HakAksesPeran
   * @example
   * // Get one HakAksesPeran
   * const hakAksesPeran = await prisma.hakAksesPeran.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends HakAksesPeranFindUniqueArgs>(args: Prisma.SelectSubset<T, HakAksesPeranFindUniqueArgs<ExtArgs>>): Prisma.Prisma__HakAksesPeranClient<runtime.Types.Result.GetResult<Prisma.$HakAksesPeranPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one HakAksesPeran that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {HakAksesPeranFindUniqueOrThrowArgs} args - Arguments to find a HakAksesPeran
   * @example
   * // Get one HakAksesPeran
   * const hakAksesPeran = await prisma.hakAksesPeran.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends HakAksesPeranFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, HakAksesPeranFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__HakAksesPeranClient<runtime.Types.Result.GetResult<Prisma.$HakAksesPeranPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first HakAksesPeran that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HakAksesPeranFindFirstArgs} args - Arguments to find a HakAksesPeran
   * @example
   * // Get one HakAksesPeran
   * const hakAksesPeran = await prisma.hakAksesPeran.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends HakAksesPeranFindFirstArgs>(args?: Prisma.SelectSubset<T, HakAksesPeranFindFirstArgs<ExtArgs>>): Prisma.Prisma__HakAksesPeranClient<runtime.Types.Result.GetResult<Prisma.$HakAksesPeranPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first HakAksesPeran that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HakAksesPeranFindFirstOrThrowArgs} args - Arguments to find a HakAksesPeran
   * @example
   * // Get one HakAksesPeran
   * const hakAksesPeran = await prisma.hakAksesPeran.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends HakAksesPeranFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, HakAksesPeranFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__HakAksesPeranClient<runtime.Types.Result.GetResult<Prisma.$HakAksesPeranPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more HakAksesPerans that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HakAksesPeranFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all HakAksesPerans
   * const hakAksesPerans = await prisma.hakAksesPeran.findMany()
   * 
   * // Get first 10 HakAksesPerans
   * const hakAksesPerans = await prisma.hakAksesPeran.findMany({ take: 10 })
   * 
   * // Only select the `hak`
   * const hakAksesPeranWithHakOnly = await prisma.hakAksesPeran.findMany({ select: { hak: true } })
   * 
   */
  findMany<T extends HakAksesPeranFindManyArgs>(args?: Prisma.SelectSubset<T, HakAksesPeranFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HakAksesPeranPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a HakAksesPeran.
   * @param {HakAksesPeranCreateArgs} args - Arguments to create a HakAksesPeran.
   * @example
   * // Create one HakAksesPeran
   * const HakAksesPeran = await prisma.hakAksesPeran.create({
   *   data: {
   *     // ... data to create a HakAksesPeran
   *   }
   * })
   * 
   */
  create<T extends HakAksesPeranCreateArgs>(args: Prisma.SelectSubset<T, HakAksesPeranCreateArgs<ExtArgs>>): Prisma.Prisma__HakAksesPeranClient<runtime.Types.Result.GetResult<Prisma.$HakAksesPeranPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many HakAksesPerans.
   * @param {HakAksesPeranCreateManyArgs} args - Arguments to create many HakAksesPerans.
   * @example
   * // Create many HakAksesPerans
   * const hakAksesPeran = await prisma.hakAksesPeran.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends HakAksesPeranCreateManyArgs>(args?: Prisma.SelectSubset<T, HakAksesPeranCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many HakAksesPerans and returns the data saved in the database.
   * @param {HakAksesPeranCreateManyAndReturnArgs} args - Arguments to create many HakAksesPerans.
   * @example
   * // Create many HakAksesPerans
   * const hakAksesPeran = await prisma.hakAksesPeran.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many HakAksesPerans and only return the `hak`
   * const hakAksesPeranWithHakOnly = await prisma.hakAksesPeran.createManyAndReturn({
   *   select: { hak: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends HakAksesPeranCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, HakAksesPeranCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HakAksesPeranPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a HakAksesPeran.
   * @param {HakAksesPeranDeleteArgs} args - Arguments to delete one HakAksesPeran.
   * @example
   * // Delete one HakAksesPeran
   * const HakAksesPeran = await prisma.hakAksesPeran.delete({
   *   where: {
   *     // ... filter to delete one HakAksesPeran
   *   }
   * })
   * 
   */
  delete<T extends HakAksesPeranDeleteArgs>(args: Prisma.SelectSubset<T, HakAksesPeranDeleteArgs<ExtArgs>>): Prisma.Prisma__HakAksesPeranClient<runtime.Types.Result.GetResult<Prisma.$HakAksesPeranPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one HakAksesPeran.
   * @param {HakAksesPeranUpdateArgs} args - Arguments to update one HakAksesPeran.
   * @example
   * // Update one HakAksesPeran
   * const hakAksesPeran = await prisma.hakAksesPeran.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends HakAksesPeranUpdateArgs>(args: Prisma.SelectSubset<T, HakAksesPeranUpdateArgs<ExtArgs>>): Prisma.Prisma__HakAksesPeranClient<runtime.Types.Result.GetResult<Prisma.$HakAksesPeranPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more HakAksesPerans.
   * @param {HakAksesPeranDeleteManyArgs} args - Arguments to filter HakAksesPerans to delete.
   * @example
   * // Delete a few HakAksesPerans
   * const { count } = await prisma.hakAksesPeran.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends HakAksesPeranDeleteManyArgs>(args?: Prisma.SelectSubset<T, HakAksesPeranDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more HakAksesPerans.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HakAksesPeranUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many HakAksesPerans
   * const hakAksesPeran = await prisma.hakAksesPeran.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends HakAksesPeranUpdateManyArgs>(args: Prisma.SelectSubset<T, HakAksesPeranUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more HakAksesPerans and returns the data updated in the database.
   * @param {HakAksesPeranUpdateManyAndReturnArgs} args - Arguments to update many HakAksesPerans.
   * @example
   * // Update many HakAksesPerans
   * const hakAksesPeran = await prisma.hakAksesPeran.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more HakAksesPerans and only return the `hak`
   * const hakAksesPeranWithHakOnly = await prisma.hakAksesPeran.updateManyAndReturn({
   *   select: { hak: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends HakAksesPeranUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, HakAksesPeranUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HakAksesPeranPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one HakAksesPeran.
   * @param {HakAksesPeranUpsertArgs} args - Arguments to update or create a HakAksesPeran.
   * @example
   * // Update or create a HakAksesPeran
   * const hakAksesPeran = await prisma.hakAksesPeran.upsert({
   *   create: {
   *     // ... data to create a HakAksesPeran
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the HakAksesPeran we want to update
   *   }
   * })
   */
  upsert<T extends HakAksesPeranUpsertArgs>(args: Prisma.SelectSubset<T, HakAksesPeranUpsertArgs<ExtArgs>>): Prisma.Prisma__HakAksesPeranClient<runtime.Types.Result.GetResult<Prisma.$HakAksesPeranPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of HakAksesPerans.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HakAksesPeranCountArgs} args - Arguments to filter HakAksesPerans to count.
   * @example
   * // Count the number of HakAksesPerans
   * const count = await prisma.hakAksesPeran.count({
   *   where: {
   *     // ... the filter for the HakAksesPerans we want to count
   *   }
   * })
  **/
  count<T extends HakAksesPeranCountArgs>(
    args?: Prisma.Subset<T, HakAksesPeranCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], HakAksesPeranCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a HakAksesPeran.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HakAksesPeranAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends HakAksesPeranAggregateArgs>(args: Prisma.Subset<T, HakAksesPeranAggregateArgs>): Prisma.PrismaPromise<GetHakAksesPeranAggregateType<T>>

  /**
   * Group by HakAksesPeran.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HakAksesPeranGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends HakAksesPeranGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: HakAksesPeranGroupByArgs['orderBy'] }
      : { orderBy?: HakAksesPeranGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, HakAksesPeranGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetHakAksesPeranGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the HakAksesPeran model
 */
readonly fields: HakAksesPeranFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for HakAksesPeran.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__HakAksesPeranClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the HakAksesPeran model
 */
export interface HakAksesPeranFieldRefs {
  readonly peran: Prisma.FieldRef<"HakAksesPeran", 'PeranPengguna'>
  readonly hak: Prisma.FieldRef<"HakAksesPeran", 'String'>
  readonly boleh: Prisma.FieldRef<"HakAksesPeran", 'Boolean'>
}
    

// Custom InputTypes
/**
 * HakAksesPeran findUnique
 */
export type HakAksesPeranFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HakAksesPeran
   */
  select?: Prisma.HakAksesPeranSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HakAksesPeran
   */
  omit?: Prisma.HakAksesPeranOmit<ExtArgs> | null
  /**
   * Filter, which HakAksesPeran to fetch.
   */
  where: Prisma.HakAksesPeranWhereUniqueInput
}

/**
 * HakAksesPeran findUniqueOrThrow
 */
export type HakAksesPeranFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HakAksesPeran
   */
  select?: Prisma.HakAksesPeranSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HakAksesPeran
   */
  omit?: Prisma.HakAksesPeranOmit<ExtArgs> | null
  /**
   * Filter, which HakAksesPeran to fetch.
   */
  where: Prisma.HakAksesPeranWhereUniqueInput
}

/**
 * HakAksesPeran findFirst
 */
export type HakAksesPeranFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HakAksesPeran
   */
  select?: Prisma.HakAksesPeranSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HakAksesPeran
   */
  omit?: Prisma.HakAksesPeranOmit<ExtArgs> | null
  /**
   * Filter, which HakAksesPeran to fetch.
   */
  where?: Prisma.HakAksesPeranWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HakAksesPerans to fetch.
   */
  orderBy?: Prisma.HakAksesPeranOrderByWithRelationInput | Prisma.HakAksesPeranOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for HakAksesPerans.
   */
  cursor?: Prisma.HakAksesPeranWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HakAksesPerans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HakAksesPerans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of HakAksesPerans.
   */
  distinct?: Prisma.HakAksesPeranScalarFieldEnum | Prisma.HakAksesPeranScalarFieldEnum[]
}

/**
 * HakAksesPeran findFirstOrThrow
 */
export type HakAksesPeranFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HakAksesPeran
   */
  select?: Prisma.HakAksesPeranSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HakAksesPeran
   */
  omit?: Prisma.HakAksesPeranOmit<ExtArgs> | null
  /**
   * Filter, which HakAksesPeran to fetch.
   */
  where?: Prisma.HakAksesPeranWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HakAksesPerans to fetch.
   */
  orderBy?: Prisma.HakAksesPeranOrderByWithRelationInput | Prisma.HakAksesPeranOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for HakAksesPerans.
   */
  cursor?: Prisma.HakAksesPeranWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HakAksesPerans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HakAksesPerans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of HakAksesPerans.
   */
  distinct?: Prisma.HakAksesPeranScalarFieldEnum | Prisma.HakAksesPeranScalarFieldEnum[]
}

/**
 * HakAksesPeran findMany
 */
export type HakAksesPeranFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HakAksesPeran
   */
  select?: Prisma.HakAksesPeranSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HakAksesPeran
   */
  omit?: Prisma.HakAksesPeranOmit<ExtArgs> | null
  /**
   * Filter, which HakAksesPerans to fetch.
   */
  where?: Prisma.HakAksesPeranWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HakAksesPerans to fetch.
   */
  orderBy?: Prisma.HakAksesPeranOrderByWithRelationInput | Prisma.HakAksesPeranOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing HakAksesPerans.
   */
  cursor?: Prisma.HakAksesPeranWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HakAksesPerans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HakAksesPerans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of HakAksesPerans.
   */
  distinct?: Prisma.HakAksesPeranScalarFieldEnum | Prisma.HakAksesPeranScalarFieldEnum[]
}

/**
 * HakAksesPeran create
 */
export type HakAksesPeranCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HakAksesPeran
   */
  select?: Prisma.HakAksesPeranSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HakAksesPeran
   */
  omit?: Prisma.HakAksesPeranOmit<ExtArgs> | null
  /**
   * The data needed to create a HakAksesPeran.
   */
  data: Prisma.XOR<Prisma.HakAksesPeranCreateInput, Prisma.HakAksesPeranUncheckedCreateInput>
}

/**
 * HakAksesPeran createMany
 */
export type HakAksesPeranCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many HakAksesPerans.
   */
  data: Prisma.HakAksesPeranCreateManyInput | Prisma.HakAksesPeranCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * HakAksesPeran createManyAndReturn
 */
export type HakAksesPeranCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HakAksesPeran
   */
  select?: Prisma.HakAksesPeranSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the HakAksesPeran
   */
  omit?: Prisma.HakAksesPeranOmit<ExtArgs> | null
  /**
   * The data used to create many HakAksesPerans.
   */
  data: Prisma.HakAksesPeranCreateManyInput | Prisma.HakAksesPeranCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * HakAksesPeran update
 */
export type HakAksesPeranUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HakAksesPeran
   */
  select?: Prisma.HakAksesPeranSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HakAksesPeran
   */
  omit?: Prisma.HakAksesPeranOmit<ExtArgs> | null
  /**
   * The data needed to update a HakAksesPeran.
   */
  data: Prisma.XOR<Prisma.HakAksesPeranUpdateInput, Prisma.HakAksesPeranUncheckedUpdateInput>
  /**
   * Choose, which HakAksesPeran to update.
   */
  where: Prisma.HakAksesPeranWhereUniqueInput
}

/**
 * HakAksesPeran updateMany
 */
export type HakAksesPeranUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update HakAksesPerans.
   */
  data: Prisma.XOR<Prisma.HakAksesPeranUpdateManyMutationInput, Prisma.HakAksesPeranUncheckedUpdateManyInput>
  /**
   * Filter which HakAksesPerans to update
   */
  where?: Prisma.HakAksesPeranWhereInput
  /**
   * Limit how many HakAksesPerans to update.
   */
  limit?: number
}

/**
 * HakAksesPeran updateManyAndReturn
 */
export type HakAksesPeranUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HakAksesPeran
   */
  select?: Prisma.HakAksesPeranSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the HakAksesPeran
   */
  omit?: Prisma.HakAksesPeranOmit<ExtArgs> | null
  /**
   * The data used to update HakAksesPerans.
   */
  data: Prisma.XOR<Prisma.HakAksesPeranUpdateManyMutationInput, Prisma.HakAksesPeranUncheckedUpdateManyInput>
  /**
   * Filter which HakAksesPerans to update
   */
  where?: Prisma.HakAksesPeranWhereInput
  /**
   * Limit how many HakAksesPerans to update.
   */
  limit?: number
}

/**
 * HakAksesPeran upsert
 */
export type HakAksesPeranUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HakAksesPeran
   */
  select?: Prisma.HakAksesPeranSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HakAksesPeran
   */
  omit?: Prisma.HakAksesPeranOmit<ExtArgs> | null
  /**
   * The filter to search for the HakAksesPeran to update in case it exists.
   */
  where: Prisma.HakAksesPeranWhereUniqueInput
  /**
   * In case the HakAksesPeran found by the `where` argument doesn't exist, create a new HakAksesPeran with this data.
   */
  create: Prisma.XOR<Prisma.HakAksesPeranCreateInput, Prisma.HakAksesPeranUncheckedCreateInput>
  /**
   * In case the HakAksesPeran was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.HakAksesPeranUpdateInput, Prisma.HakAksesPeranUncheckedUpdateInput>
}

/**
 * HakAksesPeran delete
 */
export type HakAksesPeranDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HakAksesPeran
   */
  select?: Prisma.HakAksesPeranSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HakAksesPeran
   */
  omit?: Prisma.HakAksesPeranOmit<ExtArgs> | null
  /**
   * Filter which HakAksesPeran to delete.
   */
  where: Prisma.HakAksesPeranWhereUniqueInput
}

/**
 * HakAksesPeran deleteMany
 */
export type HakAksesPeranDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which HakAksesPerans to delete
   */
  where?: Prisma.HakAksesPeranWhereInput
  /**
   * Limit how many HakAksesPerans to delete.
   */
  limit?: number
}

/**
 * HakAksesPeran without action
 */
export type HakAksesPeranDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HakAksesPeran
   */
  select?: Prisma.HakAksesPeranSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HakAksesPeran
   */
  omit?: Prisma.HakAksesPeranOmit<ExtArgs> | null
}
