
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `KursMataUang` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model KursMataUang
 * Riwayat kurs terhadap IDR: 1 unit mata uang = `kurs` rupiah pada `tanggal`.
 * Dokumen menyimpan kurs yang dipakai (snapshot), jadi jurnal lama tidak berubah saat kurs baru dimasukkan.
 */
export type KursMataUangModel = runtime.Types.Result.DefaultSelection<Prisma.$KursMataUangPayload>

export type AggregateKursMataUang = {
  _count: KursMataUangCountAggregateOutputType | null
  _avg: KursMataUangAvgAggregateOutputType | null
  _sum: KursMataUangSumAggregateOutputType | null
  _min: KursMataUangMinAggregateOutputType | null
  _max: KursMataUangMaxAggregateOutputType | null
}

export type KursMataUangAvgAggregateOutputType = {
  kurs: runtime.Decimal | null
}

export type KursMataUangSumAggregateOutputType = {
  kurs: runtime.Decimal | null
}

export type KursMataUangMinAggregateOutputType = {
  id: string | null
  mataUangId: string | null
  tanggal: Date | null
  kurs: runtime.Decimal | null
  sumber: string | null
  dicatatOleh: string | null
  dibuatPada: Date | null
}

export type KursMataUangMaxAggregateOutputType = {
  id: string | null
  mataUangId: string | null
  tanggal: Date | null
  kurs: runtime.Decimal | null
  sumber: string | null
  dicatatOleh: string | null
  dibuatPada: Date | null
}

export type KursMataUangCountAggregateOutputType = {
  id: number
  mataUangId: number
  tanggal: number
  kurs: number
  sumber: number
  dicatatOleh: number
  dibuatPada: number
  _all: number
}


export type KursMataUangAvgAggregateInputType = {
  kurs?: true
}

export type KursMataUangSumAggregateInputType = {
  kurs?: true
}

export type KursMataUangMinAggregateInputType = {
  id?: true
  mataUangId?: true
  tanggal?: true
  kurs?: true
  sumber?: true
  dicatatOleh?: true
  dibuatPada?: true
}

export type KursMataUangMaxAggregateInputType = {
  id?: true
  mataUangId?: true
  tanggal?: true
  kurs?: true
  sumber?: true
  dicatatOleh?: true
  dibuatPada?: true
}

export type KursMataUangCountAggregateInputType = {
  id?: true
  mataUangId?: true
  tanggal?: true
  kurs?: true
  sumber?: true
  dicatatOleh?: true
  dibuatPada?: true
  _all?: true
}

export type KursMataUangAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which KursMataUang to aggregate.
   */
  where?: Prisma.KursMataUangWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KursMataUangs to fetch.
   */
  orderBy?: Prisma.KursMataUangOrderByWithRelationInput | Prisma.KursMataUangOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.KursMataUangWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KursMataUangs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KursMataUangs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned KursMataUangs
  **/
  _count?: true | KursMataUangCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: KursMataUangAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: KursMataUangSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: KursMataUangMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: KursMataUangMaxAggregateInputType
}

export type GetKursMataUangAggregateType<T extends KursMataUangAggregateArgs> = {
      [P in keyof T & keyof AggregateKursMataUang]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateKursMataUang[P]>
    : Prisma.GetScalarType<T[P], AggregateKursMataUang[P]>
}




export type KursMataUangGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.KursMataUangWhereInput
  orderBy?: Prisma.KursMataUangOrderByWithAggregationInput | Prisma.KursMataUangOrderByWithAggregationInput[]
  by: Prisma.KursMataUangScalarFieldEnum[] | Prisma.KursMataUangScalarFieldEnum
  having?: Prisma.KursMataUangScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: KursMataUangCountAggregateInputType | true
  _avg?: KursMataUangAvgAggregateInputType
  _sum?: KursMataUangSumAggregateInputType
  _min?: KursMataUangMinAggregateInputType
  _max?: KursMataUangMaxAggregateInputType
}

export type KursMataUangGroupByOutputType = {
  id: string
  mataUangId: string
  tanggal: Date
  kurs: runtime.Decimal
  sumber: string | null
  dicatatOleh: string | null
  dibuatPada: Date
  _count: KursMataUangCountAggregateOutputType | null
  _avg: KursMataUangAvgAggregateOutputType | null
  _sum: KursMataUangSumAggregateOutputType | null
  _min: KursMataUangMinAggregateOutputType | null
  _max: KursMataUangMaxAggregateOutputType | null
}

export type GetKursMataUangGroupByPayload<T extends KursMataUangGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<KursMataUangGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof KursMataUangGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], KursMataUangGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], KursMataUangGroupByOutputType[P]>
      }
    >
  >



export type KursMataUangWhereInput = {
  AND?: Prisma.KursMataUangWhereInput | Prisma.KursMataUangWhereInput[]
  OR?: Prisma.KursMataUangWhereInput[]
  NOT?: Prisma.KursMataUangWhereInput | Prisma.KursMataUangWhereInput[]
  id?: Prisma.StringFilter<"KursMataUang"> | string
  mataUangId?: Prisma.StringFilter<"KursMataUang"> | string
  tanggal?: Prisma.DateTimeFilter<"KursMataUang"> | Date | string
  kurs?: Prisma.DecimalFilter<"KursMataUang"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  sumber?: Prisma.StringNullableFilter<"KursMataUang"> | string | null
  dicatatOleh?: Prisma.StringNullableFilter<"KursMataUang"> | string | null
  dibuatPada?: Prisma.DateTimeFilter<"KursMataUang"> | Date | string
  mataUang?: Prisma.XOR<Prisma.MataUangScalarRelationFilter, Prisma.MataUangWhereInput>
}

export type KursMataUangOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  mataUangId?: Prisma.SortOrder
  tanggal?: Prisma.SortOrder
  kurs?: Prisma.SortOrder
  sumber?: Prisma.SortOrderInput | Prisma.SortOrder
  dicatatOleh?: Prisma.SortOrderInput | Prisma.SortOrder
  dibuatPada?: Prisma.SortOrder
  mataUang?: Prisma.MataUangOrderByWithRelationInput
}

export type KursMataUangWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  mataUangId_tanggal?: Prisma.KursMataUangMataUangIdTanggalCompoundUniqueInput
  AND?: Prisma.KursMataUangWhereInput | Prisma.KursMataUangWhereInput[]
  OR?: Prisma.KursMataUangWhereInput[]
  NOT?: Prisma.KursMataUangWhereInput | Prisma.KursMataUangWhereInput[]
  mataUangId?: Prisma.StringFilter<"KursMataUang"> | string
  tanggal?: Prisma.DateTimeFilter<"KursMataUang"> | Date | string
  kurs?: Prisma.DecimalFilter<"KursMataUang"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  sumber?: Prisma.StringNullableFilter<"KursMataUang"> | string | null
  dicatatOleh?: Prisma.StringNullableFilter<"KursMataUang"> | string | null
  dibuatPada?: Prisma.DateTimeFilter<"KursMataUang"> | Date | string
  mataUang?: Prisma.XOR<Prisma.MataUangScalarRelationFilter, Prisma.MataUangWhereInput>
}, "id" | "mataUangId_tanggal">

export type KursMataUangOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  mataUangId?: Prisma.SortOrder
  tanggal?: Prisma.SortOrder
  kurs?: Prisma.SortOrder
  sumber?: Prisma.SortOrderInput | Prisma.SortOrder
  dicatatOleh?: Prisma.SortOrderInput | Prisma.SortOrder
  dibuatPada?: Prisma.SortOrder
  _count?: Prisma.KursMataUangCountOrderByAggregateInput
  _avg?: Prisma.KursMataUangAvgOrderByAggregateInput
  _max?: Prisma.KursMataUangMaxOrderByAggregateInput
  _min?: Prisma.KursMataUangMinOrderByAggregateInput
  _sum?: Prisma.KursMataUangSumOrderByAggregateInput
}

export type KursMataUangScalarWhereWithAggregatesInput = {
  AND?: Prisma.KursMataUangScalarWhereWithAggregatesInput | Prisma.KursMataUangScalarWhereWithAggregatesInput[]
  OR?: Prisma.KursMataUangScalarWhereWithAggregatesInput[]
  NOT?: Prisma.KursMataUangScalarWhereWithAggregatesInput | Prisma.KursMataUangScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"KursMataUang"> | string
  mataUangId?: Prisma.StringWithAggregatesFilter<"KursMataUang"> | string
  tanggal?: Prisma.DateTimeWithAggregatesFilter<"KursMataUang"> | Date | string
  kurs?: Prisma.DecimalWithAggregatesFilter<"KursMataUang"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  sumber?: Prisma.StringNullableWithAggregatesFilter<"KursMataUang"> | string | null
  dicatatOleh?: Prisma.StringNullableWithAggregatesFilter<"KursMataUang"> | string | null
  dibuatPada?: Prisma.DateTimeWithAggregatesFilter<"KursMataUang"> | Date | string
}

export type KursMataUangCreateInput = {
  id?: string
  tanggal: Date | string
  kurs: runtime.Decimal | runtime.DecimalJsLike | number | string
  sumber?: string | null
  dicatatOleh?: string | null
  dibuatPada?: Date | string
  mataUang: Prisma.MataUangCreateNestedOneWithoutKursInput
}

export type KursMataUangUncheckedCreateInput = {
  id?: string
  mataUangId: string
  tanggal: Date | string
  kurs: runtime.Decimal | runtime.DecimalJsLike | number | string
  sumber?: string | null
  dicatatOleh?: string | null
  dibuatPada?: Date | string
}

export type KursMataUangUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tanggal?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  kurs?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  sumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dicatatOleh?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dibuatPada?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mataUang?: Prisma.MataUangUpdateOneRequiredWithoutKursNestedInput
}

export type KursMataUangUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mataUangId?: Prisma.StringFieldUpdateOperationsInput | string
  tanggal?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  kurs?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  sumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dicatatOleh?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dibuatPada?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KursMataUangCreateManyInput = {
  id?: string
  mataUangId: string
  tanggal: Date | string
  kurs: runtime.Decimal | runtime.DecimalJsLike | number | string
  sumber?: string | null
  dicatatOleh?: string | null
  dibuatPada?: Date | string
}

export type KursMataUangUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tanggal?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  kurs?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  sumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dicatatOleh?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dibuatPada?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KursMataUangUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mataUangId?: Prisma.StringFieldUpdateOperationsInput | string
  tanggal?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  kurs?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  sumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dicatatOleh?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dibuatPada?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KursMataUangListRelationFilter = {
  every?: Prisma.KursMataUangWhereInput
  some?: Prisma.KursMataUangWhereInput
  none?: Prisma.KursMataUangWhereInput
}

export type KursMataUangOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type KursMataUangMataUangIdTanggalCompoundUniqueInput = {
  mataUangId: string
  tanggal: Date | string
}

export type KursMataUangCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  mataUangId?: Prisma.SortOrder
  tanggal?: Prisma.SortOrder
  kurs?: Prisma.SortOrder
  sumber?: Prisma.SortOrder
  dicatatOleh?: Prisma.SortOrder
  dibuatPada?: Prisma.SortOrder
}

export type KursMataUangAvgOrderByAggregateInput = {
  kurs?: Prisma.SortOrder
}

export type KursMataUangMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  mataUangId?: Prisma.SortOrder
  tanggal?: Prisma.SortOrder
  kurs?: Prisma.SortOrder
  sumber?: Prisma.SortOrder
  dicatatOleh?: Prisma.SortOrder
  dibuatPada?: Prisma.SortOrder
}

export type KursMataUangMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  mataUangId?: Prisma.SortOrder
  tanggal?: Prisma.SortOrder
  kurs?: Prisma.SortOrder
  sumber?: Prisma.SortOrder
  dicatatOleh?: Prisma.SortOrder
  dibuatPada?: Prisma.SortOrder
}

export type KursMataUangSumOrderByAggregateInput = {
  kurs?: Prisma.SortOrder
}

export type KursMataUangCreateNestedManyWithoutMataUangInput = {
  create?: Prisma.XOR<Prisma.KursMataUangCreateWithoutMataUangInput, Prisma.KursMataUangUncheckedCreateWithoutMataUangInput> | Prisma.KursMataUangCreateWithoutMataUangInput[] | Prisma.KursMataUangUncheckedCreateWithoutMataUangInput[]
  connectOrCreate?: Prisma.KursMataUangCreateOrConnectWithoutMataUangInput | Prisma.KursMataUangCreateOrConnectWithoutMataUangInput[]
  createMany?: Prisma.KursMataUangCreateManyMataUangInputEnvelope
  connect?: Prisma.KursMataUangWhereUniqueInput | Prisma.KursMataUangWhereUniqueInput[]
}

export type KursMataUangUncheckedCreateNestedManyWithoutMataUangInput = {
  create?: Prisma.XOR<Prisma.KursMataUangCreateWithoutMataUangInput, Prisma.KursMataUangUncheckedCreateWithoutMataUangInput> | Prisma.KursMataUangCreateWithoutMataUangInput[] | Prisma.KursMataUangUncheckedCreateWithoutMataUangInput[]
  connectOrCreate?: Prisma.KursMataUangCreateOrConnectWithoutMataUangInput | Prisma.KursMataUangCreateOrConnectWithoutMataUangInput[]
  createMany?: Prisma.KursMataUangCreateManyMataUangInputEnvelope
  connect?: Prisma.KursMataUangWhereUniqueInput | Prisma.KursMataUangWhereUniqueInput[]
}

export type KursMataUangUpdateManyWithoutMataUangNestedInput = {
  create?: Prisma.XOR<Prisma.KursMataUangCreateWithoutMataUangInput, Prisma.KursMataUangUncheckedCreateWithoutMataUangInput> | Prisma.KursMataUangCreateWithoutMataUangInput[] | Prisma.KursMataUangUncheckedCreateWithoutMataUangInput[]
  connectOrCreate?: Prisma.KursMataUangCreateOrConnectWithoutMataUangInput | Prisma.KursMataUangCreateOrConnectWithoutMataUangInput[]
  upsert?: Prisma.KursMataUangUpsertWithWhereUniqueWithoutMataUangInput | Prisma.KursMataUangUpsertWithWhereUniqueWithoutMataUangInput[]
  createMany?: Prisma.KursMataUangCreateManyMataUangInputEnvelope
  set?: Prisma.KursMataUangWhereUniqueInput | Prisma.KursMataUangWhereUniqueInput[]
  disconnect?: Prisma.KursMataUangWhereUniqueInput | Prisma.KursMataUangWhereUniqueInput[]
  delete?: Prisma.KursMataUangWhereUniqueInput | Prisma.KursMataUangWhereUniqueInput[]
  connect?: Prisma.KursMataUangWhereUniqueInput | Prisma.KursMataUangWhereUniqueInput[]
  update?: Prisma.KursMataUangUpdateWithWhereUniqueWithoutMataUangInput | Prisma.KursMataUangUpdateWithWhereUniqueWithoutMataUangInput[]
  updateMany?: Prisma.KursMataUangUpdateManyWithWhereWithoutMataUangInput | Prisma.KursMataUangUpdateManyWithWhereWithoutMataUangInput[]
  deleteMany?: Prisma.KursMataUangScalarWhereInput | Prisma.KursMataUangScalarWhereInput[]
}

export type KursMataUangUncheckedUpdateManyWithoutMataUangNestedInput = {
  create?: Prisma.XOR<Prisma.KursMataUangCreateWithoutMataUangInput, Prisma.KursMataUangUncheckedCreateWithoutMataUangInput> | Prisma.KursMataUangCreateWithoutMataUangInput[] | Prisma.KursMataUangUncheckedCreateWithoutMataUangInput[]
  connectOrCreate?: Prisma.KursMataUangCreateOrConnectWithoutMataUangInput | Prisma.KursMataUangCreateOrConnectWithoutMataUangInput[]
  upsert?: Prisma.KursMataUangUpsertWithWhereUniqueWithoutMataUangInput | Prisma.KursMataUangUpsertWithWhereUniqueWithoutMataUangInput[]
  createMany?: Prisma.KursMataUangCreateManyMataUangInputEnvelope
  set?: Prisma.KursMataUangWhereUniqueInput | Prisma.KursMataUangWhereUniqueInput[]
  disconnect?: Prisma.KursMataUangWhereUniqueInput | Prisma.KursMataUangWhereUniqueInput[]
  delete?: Prisma.KursMataUangWhereUniqueInput | Prisma.KursMataUangWhereUniqueInput[]
  connect?: Prisma.KursMataUangWhereUniqueInput | Prisma.KursMataUangWhereUniqueInput[]
  update?: Prisma.KursMataUangUpdateWithWhereUniqueWithoutMataUangInput | Prisma.KursMataUangUpdateWithWhereUniqueWithoutMataUangInput[]
  updateMany?: Prisma.KursMataUangUpdateManyWithWhereWithoutMataUangInput | Prisma.KursMataUangUpdateManyWithWhereWithoutMataUangInput[]
  deleteMany?: Prisma.KursMataUangScalarWhereInput | Prisma.KursMataUangScalarWhereInput[]
}

export type DecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type KursMataUangCreateWithoutMataUangInput = {
  id?: string
  tanggal: Date | string
  kurs: runtime.Decimal | runtime.DecimalJsLike | number | string
  sumber?: string | null
  dicatatOleh?: string | null
  dibuatPada?: Date | string
}

export type KursMataUangUncheckedCreateWithoutMataUangInput = {
  id?: string
  tanggal: Date | string
  kurs: runtime.Decimal | runtime.DecimalJsLike | number | string
  sumber?: string | null
  dicatatOleh?: string | null
  dibuatPada?: Date | string
}

export type KursMataUangCreateOrConnectWithoutMataUangInput = {
  where: Prisma.KursMataUangWhereUniqueInput
  create: Prisma.XOR<Prisma.KursMataUangCreateWithoutMataUangInput, Prisma.KursMataUangUncheckedCreateWithoutMataUangInput>
}

export type KursMataUangCreateManyMataUangInputEnvelope = {
  data: Prisma.KursMataUangCreateManyMataUangInput | Prisma.KursMataUangCreateManyMataUangInput[]
  skipDuplicates?: boolean
}

export type KursMataUangUpsertWithWhereUniqueWithoutMataUangInput = {
  where: Prisma.KursMataUangWhereUniqueInput
  update: Prisma.XOR<Prisma.KursMataUangUpdateWithoutMataUangInput, Prisma.KursMataUangUncheckedUpdateWithoutMataUangInput>
  create: Prisma.XOR<Prisma.KursMataUangCreateWithoutMataUangInput, Prisma.KursMataUangUncheckedCreateWithoutMataUangInput>
}

export type KursMataUangUpdateWithWhereUniqueWithoutMataUangInput = {
  where: Prisma.KursMataUangWhereUniqueInput
  data: Prisma.XOR<Prisma.KursMataUangUpdateWithoutMataUangInput, Prisma.KursMataUangUncheckedUpdateWithoutMataUangInput>
}

export type KursMataUangUpdateManyWithWhereWithoutMataUangInput = {
  where: Prisma.KursMataUangScalarWhereInput
  data: Prisma.XOR<Prisma.KursMataUangUpdateManyMutationInput, Prisma.KursMataUangUncheckedUpdateManyWithoutMataUangInput>
}

export type KursMataUangScalarWhereInput = {
  AND?: Prisma.KursMataUangScalarWhereInput | Prisma.KursMataUangScalarWhereInput[]
  OR?: Prisma.KursMataUangScalarWhereInput[]
  NOT?: Prisma.KursMataUangScalarWhereInput | Prisma.KursMataUangScalarWhereInput[]
  id?: Prisma.StringFilter<"KursMataUang"> | string
  mataUangId?: Prisma.StringFilter<"KursMataUang"> | string
  tanggal?: Prisma.DateTimeFilter<"KursMataUang"> | Date | string
  kurs?: Prisma.DecimalFilter<"KursMataUang"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  sumber?: Prisma.StringNullableFilter<"KursMataUang"> | string | null
  dicatatOleh?: Prisma.StringNullableFilter<"KursMataUang"> | string | null
  dibuatPada?: Prisma.DateTimeFilter<"KursMataUang"> | Date | string
}

export type KursMataUangCreateManyMataUangInput = {
  id?: string
  tanggal: Date | string
  kurs: runtime.Decimal | runtime.DecimalJsLike | number | string
  sumber?: string | null
  dicatatOleh?: string | null
  dibuatPada?: Date | string
}

export type KursMataUangUpdateWithoutMataUangInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tanggal?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  kurs?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  sumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dicatatOleh?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dibuatPada?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KursMataUangUncheckedUpdateWithoutMataUangInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tanggal?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  kurs?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  sumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dicatatOleh?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dibuatPada?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KursMataUangUncheckedUpdateManyWithoutMataUangInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tanggal?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  kurs?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  sumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dicatatOleh?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dibuatPada?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type KursMataUangSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  mataUangId?: boolean
  tanggal?: boolean
  kurs?: boolean
  sumber?: boolean
  dicatatOleh?: boolean
  dibuatPada?: boolean
  mataUang?: boolean | Prisma.MataUangDefaultArgs<ExtArgs>
}, ExtArgs["result"]["kursMataUang"]>

export type KursMataUangSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  mataUangId?: boolean
  tanggal?: boolean
  kurs?: boolean
  sumber?: boolean
  dicatatOleh?: boolean
  dibuatPada?: boolean
  mataUang?: boolean | Prisma.MataUangDefaultArgs<ExtArgs>
}, ExtArgs["result"]["kursMataUang"]>

export type KursMataUangSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  mataUangId?: boolean
  tanggal?: boolean
  kurs?: boolean
  sumber?: boolean
  dicatatOleh?: boolean
  dibuatPada?: boolean
  mataUang?: boolean | Prisma.MataUangDefaultArgs<ExtArgs>
}, ExtArgs["result"]["kursMataUang"]>

export type KursMataUangSelectScalar = {
  id?: boolean
  mataUangId?: boolean
  tanggal?: boolean
  kurs?: boolean
  sumber?: boolean
  dicatatOleh?: boolean
  dibuatPada?: boolean
}

export type KursMataUangOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "mataUangId" | "tanggal" | "kurs" | "sumber" | "dicatatOleh" | "dibuatPada", ExtArgs["result"]["kursMataUang"]>
export type KursMataUangInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  mataUang?: boolean | Prisma.MataUangDefaultArgs<ExtArgs>
}
export type KursMataUangIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  mataUang?: boolean | Prisma.MataUangDefaultArgs<ExtArgs>
}
export type KursMataUangIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  mataUang?: boolean | Prisma.MataUangDefaultArgs<ExtArgs>
}

export type $KursMataUangPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "KursMataUang"
  objects: {
    mataUang: Prisma.$MataUangPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    mataUangId: string
    tanggal: Date
    kurs: runtime.Decimal
    sumber: string | null
    dicatatOleh: string | null
    dibuatPada: Date
  }, ExtArgs["result"]["kursMataUang"]>
  composites: {}
}

export type KursMataUangGetPayload<S extends boolean | null | undefined | KursMataUangDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$KursMataUangPayload, S>

export type KursMataUangCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<KursMataUangFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: KursMataUangCountAggregateInputType | true
  }

export interface KursMataUangDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['KursMataUang'], meta: { name: 'KursMataUang' } }
  /**
   * Find zero or one KursMataUang that matches the filter.
   * @param {KursMataUangFindUniqueArgs} args - Arguments to find a KursMataUang
   * @example
   * // Get one KursMataUang
   * const kursMataUang = await prisma.kursMataUang.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends KursMataUangFindUniqueArgs>(args: Prisma.SelectSubset<T, KursMataUangFindUniqueArgs<ExtArgs>>): Prisma.Prisma__KursMataUangClient<runtime.Types.Result.GetResult<Prisma.$KursMataUangPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one KursMataUang that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {KursMataUangFindUniqueOrThrowArgs} args - Arguments to find a KursMataUang
   * @example
   * // Get one KursMataUang
   * const kursMataUang = await prisma.kursMataUang.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends KursMataUangFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, KursMataUangFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__KursMataUangClient<runtime.Types.Result.GetResult<Prisma.$KursMataUangPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first KursMataUang that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KursMataUangFindFirstArgs} args - Arguments to find a KursMataUang
   * @example
   * // Get one KursMataUang
   * const kursMataUang = await prisma.kursMataUang.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends KursMataUangFindFirstArgs>(args?: Prisma.SelectSubset<T, KursMataUangFindFirstArgs<ExtArgs>>): Prisma.Prisma__KursMataUangClient<runtime.Types.Result.GetResult<Prisma.$KursMataUangPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first KursMataUang that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KursMataUangFindFirstOrThrowArgs} args - Arguments to find a KursMataUang
   * @example
   * // Get one KursMataUang
   * const kursMataUang = await prisma.kursMataUang.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends KursMataUangFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, KursMataUangFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__KursMataUangClient<runtime.Types.Result.GetResult<Prisma.$KursMataUangPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more KursMataUangs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KursMataUangFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all KursMataUangs
   * const kursMataUangs = await prisma.kursMataUang.findMany()
   * 
   * // Get first 10 KursMataUangs
   * const kursMataUangs = await prisma.kursMataUang.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const kursMataUangWithIdOnly = await prisma.kursMataUang.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends KursMataUangFindManyArgs>(args?: Prisma.SelectSubset<T, KursMataUangFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KursMataUangPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a KursMataUang.
   * @param {KursMataUangCreateArgs} args - Arguments to create a KursMataUang.
   * @example
   * // Create one KursMataUang
   * const KursMataUang = await prisma.kursMataUang.create({
   *   data: {
   *     // ... data to create a KursMataUang
   *   }
   * })
   * 
   */
  create<T extends KursMataUangCreateArgs>(args: Prisma.SelectSubset<T, KursMataUangCreateArgs<ExtArgs>>): Prisma.Prisma__KursMataUangClient<runtime.Types.Result.GetResult<Prisma.$KursMataUangPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many KursMataUangs.
   * @param {KursMataUangCreateManyArgs} args - Arguments to create many KursMataUangs.
   * @example
   * // Create many KursMataUangs
   * const kursMataUang = await prisma.kursMataUang.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends KursMataUangCreateManyArgs>(args?: Prisma.SelectSubset<T, KursMataUangCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many KursMataUangs and returns the data saved in the database.
   * @param {KursMataUangCreateManyAndReturnArgs} args - Arguments to create many KursMataUangs.
   * @example
   * // Create many KursMataUangs
   * const kursMataUang = await prisma.kursMataUang.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many KursMataUangs and only return the `id`
   * const kursMataUangWithIdOnly = await prisma.kursMataUang.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends KursMataUangCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, KursMataUangCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KursMataUangPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a KursMataUang.
   * @param {KursMataUangDeleteArgs} args - Arguments to delete one KursMataUang.
   * @example
   * // Delete one KursMataUang
   * const KursMataUang = await prisma.kursMataUang.delete({
   *   where: {
   *     // ... filter to delete one KursMataUang
   *   }
   * })
   * 
   */
  delete<T extends KursMataUangDeleteArgs>(args: Prisma.SelectSubset<T, KursMataUangDeleteArgs<ExtArgs>>): Prisma.Prisma__KursMataUangClient<runtime.Types.Result.GetResult<Prisma.$KursMataUangPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one KursMataUang.
   * @param {KursMataUangUpdateArgs} args - Arguments to update one KursMataUang.
   * @example
   * // Update one KursMataUang
   * const kursMataUang = await prisma.kursMataUang.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends KursMataUangUpdateArgs>(args: Prisma.SelectSubset<T, KursMataUangUpdateArgs<ExtArgs>>): Prisma.Prisma__KursMataUangClient<runtime.Types.Result.GetResult<Prisma.$KursMataUangPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more KursMataUangs.
   * @param {KursMataUangDeleteManyArgs} args - Arguments to filter KursMataUangs to delete.
   * @example
   * // Delete a few KursMataUangs
   * const { count } = await prisma.kursMataUang.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends KursMataUangDeleteManyArgs>(args?: Prisma.SelectSubset<T, KursMataUangDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more KursMataUangs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KursMataUangUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many KursMataUangs
   * const kursMataUang = await prisma.kursMataUang.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends KursMataUangUpdateManyArgs>(args: Prisma.SelectSubset<T, KursMataUangUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more KursMataUangs and returns the data updated in the database.
   * @param {KursMataUangUpdateManyAndReturnArgs} args - Arguments to update many KursMataUangs.
   * @example
   * // Update many KursMataUangs
   * const kursMataUang = await prisma.kursMataUang.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more KursMataUangs and only return the `id`
   * const kursMataUangWithIdOnly = await prisma.kursMataUang.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends KursMataUangUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, KursMataUangUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KursMataUangPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one KursMataUang.
   * @param {KursMataUangUpsertArgs} args - Arguments to update or create a KursMataUang.
   * @example
   * // Update or create a KursMataUang
   * const kursMataUang = await prisma.kursMataUang.upsert({
   *   create: {
   *     // ... data to create a KursMataUang
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the KursMataUang we want to update
   *   }
   * })
   */
  upsert<T extends KursMataUangUpsertArgs>(args: Prisma.SelectSubset<T, KursMataUangUpsertArgs<ExtArgs>>): Prisma.Prisma__KursMataUangClient<runtime.Types.Result.GetResult<Prisma.$KursMataUangPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of KursMataUangs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KursMataUangCountArgs} args - Arguments to filter KursMataUangs to count.
   * @example
   * // Count the number of KursMataUangs
   * const count = await prisma.kursMataUang.count({
   *   where: {
   *     // ... the filter for the KursMataUangs we want to count
   *   }
   * })
  **/
  count<T extends KursMataUangCountArgs>(
    args?: Prisma.Subset<T, KursMataUangCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], KursMataUangCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a KursMataUang.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KursMataUangAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends KursMataUangAggregateArgs>(args: Prisma.Subset<T, KursMataUangAggregateArgs>): Prisma.PrismaPromise<GetKursMataUangAggregateType<T>>

  /**
   * Group by KursMataUang.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KursMataUangGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends KursMataUangGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: KursMataUangGroupByArgs['orderBy'] }
      : { orderBy?: KursMataUangGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, KursMataUangGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetKursMataUangGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the KursMataUang model
 */
readonly fields: KursMataUangFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for KursMataUang.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__KursMataUangClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  mataUang<T extends Prisma.MataUangDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MataUangDefaultArgs<ExtArgs>>): Prisma.Prisma__MataUangClient<runtime.Types.Result.GetResult<Prisma.$MataUangPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the KursMataUang model
 */
export interface KursMataUangFieldRefs {
  readonly id: Prisma.FieldRef<"KursMataUang", 'String'>
  readonly mataUangId: Prisma.FieldRef<"KursMataUang", 'String'>
  readonly tanggal: Prisma.FieldRef<"KursMataUang", 'DateTime'>
  readonly kurs: Prisma.FieldRef<"KursMataUang", 'Decimal'>
  readonly sumber: Prisma.FieldRef<"KursMataUang", 'String'>
  readonly dicatatOleh: Prisma.FieldRef<"KursMataUang", 'String'>
  readonly dibuatPada: Prisma.FieldRef<"KursMataUang", 'DateTime'>
}
    

// Custom InputTypes
/**
 * KursMataUang findUnique
 */
export type KursMataUangFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KursMataUang
   */
  select?: Prisma.KursMataUangSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KursMataUang
   */
  omit?: Prisma.KursMataUangOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KursMataUangInclude<ExtArgs> | null
  /**
   * Filter, which KursMataUang to fetch.
   */
  where: Prisma.KursMataUangWhereUniqueInput
}

/**
 * KursMataUang findUniqueOrThrow
 */
export type KursMataUangFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KursMataUang
   */
  select?: Prisma.KursMataUangSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KursMataUang
   */
  omit?: Prisma.KursMataUangOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KursMataUangInclude<ExtArgs> | null
  /**
   * Filter, which KursMataUang to fetch.
   */
  where: Prisma.KursMataUangWhereUniqueInput
}

/**
 * KursMataUang findFirst
 */
export type KursMataUangFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KursMataUang
   */
  select?: Prisma.KursMataUangSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KursMataUang
   */
  omit?: Prisma.KursMataUangOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KursMataUangInclude<ExtArgs> | null
  /**
   * Filter, which KursMataUang to fetch.
   */
  where?: Prisma.KursMataUangWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KursMataUangs to fetch.
   */
  orderBy?: Prisma.KursMataUangOrderByWithRelationInput | Prisma.KursMataUangOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for KursMataUangs.
   */
  cursor?: Prisma.KursMataUangWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KursMataUangs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KursMataUangs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of KursMataUangs.
   */
  distinct?: Prisma.KursMataUangScalarFieldEnum | Prisma.KursMataUangScalarFieldEnum[]
}

/**
 * KursMataUang findFirstOrThrow
 */
export type KursMataUangFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KursMataUang
   */
  select?: Prisma.KursMataUangSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KursMataUang
   */
  omit?: Prisma.KursMataUangOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KursMataUangInclude<ExtArgs> | null
  /**
   * Filter, which KursMataUang to fetch.
   */
  where?: Prisma.KursMataUangWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KursMataUangs to fetch.
   */
  orderBy?: Prisma.KursMataUangOrderByWithRelationInput | Prisma.KursMataUangOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for KursMataUangs.
   */
  cursor?: Prisma.KursMataUangWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KursMataUangs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KursMataUangs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of KursMataUangs.
   */
  distinct?: Prisma.KursMataUangScalarFieldEnum | Prisma.KursMataUangScalarFieldEnum[]
}

/**
 * KursMataUang findMany
 */
export type KursMataUangFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KursMataUang
   */
  select?: Prisma.KursMataUangSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KursMataUang
   */
  omit?: Prisma.KursMataUangOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KursMataUangInclude<ExtArgs> | null
  /**
   * Filter, which KursMataUangs to fetch.
   */
  where?: Prisma.KursMataUangWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KursMataUangs to fetch.
   */
  orderBy?: Prisma.KursMataUangOrderByWithRelationInput | Prisma.KursMataUangOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing KursMataUangs.
   */
  cursor?: Prisma.KursMataUangWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KursMataUangs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KursMataUangs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of KursMataUangs.
   */
  distinct?: Prisma.KursMataUangScalarFieldEnum | Prisma.KursMataUangScalarFieldEnum[]
}

/**
 * KursMataUang create
 */
export type KursMataUangCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KursMataUang
   */
  select?: Prisma.KursMataUangSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KursMataUang
   */
  omit?: Prisma.KursMataUangOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KursMataUangInclude<ExtArgs> | null
  /**
   * The data needed to create a KursMataUang.
   */
  data: Prisma.XOR<Prisma.KursMataUangCreateInput, Prisma.KursMataUangUncheckedCreateInput>
}

/**
 * KursMataUang createMany
 */
export type KursMataUangCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many KursMataUangs.
   */
  data: Prisma.KursMataUangCreateManyInput | Prisma.KursMataUangCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * KursMataUang createManyAndReturn
 */
export type KursMataUangCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KursMataUang
   */
  select?: Prisma.KursMataUangSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the KursMataUang
   */
  omit?: Prisma.KursMataUangOmit<ExtArgs> | null
  /**
   * The data used to create many KursMataUangs.
   */
  data: Prisma.KursMataUangCreateManyInput | Prisma.KursMataUangCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KursMataUangIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * KursMataUang update
 */
export type KursMataUangUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KursMataUang
   */
  select?: Prisma.KursMataUangSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KursMataUang
   */
  omit?: Prisma.KursMataUangOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KursMataUangInclude<ExtArgs> | null
  /**
   * The data needed to update a KursMataUang.
   */
  data: Prisma.XOR<Prisma.KursMataUangUpdateInput, Prisma.KursMataUangUncheckedUpdateInput>
  /**
   * Choose, which KursMataUang to update.
   */
  where: Prisma.KursMataUangWhereUniqueInput
}

/**
 * KursMataUang updateMany
 */
export type KursMataUangUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update KursMataUangs.
   */
  data: Prisma.XOR<Prisma.KursMataUangUpdateManyMutationInput, Prisma.KursMataUangUncheckedUpdateManyInput>
  /**
   * Filter which KursMataUangs to update
   */
  where?: Prisma.KursMataUangWhereInput
  /**
   * Limit how many KursMataUangs to update.
   */
  limit?: number
}

/**
 * KursMataUang updateManyAndReturn
 */
export type KursMataUangUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KursMataUang
   */
  select?: Prisma.KursMataUangSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the KursMataUang
   */
  omit?: Prisma.KursMataUangOmit<ExtArgs> | null
  /**
   * The data used to update KursMataUangs.
   */
  data: Prisma.XOR<Prisma.KursMataUangUpdateManyMutationInput, Prisma.KursMataUangUncheckedUpdateManyInput>
  /**
   * Filter which KursMataUangs to update
   */
  where?: Prisma.KursMataUangWhereInput
  /**
   * Limit how many KursMataUangs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KursMataUangIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * KursMataUang upsert
 */
export type KursMataUangUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KursMataUang
   */
  select?: Prisma.KursMataUangSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KursMataUang
   */
  omit?: Prisma.KursMataUangOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KursMataUangInclude<ExtArgs> | null
  /**
   * The filter to search for the KursMataUang to update in case it exists.
   */
  where: Prisma.KursMataUangWhereUniqueInput
  /**
   * In case the KursMataUang found by the `where` argument doesn't exist, create a new KursMataUang with this data.
   */
  create: Prisma.XOR<Prisma.KursMataUangCreateInput, Prisma.KursMataUangUncheckedCreateInput>
  /**
   * In case the KursMataUang was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.KursMataUangUpdateInput, Prisma.KursMataUangUncheckedUpdateInput>
}

/**
 * KursMataUang delete
 */
export type KursMataUangDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KursMataUang
   */
  select?: Prisma.KursMataUangSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KursMataUang
   */
  omit?: Prisma.KursMataUangOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KursMataUangInclude<ExtArgs> | null
  /**
   * Filter which KursMataUang to delete.
   */
  where: Prisma.KursMataUangWhereUniqueInput
}

/**
 * KursMataUang deleteMany
 */
export type KursMataUangDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which KursMataUangs to delete
   */
  where?: Prisma.KursMataUangWhereInput
  /**
   * Limit how many KursMataUangs to delete.
   */
  limit?: number
}

/**
 * KursMataUang without action
 */
export type KursMataUangDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KursMataUang
   */
  select?: Prisma.KursMataUangSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KursMataUang
   */
  omit?: Prisma.KursMataUangOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KursMataUangInclude<ExtArgs> | null
}
