
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PemetaanAkun` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PemetaanAkun
 * 
 */
export type PemetaanAkunModel = runtime.Types.Result.DefaultSelection<Prisma.$PemetaanAkunPayload>

export type AggregatePemetaanAkun = {
  _count: PemetaanAkunCountAggregateOutputType | null
  _min: PemetaanAkunMinAggregateOutputType | null
  _max: PemetaanAkunMaxAggregateOutputType | null
}

export type PemetaanAkunMinAggregateOutputType = {
  id: string | null
  piutangUsahaId: string | null
  persediaanId: string | null
  hppId: string | null
  pendapatanPenjualanId: string | null
  utangUsahaId: string | null
  bebanJasaId: string | null
  barangBelumDitagihId: string | null
  selisihPersediaanId: string | null
}

export type PemetaanAkunMaxAggregateOutputType = {
  id: string | null
  piutangUsahaId: string | null
  persediaanId: string | null
  hppId: string | null
  pendapatanPenjualanId: string | null
  utangUsahaId: string | null
  bebanJasaId: string | null
  barangBelumDitagihId: string | null
  selisihPersediaanId: string | null
}

export type PemetaanAkunCountAggregateOutputType = {
  id: number
  piutangUsahaId: number
  persediaanId: number
  hppId: number
  pendapatanPenjualanId: number
  utangUsahaId: number
  bebanJasaId: number
  barangBelumDitagihId: number
  selisihPersediaanId: number
  _all: number
}


export type PemetaanAkunMinAggregateInputType = {
  id?: true
  piutangUsahaId?: true
  persediaanId?: true
  hppId?: true
  pendapatanPenjualanId?: true
  utangUsahaId?: true
  bebanJasaId?: true
  barangBelumDitagihId?: true
  selisihPersediaanId?: true
}

export type PemetaanAkunMaxAggregateInputType = {
  id?: true
  piutangUsahaId?: true
  persediaanId?: true
  hppId?: true
  pendapatanPenjualanId?: true
  utangUsahaId?: true
  bebanJasaId?: true
  barangBelumDitagihId?: true
  selisihPersediaanId?: true
}

export type PemetaanAkunCountAggregateInputType = {
  id?: true
  piutangUsahaId?: true
  persediaanId?: true
  hppId?: true
  pendapatanPenjualanId?: true
  utangUsahaId?: true
  bebanJasaId?: true
  barangBelumDitagihId?: true
  selisihPersediaanId?: true
  _all?: true
}

export type PemetaanAkunAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PemetaanAkun to aggregate.
   */
  where?: Prisma.PemetaanAkunWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PemetaanAkuns to fetch.
   */
  orderBy?: Prisma.PemetaanAkunOrderByWithRelationInput | Prisma.PemetaanAkunOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PemetaanAkunWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PemetaanAkuns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PemetaanAkuns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PemetaanAkuns
  **/
  _count?: true | PemetaanAkunCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PemetaanAkunMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PemetaanAkunMaxAggregateInputType
}

export type GetPemetaanAkunAggregateType<T extends PemetaanAkunAggregateArgs> = {
      [P in keyof T & keyof AggregatePemetaanAkun]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePemetaanAkun[P]>
    : Prisma.GetScalarType<T[P], AggregatePemetaanAkun[P]>
}




export type PemetaanAkunGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PemetaanAkunWhereInput
  orderBy?: Prisma.PemetaanAkunOrderByWithAggregationInput | Prisma.PemetaanAkunOrderByWithAggregationInput[]
  by: Prisma.PemetaanAkunScalarFieldEnum[] | Prisma.PemetaanAkunScalarFieldEnum
  having?: Prisma.PemetaanAkunScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PemetaanAkunCountAggregateInputType | true
  _min?: PemetaanAkunMinAggregateInputType
  _max?: PemetaanAkunMaxAggregateInputType
}

export type PemetaanAkunGroupByOutputType = {
  id: string
  piutangUsahaId: string
  persediaanId: string
  hppId: string
  pendapatanPenjualanId: string
  utangUsahaId: string
  bebanJasaId: string | null
  barangBelumDitagihId: string | null
  selisihPersediaanId: string | null
  _count: PemetaanAkunCountAggregateOutputType | null
  _min: PemetaanAkunMinAggregateOutputType | null
  _max: PemetaanAkunMaxAggregateOutputType | null
}

export type GetPemetaanAkunGroupByPayload<T extends PemetaanAkunGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PemetaanAkunGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PemetaanAkunGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PemetaanAkunGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PemetaanAkunGroupByOutputType[P]>
      }
    >
  >



export type PemetaanAkunWhereInput = {
  AND?: Prisma.PemetaanAkunWhereInput | Prisma.PemetaanAkunWhereInput[]
  OR?: Prisma.PemetaanAkunWhereInput[]
  NOT?: Prisma.PemetaanAkunWhereInput | Prisma.PemetaanAkunWhereInput[]
  id?: Prisma.StringFilter<"PemetaanAkun"> | string
  piutangUsahaId?: Prisma.StringFilter<"PemetaanAkun"> | string
  persediaanId?: Prisma.StringFilter<"PemetaanAkun"> | string
  hppId?: Prisma.StringFilter<"PemetaanAkun"> | string
  pendapatanPenjualanId?: Prisma.StringFilter<"PemetaanAkun"> | string
  utangUsahaId?: Prisma.StringFilter<"PemetaanAkun"> | string
  bebanJasaId?: Prisma.StringNullableFilter<"PemetaanAkun"> | string | null
  barangBelumDitagihId?: Prisma.StringNullableFilter<"PemetaanAkun"> | string | null
  selisihPersediaanId?: Prisma.StringNullableFilter<"PemetaanAkun"> | string | null
  piutangUsaha?: Prisma.XOR<Prisma.AkunScalarRelationFilter, Prisma.AkunWhereInput>
  persediaan?: Prisma.XOR<Prisma.AkunScalarRelationFilter, Prisma.AkunWhereInput>
  hpp?: Prisma.XOR<Prisma.AkunScalarRelationFilter, Prisma.AkunWhereInput>
  pendapatanPenjualan?: Prisma.XOR<Prisma.AkunScalarRelationFilter, Prisma.AkunWhereInput>
  utangUsaha?: Prisma.XOR<Prisma.AkunScalarRelationFilter, Prisma.AkunWhereInput>
  bebanJasa?: Prisma.XOR<Prisma.AkunNullableScalarRelationFilter, Prisma.AkunWhereInput> | null
  barangBelumDitagih?: Prisma.XOR<Prisma.AkunNullableScalarRelationFilter, Prisma.AkunWhereInput> | null
  selisihPersediaan?: Prisma.XOR<Prisma.AkunNullableScalarRelationFilter, Prisma.AkunWhereInput> | null
}

export type PemetaanAkunOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  piutangUsahaId?: Prisma.SortOrder
  persediaanId?: Prisma.SortOrder
  hppId?: Prisma.SortOrder
  pendapatanPenjualanId?: Prisma.SortOrder
  utangUsahaId?: Prisma.SortOrder
  bebanJasaId?: Prisma.SortOrderInput | Prisma.SortOrder
  barangBelumDitagihId?: Prisma.SortOrderInput | Prisma.SortOrder
  selisihPersediaanId?: Prisma.SortOrderInput | Prisma.SortOrder
  piutangUsaha?: Prisma.AkunOrderByWithRelationInput
  persediaan?: Prisma.AkunOrderByWithRelationInput
  hpp?: Prisma.AkunOrderByWithRelationInput
  pendapatanPenjualan?: Prisma.AkunOrderByWithRelationInput
  utangUsaha?: Prisma.AkunOrderByWithRelationInput
  bebanJasa?: Prisma.AkunOrderByWithRelationInput
  barangBelumDitagih?: Prisma.AkunOrderByWithRelationInput
  selisihPersediaan?: Prisma.AkunOrderByWithRelationInput
}

export type PemetaanAkunWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  piutangUsahaId?: string
  persediaanId?: string
  hppId?: string
  pendapatanPenjualanId?: string
  utangUsahaId?: string
  bebanJasaId?: string
  barangBelumDitagihId?: string
  selisihPersediaanId?: string
  AND?: Prisma.PemetaanAkunWhereInput | Prisma.PemetaanAkunWhereInput[]
  OR?: Prisma.PemetaanAkunWhereInput[]
  NOT?: Prisma.PemetaanAkunWhereInput | Prisma.PemetaanAkunWhereInput[]
  piutangUsaha?: Prisma.XOR<Prisma.AkunScalarRelationFilter, Prisma.AkunWhereInput>
  persediaan?: Prisma.XOR<Prisma.AkunScalarRelationFilter, Prisma.AkunWhereInput>
  hpp?: Prisma.XOR<Prisma.AkunScalarRelationFilter, Prisma.AkunWhereInput>
  pendapatanPenjualan?: Prisma.XOR<Prisma.AkunScalarRelationFilter, Prisma.AkunWhereInput>
  utangUsaha?: Prisma.XOR<Prisma.AkunScalarRelationFilter, Prisma.AkunWhereInput>
  bebanJasa?: Prisma.XOR<Prisma.AkunNullableScalarRelationFilter, Prisma.AkunWhereInput> | null
  barangBelumDitagih?: Prisma.XOR<Prisma.AkunNullableScalarRelationFilter, Prisma.AkunWhereInput> | null
  selisihPersediaan?: Prisma.XOR<Prisma.AkunNullableScalarRelationFilter, Prisma.AkunWhereInput> | null
}, "id" | "piutangUsahaId" | "persediaanId" | "hppId" | "pendapatanPenjualanId" | "utangUsahaId" | "bebanJasaId" | "barangBelumDitagihId" | "selisihPersediaanId">

export type PemetaanAkunOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  piutangUsahaId?: Prisma.SortOrder
  persediaanId?: Prisma.SortOrder
  hppId?: Prisma.SortOrder
  pendapatanPenjualanId?: Prisma.SortOrder
  utangUsahaId?: Prisma.SortOrder
  bebanJasaId?: Prisma.SortOrderInput | Prisma.SortOrder
  barangBelumDitagihId?: Prisma.SortOrderInput | Prisma.SortOrder
  selisihPersediaanId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.PemetaanAkunCountOrderByAggregateInput
  _max?: Prisma.PemetaanAkunMaxOrderByAggregateInput
  _min?: Prisma.PemetaanAkunMinOrderByAggregateInput
}

export type PemetaanAkunScalarWhereWithAggregatesInput = {
  AND?: Prisma.PemetaanAkunScalarWhereWithAggregatesInput | Prisma.PemetaanAkunScalarWhereWithAggregatesInput[]
  OR?: Prisma.PemetaanAkunScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PemetaanAkunScalarWhereWithAggregatesInput | Prisma.PemetaanAkunScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PemetaanAkun"> | string
  piutangUsahaId?: Prisma.StringWithAggregatesFilter<"PemetaanAkun"> | string
  persediaanId?: Prisma.StringWithAggregatesFilter<"PemetaanAkun"> | string
  hppId?: Prisma.StringWithAggregatesFilter<"PemetaanAkun"> | string
  pendapatanPenjualanId?: Prisma.StringWithAggregatesFilter<"PemetaanAkun"> | string
  utangUsahaId?: Prisma.StringWithAggregatesFilter<"PemetaanAkun"> | string
  bebanJasaId?: Prisma.StringNullableWithAggregatesFilter<"PemetaanAkun"> | string | null
  barangBelumDitagihId?: Prisma.StringNullableWithAggregatesFilter<"PemetaanAkun"> | string | null
  selisihPersediaanId?: Prisma.StringNullableWithAggregatesFilter<"PemetaanAkun"> | string | null
}

export type PemetaanAkunCreateInput = {
  id?: string
  piutangUsaha: Prisma.AkunCreateNestedOneWithoutPemetaanPiutangInput
  persediaan: Prisma.AkunCreateNestedOneWithoutPemetaanPersediaanInput
  hpp: Prisma.AkunCreateNestedOneWithoutPemetaanHppInput
  pendapatanPenjualan: Prisma.AkunCreateNestedOneWithoutPemetaanPendapatanInput
  utangUsaha: Prisma.AkunCreateNestedOneWithoutPemetaanUtangInput
  bebanJasa?: Prisma.AkunCreateNestedOneWithoutPemetaanBebanJasaInput
  barangBelumDitagih?: Prisma.AkunCreateNestedOneWithoutPemetaanBarangBelumDitagihInput
  selisihPersediaan?: Prisma.AkunCreateNestedOneWithoutPemetaanSelisihPersediaanInput
}

export type PemetaanAkunUncheckedCreateInput = {
  id?: string
  piutangUsahaId: string
  persediaanId: string
  hppId: string
  pendapatanPenjualanId: string
  utangUsahaId: string
  bebanJasaId?: string | null
  barangBelumDitagihId?: string | null
  selisihPersediaanId?: string | null
}

export type PemetaanAkunUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  piutangUsaha?: Prisma.AkunUpdateOneRequiredWithoutPemetaanPiutangNestedInput
  persediaan?: Prisma.AkunUpdateOneRequiredWithoutPemetaanPersediaanNestedInput
  hpp?: Prisma.AkunUpdateOneRequiredWithoutPemetaanHppNestedInput
  pendapatanPenjualan?: Prisma.AkunUpdateOneRequiredWithoutPemetaanPendapatanNestedInput
  utangUsaha?: Prisma.AkunUpdateOneRequiredWithoutPemetaanUtangNestedInput
  bebanJasa?: Prisma.AkunUpdateOneWithoutPemetaanBebanJasaNestedInput
  barangBelumDitagih?: Prisma.AkunUpdateOneWithoutPemetaanBarangBelumDitagihNestedInput
  selisihPersediaan?: Prisma.AkunUpdateOneWithoutPemetaanSelisihPersediaanNestedInput
}

export type PemetaanAkunUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  piutangUsahaId?: Prisma.StringFieldUpdateOperationsInput | string
  persediaanId?: Prisma.StringFieldUpdateOperationsInput | string
  hppId?: Prisma.StringFieldUpdateOperationsInput | string
  pendapatanPenjualanId?: Prisma.StringFieldUpdateOperationsInput | string
  utangUsahaId?: Prisma.StringFieldUpdateOperationsInput | string
  bebanJasaId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  barangBelumDitagihId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  selisihPersediaanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PemetaanAkunCreateManyInput = {
  id?: string
  piutangUsahaId: string
  persediaanId: string
  hppId: string
  pendapatanPenjualanId: string
  utangUsahaId: string
  bebanJasaId?: string | null
  barangBelumDitagihId?: string | null
  selisihPersediaanId?: string | null
}

export type PemetaanAkunUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PemetaanAkunUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  piutangUsahaId?: Prisma.StringFieldUpdateOperationsInput | string
  persediaanId?: Prisma.StringFieldUpdateOperationsInput | string
  hppId?: Prisma.StringFieldUpdateOperationsInput | string
  pendapatanPenjualanId?: Prisma.StringFieldUpdateOperationsInput | string
  utangUsahaId?: Prisma.StringFieldUpdateOperationsInput | string
  bebanJasaId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  barangBelumDitagihId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  selisihPersediaanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PemetaanAkunNullableScalarRelationFilter = {
  is?: Prisma.PemetaanAkunWhereInput | null
  isNot?: Prisma.PemetaanAkunWhereInput | null
}

export type PemetaanAkunCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  piutangUsahaId?: Prisma.SortOrder
  persediaanId?: Prisma.SortOrder
  hppId?: Prisma.SortOrder
  pendapatanPenjualanId?: Prisma.SortOrder
  utangUsahaId?: Prisma.SortOrder
  bebanJasaId?: Prisma.SortOrder
  barangBelumDitagihId?: Prisma.SortOrder
  selisihPersediaanId?: Prisma.SortOrder
}

export type PemetaanAkunMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  piutangUsahaId?: Prisma.SortOrder
  persediaanId?: Prisma.SortOrder
  hppId?: Prisma.SortOrder
  pendapatanPenjualanId?: Prisma.SortOrder
  utangUsahaId?: Prisma.SortOrder
  bebanJasaId?: Prisma.SortOrder
  barangBelumDitagihId?: Prisma.SortOrder
  selisihPersediaanId?: Prisma.SortOrder
}

export type PemetaanAkunMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  piutangUsahaId?: Prisma.SortOrder
  persediaanId?: Prisma.SortOrder
  hppId?: Prisma.SortOrder
  pendapatanPenjualanId?: Prisma.SortOrder
  utangUsahaId?: Prisma.SortOrder
  bebanJasaId?: Prisma.SortOrder
  barangBelumDitagihId?: Prisma.SortOrder
  selisihPersediaanId?: Prisma.SortOrder
}

export type PemetaanAkunCreateNestedOneWithoutPiutangUsahaInput = {
  create?: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutPiutangUsahaInput, Prisma.PemetaanAkunUncheckedCreateWithoutPiutangUsahaInput>
  connectOrCreate?: Prisma.PemetaanAkunCreateOrConnectWithoutPiutangUsahaInput
  connect?: Prisma.PemetaanAkunWhereUniqueInput
}

export type PemetaanAkunCreateNestedOneWithoutPersediaanInput = {
  create?: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutPersediaanInput, Prisma.PemetaanAkunUncheckedCreateWithoutPersediaanInput>
  connectOrCreate?: Prisma.PemetaanAkunCreateOrConnectWithoutPersediaanInput
  connect?: Prisma.PemetaanAkunWhereUniqueInput
}

export type PemetaanAkunCreateNestedOneWithoutHppInput = {
  create?: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutHppInput, Prisma.PemetaanAkunUncheckedCreateWithoutHppInput>
  connectOrCreate?: Prisma.PemetaanAkunCreateOrConnectWithoutHppInput
  connect?: Prisma.PemetaanAkunWhereUniqueInput
}

export type PemetaanAkunCreateNestedOneWithoutPendapatanPenjualanInput = {
  create?: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutPendapatanPenjualanInput, Prisma.PemetaanAkunUncheckedCreateWithoutPendapatanPenjualanInput>
  connectOrCreate?: Prisma.PemetaanAkunCreateOrConnectWithoutPendapatanPenjualanInput
  connect?: Prisma.PemetaanAkunWhereUniqueInput
}

export type PemetaanAkunCreateNestedOneWithoutUtangUsahaInput = {
  create?: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutUtangUsahaInput, Prisma.PemetaanAkunUncheckedCreateWithoutUtangUsahaInput>
  connectOrCreate?: Prisma.PemetaanAkunCreateOrConnectWithoutUtangUsahaInput
  connect?: Prisma.PemetaanAkunWhereUniqueInput
}

export type PemetaanAkunCreateNestedOneWithoutBebanJasaInput = {
  create?: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutBebanJasaInput, Prisma.PemetaanAkunUncheckedCreateWithoutBebanJasaInput>
  connectOrCreate?: Prisma.PemetaanAkunCreateOrConnectWithoutBebanJasaInput
  connect?: Prisma.PemetaanAkunWhereUniqueInput
}

export type PemetaanAkunCreateNestedOneWithoutBarangBelumDitagihInput = {
  create?: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutBarangBelumDitagihInput, Prisma.PemetaanAkunUncheckedCreateWithoutBarangBelumDitagihInput>
  connectOrCreate?: Prisma.PemetaanAkunCreateOrConnectWithoutBarangBelumDitagihInput
  connect?: Prisma.PemetaanAkunWhereUniqueInput
}

export type PemetaanAkunCreateNestedOneWithoutSelisihPersediaanInput = {
  create?: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutSelisihPersediaanInput, Prisma.PemetaanAkunUncheckedCreateWithoutSelisihPersediaanInput>
  connectOrCreate?: Prisma.PemetaanAkunCreateOrConnectWithoutSelisihPersediaanInput
  connect?: Prisma.PemetaanAkunWhereUniqueInput
}

export type PemetaanAkunUncheckedCreateNestedOneWithoutPiutangUsahaInput = {
  create?: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutPiutangUsahaInput, Prisma.PemetaanAkunUncheckedCreateWithoutPiutangUsahaInput>
  connectOrCreate?: Prisma.PemetaanAkunCreateOrConnectWithoutPiutangUsahaInput
  connect?: Prisma.PemetaanAkunWhereUniqueInput
}

export type PemetaanAkunUncheckedCreateNestedOneWithoutPersediaanInput = {
  create?: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutPersediaanInput, Prisma.PemetaanAkunUncheckedCreateWithoutPersediaanInput>
  connectOrCreate?: Prisma.PemetaanAkunCreateOrConnectWithoutPersediaanInput
  connect?: Prisma.PemetaanAkunWhereUniqueInput
}

export type PemetaanAkunUncheckedCreateNestedOneWithoutHppInput = {
  create?: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutHppInput, Prisma.PemetaanAkunUncheckedCreateWithoutHppInput>
  connectOrCreate?: Prisma.PemetaanAkunCreateOrConnectWithoutHppInput
  connect?: Prisma.PemetaanAkunWhereUniqueInput
}

export type PemetaanAkunUncheckedCreateNestedOneWithoutPendapatanPenjualanInput = {
  create?: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutPendapatanPenjualanInput, Prisma.PemetaanAkunUncheckedCreateWithoutPendapatanPenjualanInput>
  connectOrCreate?: Prisma.PemetaanAkunCreateOrConnectWithoutPendapatanPenjualanInput
  connect?: Prisma.PemetaanAkunWhereUniqueInput
}

export type PemetaanAkunUncheckedCreateNestedOneWithoutUtangUsahaInput = {
  create?: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutUtangUsahaInput, Prisma.PemetaanAkunUncheckedCreateWithoutUtangUsahaInput>
  connectOrCreate?: Prisma.PemetaanAkunCreateOrConnectWithoutUtangUsahaInput
  connect?: Prisma.PemetaanAkunWhereUniqueInput
}

export type PemetaanAkunUncheckedCreateNestedOneWithoutBebanJasaInput = {
  create?: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutBebanJasaInput, Prisma.PemetaanAkunUncheckedCreateWithoutBebanJasaInput>
  connectOrCreate?: Prisma.PemetaanAkunCreateOrConnectWithoutBebanJasaInput
  connect?: Prisma.PemetaanAkunWhereUniqueInput
}

export type PemetaanAkunUncheckedCreateNestedOneWithoutBarangBelumDitagihInput = {
  create?: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutBarangBelumDitagihInput, Prisma.PemetaanAkunUncheckedCreateWithoutBarangBelumDitagihInput>
  connectOrCreate?: Prisma.PemetaanAkunCreateOrConnectWithoutBarangBelumDitagihInput
  connect?: Prisma.PemetaanAkunWhereUniqueInput
}

export type PemetaanAkunUncheckedCreateNestedOneWithoutSelisihPersediaanInput = {
  create?: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutSelisihPersediaanInput, Prisma.PemetaanAkunUncheckedCreateWithoutSelisihPersediaanInput>
  connectOrCreate?: Prisma.PemetaanAkunCreateOrConnectWithoutSelisihPersediaanInput
  connect?: Prisma.PemetaanAkunWhereUniqueInput
}

export type PemetaanAkunUpdateOneWithoutPiutangUsahaNestedInput = {
  create?: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutPiutangUsahaInput, Prisma.PemetaanAkunUncheckedCreateWithoutPiutangUsahaInput>
  connectOrCreate?: Prisma.PemetaanAkunCreateOrConnectWithoutPiutangUsahaInput
  upsert?: Prisma.PemetaanAkunUpsertWithoutPiutangUsahaInput
  disconnect?: Prisma.PemetaanAkunWhereInput | boolean
  delete?: Prisma.PemetaanAkunWhereInput | boolean
  connect?: Prisma.PemetaanAkunWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PemetaanAkunUpdateToOneWithWhereWithoutPiutangUsahaInput, Prisma.PemetaanAkunUpdateWithoutPiutangUsahaInput>, Prisma.PemetaanAkunUncheckedUpdateWithoutPiutangUsahaInput>
}

export type PemetaanAkunUpdateOneWithoutPersediaanNestedInput = {
  create?: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutPersediaanInput, Prisma.PemetaanAkunUncheckedCreateWithoutPersediaanInput>
  connectOrCreate?: Prisma.PemetaanAkunCreateOrConnectWithoutPersediaanInput
  upsert?: Prisma.PemetaanAkunUpsertWithoutPersediaanInput
  disconnect?: Prisma.PemetaanAkunWhereInput | boolean
  delete?: Prisma.PemetaanAkunWhereInput | boolean
  connect?: Prisma.PemetaanAkunWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PemetaanAkunUpdateToOneWithWhereWithoutPersediaanInput, Prisma.PemetaanAkunUpdateWithoutPersediaanInput>, Prisma.PemetaanAkunUncheckedUpdateWithoutPersediaanInput>
}

export type PemetaanAkunUpdateOneWithoutHppNestedInput = {
  create?: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutHppInput, Prisma.PemetaanAkunUncheckedCreateWithoutHppInput>
  connectOrCreate?: Prisma.PemetaanAkunCreateOrConnectWithoutHppInput
  upsert?: Prisma.PemetaanAkunUpsertWithoutHppInput
  disconnect?: Prisma.PemetaanAkunWhereInput | boolean
  delete?: Prisma.PemetaanAkunWhereInput | boolean
  connect?: Prisma.PemetaanAkunWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PemetaanAkunUpdateToOneWithWhereWithoutHppInput, Prisma.PemetaanAkunUpdateWithoutHppInput>, Prisma.PemetaanAkunUncheckedUpdateWithoutHppInput>
}

export type PemetaanAkunUpdateOneWithoutPendapatanPenjualanNestedInput = {
  create?: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutPendapatanPenjualanInput, Prisma.PemetaanAkunUncheckedCreateWithoutPendapatanPenjualanInput>
  connectOrCreate?: Prisma.PemetaanAkunCreateOrConnectWithoutPendapatanPenjualanInput
  upsert?: Prisma.PemetaanAkunUpsertWithoutPendapatanPenjualanInput
  disconnect?: Prisma.PemetaanAkunWhereInput | boolean
  delete?: Prisma.PemetaanAkunWhereInput | boolean
  connect?: Prisma.PemetaanAkunWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PemetaanAkunUpdateToOneWithWhereWithoutPendapatanPenjualanInput, Prisma.PemetaanAkunUpdateWithoutPendapatanPenjualanInput>, Prisma.PemetaanAkunUncheckedUpdateWithoutPendapatanPenjualanInput>
}

export type PemetaanAkunUpdateOneWithoutUtangUsahaNestedInput = {
  create?: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutUtangUsahaInput, Prisma.PemetaanAkunUncheckedCreateWithoutUtangUsahaInput>
  connectOrCreate?: Prisma.PemetaanAkunCreateOrConnectWithoutUtangUsahaInput
  upsert?: Prisma.PemetaanAkunUpsertWithoutUtangUsahaInput
  disconnect?: Prisma.PemetaanAkunWhereInput | boolean
  delete?: Prisma.PemetaanAkunWhereInput | boolean
  connect?: Prisma.PemetaanAkunWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PemetaanAkunUpdateToOneWithWhereWithoutUtangUsahaInput, Prisma.PemetaanAkunUpdateWithoutUtangUsahaInput>, Prisma.PemetaanAkunUncheckedUpdateWithoutUtangUsahaInput>
}

export type PemetaanAkunUpdateOneWithoutBebanJasaNestedInput = {
  create?: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutBebanJasaInput, Prisma.PemetaanAkunUncheckedCreateWithoutBebanJasaInput>
  connectOrCreate?: Prisma.PemetaanAkunCreateOrConnectWithoutBebanJasaInput
  upsert?: Prisma.PemetaanAkunUpsertWithoutBebanJasaInput
  disconnect?: Prisma.PemetaanAkunWhereInput | boolean
  delete?: Prisma.PemetaanAkunWhereInput | boolean
  connect?: Prisma.PemetaanAkunWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PemetaanAkunUpdateToOneWithWhereWithoutBebanJasaInput, Prisma.PemetaanAkunUpdateWithoutBebanJasaInput>, Prisma.PemetaanAkunUncheckedUpdateWithoutBebanJasaInput>
}

export type PemetaanAkunUpdateOneWithoutBarangBelumDitagihNestedInput = {
  create?: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutBarangBelumDitagihInput, Prisma.PemetaanAkunUncheckedCreateWithoutBarangBelumDitagihInput>
  connectOrCreate?: Prisma.PemetaanAkunCreateOrConnectWithoutBarangBelumDitagihInput
  upsert?: Prisma.PemetaanAkunUpsertWithoutBarangBelumDitagihInput
  disconnect?: Prisma.PemetaanAkunWhereInput | boolean
  delete?: Prisma.PemetaanAkunWhereInput | boolean
  connect?: Prisma.PemetaanAkunWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PemetaanAkunUpdateToOneWithWhereWithoutBarangBelumDitagihInput, Prisma.PemetaanAkunUpdateWithoutBarangBelumDitagihInput>, Prisma.PemetaanAkunUncheckedUpdateWithoutBarangBelumDitagihInput>
}

export type PemetaanAkunUpdateOneWithoutSelisihPersediaanNestedInput = {
  create?: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutSelisihPersediaanInput, Prisma.PemetaanAkunUncheckedCreateWithoutSelisihPersediaanInput>
  connectOrCreate?: Prisma.PemetaanAkunCreateOrConnectWithoutSelisihPersediaanInput
  upsert?: Prisma.PemetaanAkunUpsertWithoutSelisihPersediaanInput
  disconnect?: Prisma.PemetaanAkunWhereInput | boolean
  delete?: Prisma.PemetaanAkunWhereInput | boolean
  connect?: Prisma.PemetaanAkunWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PemetaanAkunUpdateToOneWithWhereWithoutSelisihPersediaanInput, Prisma.PemetaanAkunUpdateWithoutSelisihPersediaanInput>, Prisma.PemetaanAkunUncheckedUpdateWithoutSelisihPersediaanInput>
}

export type PemetaanAkunUncheckedUpdateOneWithoutPiutangUsahaNestedInput = {
  create?: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutPiutangUsahaInput, Prisma.PemetaanAkunUncheckedCreateWithoutPiutangUsahaInput>
  connectOrCreate?: Prisma.PemetaanAkunCreateOrConnectWithoutPiutangUsahaInput
  upsert?: Prisma.PemetaanAkunUpsertWithoutPiutangUsahaInput
  disconnect?: Prisma.PemetaanAkunWhereInput | boolean
  delete?: Prisma.PemetaanAkunWhereInput | boolean
  connect?: Prisma.PemetaanAkunWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PemetaanAkunUpdateToOneWithWhereWithoutPiutangUsahaInput, Prisma.PemetaanAkunUpdateWithoutPiutangUsahaInput>, Prisma.PemetaanAkunUncheckedUpdateWithoutPiutangUsahaInput>
}

export type PemetaanAkunUncheckedUpdateOneWithoutPersediaanNestedInput = {
  create?: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutPersediaanInput, Prisma.PemetaanAkunUncheckedCreateWithoutPersediaanInput>
  connectOrCreate?: Prisma.PemetaanAkunCreateOrConnectWithoutPersediaanInput
  upsert?: Prisma.PemetaanAkunUpsertWithoutPersediaanInput
  disconnect?: Prisma.PemetaanAkunWhereInput | boolean
  delete?: Prisma.PemetaanAkunWhereInput | boolean
  connect?: Prisma.PemetaanAkunWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PemetaanAkunUpdateToOneWithWhereWithoutPersediaanInput, Prisma.PemetaanAkunUpdateWithoutPersediaanInput>, Prisma.PemetaanAkunUncheckedUpdateWithoutPersediaanInput>
}

export type PemetaanAkunUncheckedUpdateOneWithoutHppNestedInput = {
  create?: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutHppInput, Prisma.PemetaanAkunUncheckedCreateWithoutHppInput>
  connectOrCreate?: Prisma.PemetaanAkunCreateOrConnectWithoutHppInput
  upsert?: Prisma.PemetaanAkunUpsertWithoutHppInput
  disconnect?: Prisma.PemetaanAkunWhereInput | boolean
  delete?: Prisma.PemetaanAkunWhereInput | boolean
  connect?: Prisma.PemetaanAkunWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PemetaanAkunUpdateToOneWithWhereWithoutHppInput, Prisma.PemetaanAkunUpdateWithoutHppInput>, Prisma.PemetaanAkunUncheckedUpdateWithoutHppInput>
}

export type PemetaanAkunUncheckedUpdateOneWithoutPendapatanPenjualanNestedInput = {
  create?: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutPendapatanPenjualanInput, Prisma.PemetaanAkunUncheckedCreateWithoutPendapatanPenjualanInput>
  connectOrCreate?: Prisma.PemetaanAkunCreateOrConnectWithoutPendapatanPenjualanInput
  upsert?: Prisma.PemetaanAkunUpsertWithoutPendapatanPenjualanInput
  disconnect?: Prisma.PemetaanAkunWhereInput | boolean
  delete?: Prisma.PemetaanAkunWhereInput | boolean
  connect?: Prisma.PemetaanAkunWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PemetaanAkunUpdateToOneWithWhereWithoutPendapatanPenjualanInput, Prisma.PemetaanAkunUpdateWithoutPendapatanPenjualanInput>, Prisma.PemetaanAkunUncheckedUpdateWithoutPendapatanPenjualanInput>
}

export type PemetaanAkunUncheckedUpdateOneWithoutUtangUsahaNestedInput = {
  create?: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutUtangUsahaInput, Prisma.PemetaanAkunUncheckedCreateWithoutUtangUsahaInput>
  connectOrCreate?: Prisma.PemetaanAkunCreateOrConnectWithoutUtangUsahaInput
  upsert?: Prisma.PemetaanAkunUpsertWithoutUtangUsahaInput
  disconnect?: Prisma.PemetaanAkunWhereInput | boolean
  delete?: Prisma.PemetaanAkunWhereInput | boolean
  connect?: Prisma.PemetaanAkunWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PemetaanAkunUpdateToOneWithWhereWithoutUtangUsahaInput, Prisma.PemetaanAkunUpdateWithoutUtangUsahaInput>, Prisma.PemetaanAkunUncheckedUpdateWithoutUtangUsahaInput>
}

export type PemetaanAkunUncheckedUpdateOneWithoutBebanJasaNestedInput = {
  create?: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutBebanJasaInput, Prisma.PemetaanAkunUncheckedCreateWithoutBebanJasaInput>
  connectOrCreate?: Prisma.PemetaanAkunCreateOrConnectWithoutBebanJasaInput
  upsert?: Prisma.PemetaanAkunUpsertWithoutBebanJasaInput
  disconnect?: Prisma.PemetaanAkunWhereInput | boolean
  delete?: Prisma.PemetaanAkunWhereInput | boolean
  connect?: Prisma.PemetaanAkunWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PemetaanAkunUpdateToOneWithWhereWithoutBebanJasaInput, Prisma.PemetaanAkunUpdateWithoutBebanJasaInput>, Prisma.PemetaanAkunUncheckedUpdateWithoutBebanJasaInput>
}

export type PemetaanAkunUncheckedUpdateOneWithoutBarangBelumDitagihNestedInput = {
  create?: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutBarangBelumDitagihInput, Prisma.PemetaanAkunUncheckedCreateWithoutBarangBelumDitagihInput>
  connectOrCreate?: Prisma.PemetaanAkunCreateOrConnectWithoutBarangBelumDitagihInput
  upsert?: Prisma.PemetaanAkunUpsertWithoutBarangBelumDitagihInput
  disconnect?: Prisma.PemetaanAkunWhereInput | boolean
  delete?: Prisma.PemetaanAkunWhereInput | boolean
  connect?: Prisma.PemetaanAkunWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PemetaanAkunUpdateToOneWithWhereWithoutBarangBelumDitagihInput, Prisma.PemetaanAkunUpdateWithoutBarangBelumDitagihInput>, Prisma.PemetaanAkunUncheckedUpdateWithoutBarangBelumDitagihInput>
}

export type PemetaanAkunUncheckedUpdateOneWithoutSelisihPersediaanNestedInput = {
  create?: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutSelisihPersediaanInput, Prisma.PemetaanAkunUncheckedCreateWithoutSelisihPersediaanInput>
  connectOrCreate?: Prisma.PemetaanAkunCreateOrConnectWithoutSelisihPersediaanInput
  upsert?: Prisma.PemetaanAkunUpsertWithoutSelisihPersediaanInput
  disconnect?: Prisma.PemetaanAkunWhereInput | boolean
  delete?: Prisma.PemetaanAkunWhereInput | boolean
  connect?: Prisma.PemetaanAkunWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PemetaanAkunUpdateToOneWithWhereWithoutSelisihPersediaanInput, Prisma.PemetaanAkunUpdateWithoutSelisihPersediaanInput>, Prisma.PemetaanAkunUncheckedUpdateWithoutSelisihPersediaanInput>
}

export type PemetaanAkunCreateWithoutPiutangUsahaInput = {
  id?: string
  persediaan: Prisma.AkunCreateNestedOneWithoutPemetaanPersediaanInput
  hpp: Prisma.AkunCreateNestedOneWithoutPemetaanHppInput
  pendapatanPenjualan: Prisma.AkunCreateNestedOneWithoutPemetaanPendapatanInput
  utangUsaha: Prisma.AkunCreateNestedOneWithoutPemetaanUtangInput
  bebanJasa?: Prisma.AkunCreateNestedOneWithoutPemetaanBebanJasaInput
  barangBelumDitagih?: Prisma.AkunCreateNestedOneWithoutPemetaanBarangBelumDitagihInput
  selisihPersediaan?: Prisma.AkunCreateNestedOneWithoutPemetaanSelisihPersediaanInput
}

export type PemetaanAkunUncheckedCreateWithoutPiutangUsahaInput = {
  id?: string
  persediaanId: string
  hppId: string
  pendapatanPenjualanId: string
  utangUsahaId: string
  bebanJasaId?: string | null
  barangBelumDitagihId?: string | null
  selisihPersediaanId?: string | null
}

export type PemetaanAkunCreateOrConnectWithoutPiutangUsahaInput = {
  where: Prisma.PemetaanAkunWhereUniqueInput
  create: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutPiutangUsahaInput, Prisma.PemetaanAkunUncheckedCreateWithoutPiutangUsahaInput>
}

export type PemetaanAkunCreateWithoutPersediaanInput = {
  id?: string
  piutangUsaha: Prisma.AkunCreateNestedOneWithoutPemetaanPiutangInput
  hpp: Prisma.AkunCreateNestedOneWithoutPemetaanHppInput
  pendapatanPenjualan: Prisma.AkunCreateNestedOneWithoutPemetaanPendapatanInput
  utangUsaha: Prisma.AkunCreateNestedOneWithoutPemetaanUtangInput
  bebanJasa?: Prisma.AkunCreateNestedOneWithoutPemetaanBebanJasaInput
  barangBelumDitagih?: Prisma.AkunCreateNestedOneWithoutPemetaanBarangBelumDitagihInput
  selisihPersediaan?: Prisma.AkunCreateNestedOneWithoutPemetaanSelisihPersediaanInput
}

export type PemetaanAkunUncheckedCreateWithoutPersediaanInput = {
  id?: string
  piutangUsahaId: string
  hppId: string
  pendapatanPenjualanId: string
  utangUsahaId: string
  bebanJasaId?: string | null
  barangBelumDitagihId?: string | null
  selisihPersediaanId?: string | null
}

export type PemetaanAkunCreateOrConnectWithoutPersediaanInput = {
  where: Prisma.PemetaanAkunWhereUniqueInput
  create: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutPersediaanInput, Prisma.PemetaanAkunUncheckedCreateWithoutPersediaanInput>
}

export type PemetaanAkunCreateWithoutHppInput = {
  id?: string
  piutangUsaha: Prisma.AkunCreateNestedOneWithoutPemetaanPiutangInput
  persediaan: Prisma.AkunCreateNestedOneWithoutPemetaanPersediaanInput
  pendapatanPenjualan: Prisma.AkunCreateNestedOneWithoutPemetaanPendapatanInput
  utangUsaha: Prisma.AkunCreateNestedOneWithoutPemetaanUtangInput
  bebanJasa?: Prisma.AkunCreateNestedOneWithoutPemetaanBebanJasaInput
  barangBelumDitagih?: Prisma.AkunCreateNestedOneWithoutPemetaanBarangBelumDitagihInput
  selisihPersediaan?: Prisma.AkunCreateNestedOneWithoutPemetaanSelisihPersediaanInput
}

export type PemetaanAkunUncheckedCreateWithoutHppInput = {
  id?: string
  piutangUsahaId: string
  persediaanId: string
  pendapatanPenjualanId: string
  utangUsahaId: string
  bebanJasaId?: string | null
  barangBelumDitagihId?: string | null
  selisihPersediaanId?: string | null
}

export type PemetaanAkunCreateOrConnectWithoutHppInput = {
  where: Prisma.PemetaanAkunWhereUniqueInput
  create: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutHppInput, Prisma.PemetaanAkunUncheckedCreateWithoutHppInput>
}

export type PemetaanAkunCreateWithoutPendapatanPenjualanInput = {
  id?: string
  piutangUsaha: Prisma.AkunCreateNestedOneWithoutPemetaanPiutangInput
  persediaan: Prisma.AkunCreateNestedOneWithoutPemetaanPersediaanInput
  hpp: Prisma.AkunCreateNestedOneWithoutPemetaanHppInput
  utangUsaha: Prisma.AkunCreateNestedOneWithoutPemetaanUtangInput
  bebanJasa?: Prisma.AkunCreateNestedOneWithoutPemetaanBebanJasaInput
  barangBelumDitagih?: Prisma.AkunCreateNestedOneWithoutPemetaanBarangBelumDitagihInput
  selisihPersediaan?: Prisma.AkunCreateNestedOneWithoutPemetaanSelisihPersediaanInput
}

export type PemetaanAkunUncheckedCreateWithoutPendapatanPenjualanInput = {
  id?: string
  piutangUsahaId: string
  persediaanId: string
  hppId: string
  utangUsahaId: string
  bebanJasaId?: string | null
  barangBelumDitagihId?: string | null
  selisihPersediaanId?: string | null
}

export type PemetaanAkunCreateOrConnectWithoutPendapatanPenjualanInput = {
  where: Prisma.PemetaanAkunWhereUniqueInput
  create: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutPendapatanPenjualanInput, Prisma.PemetaanAkunUncheckedCreateWithoutPendapatanPenjualanInput>
}

export type PemetaanAkunCreateWithoutUtangUsahaInput = {
  id?: string
  piutangUsaha: Prisma.AkunCreateNestedOneWithoutPemetaanPiutangInput
  persediaan: Prisma.AkunCreateNestedOneWithoutPemetaanPersediaanInput
  hpp: Prisma.AkunCreateNestedOneWithoutPemetaanHppInput
  pendapatanPenjualan: Prisma.AkunCreateNestedOneWithoutPemetaanPendapatanInput
  bebanJasa?: Prisma.AkunCreateNestedOneWithoutPemetaanBebanJasaInput
  barangBelumDitagih?: Prisma.AkunCreateNestedOneWithoutPemetaanBarangBelumDitagihInput
  selisihPersediaan?: Prisma.AkunCreateNestedOneWithoutPemetaanSelisihPersediaanInput
}

export type PemetaanAkunUncheckedCreateWithoutUtangUsahaInput = {
  id?: string
  piutangUsahaId: string
  persediaanId: string
  hppId: string
  pendapatanPenjualanId: string
  bebanJasaId?: string | null
  barangBelumDitagihId?: string | null
  selisihPersediaanId?: string | null
}

export type PemetaanAkunCreateOrConnectWithoutUtangUsahaInput = {
  where: Prisma.PemetaanAkunWhereUniqueInput
  create: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutUtangUsahaInput, Prisma.PemetaanAkunUncheckedCreateWithoutUtangUsahaInput>
}

export type PemetaanAkunCreateWithoutBebanJasaInput = {
  id?: string
  piutangUsaha: Prisma.AkunCreateNestedOneWithoutPemetaanPiutangInput
  persediaan: Prisma.AkunCreateNestedOneWithoutPemetaanPersediaanInput
  hpp: Prisma.AkunCreateNestedOneWithoutPemetaanHppInput
  pendapatanPenjualan: Prisma.AkunCreateNestedOneWithoutPemetaanPendapatanInput
  utangUsaha: Prisma.AkunCreateNestedOneWithoutPemetaanUtangInput
  barangBelumDitagih?: Prisma.AkunCreateNestedOneWithoutPemetaanBarangBelumDitagihInput
  selisihPersediaan?: Prisma.AkunCreateNestedOneWithoutPemetaanSelisihPersediaanInput
}

export type PemetaanAkunUncheckedCreateWithoutBebanJasaInput = {
  id?: string
  piutangUsahaId: string
  persediaanId: string
  hppId: string
  pendapatanPenjualanId: string
  utangUsahaId: string
  barangBelumDitagihId?: string | null
  selisihPersediaanId?: string | null
}

export type PemetaanAkunCreateOrConnectWithoutBebanJasaInput = {
  where: Prisma.PemetaanAkunWhereUniqueInput
  create: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutBebanJasaInput, Prisma.PemetaanAkunUncheckedCreateWithoutBebanJasaInput>
}

export type PemetaanAkunCreateWithoutBarangBelumDitagihInput = {
  id?: string
  piutangUsaha: Prisma.AkunCreateNestedOneWithoutPemetaanPiutangInput
  persediaan: Prisma.AkunCreateNestedOneWithoutPemetaanPersediaanInput
  hpp: Prisma.AkunCreateNestedOneWithoutPemetaanHppInput
  pendapatanPenjualan: Prisma.AkunCreateNestedOneWithoutPemetaanPendapatanInput
  utangUsaha: Prisma.AkunCreateNestedOneWithoutPemetaanUtangInput
  bebanJasa?: Prisma.AkunCreateNestedOneWithoutPemetaanBebanJasaInput
  selisihPersediaan?: Prisma.AkunCreateNestedOneWithoutPemetaanSelisihPersediaanInput
}

export type PemetaanAkunUncheckedCreateWithoutBarangBelumDitagihInput = {
  id?: string
  piutangUsahaId: string
  persediaanId: string
  hppId: string
  pendapatanPenjualanId: string
  utangUsahaId: string
  bebanJasaId?: string | null
  selisihPersediaanId?: string | null
}

export type PemetaanAkunCreateOrConnectWithoutBarangBelumDitagihInput = {
  where: Prisma.PemetaanAkunWhereUniqueInput
  create: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutBarangBelumDitagihInput, Prisma.PemetaanAkunUncheckedCreateWithoutBarangBelumDitagihInput>
}

export type PemetaanAkunCreateWithoutSelisihPersediaanInput = {
  id?: string
  piutangUsaha: Prisma.AkunCreateNestedOneWithoutPemetaanPiutangInput
  persediaan: Prisma.AkunCreateNestedOneWithoutPemetaanPersediaanInput
  hpp: Prisma.AkunCreateNestedOneWithoutPemetaanHppInput
  pendapatanPenjualan: Prisma.AkunCreateNestedOneWithoutPemetaanPendapatanInput
  utangUsaha: Prisma.AkunCreateNestedOneWithoutPemetaanUtangInput
  bebanJasa?: Prisma.AkunCreateNestedOneWithoutPemetaanBebanJasaInput
  barangBelumDitagih?: Prisma.AkunCreateNestedOneWithoutPemetaanBarangBelumDitagihInput
}

export type PemetaanAkunUncheckedCreateWithoutSelisihPersediaanInput = {
  id?: string
  piutangUsahaId: string
  persediaanId: string
  hppId: string
  pendapatanPenjualanId: string
  utangUsahaId: string
  bebanJasaId?: string | null
  barangBelumDitagihId?: string | null
}

export type PemetaanAkunCreateOrConnectWithoutSelisihPersediaanInput = {
  where: Prisma.PemetaanAkunWhereUniqueInput
  create: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutSelisihPersediaanInput, Prisma.PemetaanAkunUncheckedCreateWithoutSelisihPersediaanInput>
}

export type PemetaanAkunUpsertWithoutPiutangUsahaInput = {
  update: Prisma.XOR<Prisma.PemetaanAkunUpdateWithoutPiutangUsahaInput, Prisma.PemetaanAkunUncheckedUpdateWithoutPiutangUsahaInput>
  create: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutPiutangUsahaInput, Prisma.PemetaanAkunUncheckedCreateWithoutPiutangUsahaInput>
  where?: Prisma.PemetaanAkunWhereInput
}

export type PemetaanAkunUpdateToOneWithWhereWithoutPiutangUsahaInput = {
  where?: Prisma.PemetaanAkunWhereInput
  data: Prisma.XOR<Prisma.PemetaanAkunUpdateWithoutPiutangUsahaInput, Prisma.PemetaanAkunUncheckedUpdateWithoutPiutangUsahaInput>
}

export type PemetaanAkunUpdateWithoutPiutangUsahaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  persediaan?: Prisma.AkunUpdateOneRequiredWithoutPemetaanPersediaanNestedInput
  hpp?: Prisma.AkunUpdateOneRequiredWithoutPemetaanHppNestedInput
  pendapatanPenjualan?: Prisma.AkunUpdateOneRequiredWithoutPemetaanPendapatanNestedInput
  utangUsaha?: Prisma.AkunUpdateOneRequiredWithoutPemetaanUtangNestedInput
  bebanJasa?: Prisma.AkunUpdateOneWithoutPemetaanBebanJasaNestedInput
  barangBelumDitagih?: Prisma.AkunUpdateOneWithoutPemetaanBarangBelumDitagihNestedInput
  selisihPersediaan?: Prisma.AkunUpdateOneWithoutPemetaanSelisihPersediaanNestedInput
}

export type PemetaanAkunUncheckedUpdateWithoutPiutangUsahaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  persediaanId?: Prisma.StringFieldUpdateOperationsInput | string
  hppId?: Prisma.StringFieldUpdateOperationsInput | string
  pendapatanPenjualanId?: Prisma.StringFieldUpdateOperationsInput | string
  utangUsahaId?: Prisma.StringFieldUpdateOperationsInput | string
  bebanJasaId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  barangBelumDitagihId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  selisihPersediaanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PemetaanAkunUpsertWithoutPersediaanInput = {
  update: Prisma.XOR<Prisma.PemetaanAkunUpdateWithoutPersediaanInput, Prisma.PemetaanAkunUncheckedUpdateWithoutPersediaanInput>
  create: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutPersediaanInput, Prisma.PemetaanAkunUncheckedCreateWithoutPersediaanInput>
  where?: Prisma.PemetaanAkunWhereInput
}

export type PemetaanAkunUpdateToOneWithWhereWithoutPersediaanInput = {
  where?: Prisma.PemetaanAkunWhereInput
  data: Prisma.XOR<Prisma.PemetaanAkunUpdateWithoutPersediaanInput, Prisma.PemetaanAkunUncheckedUpdateWithoutPersediaanInput>
}

export type PemetaanAkunUpdateWithoutPersediaanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  piutangUsaha?: Prisma.AkunUpdateOneRequiredWithoutPemetaanPiutangNestedInput
  hpp?: Prisma.AkunUpdateOneRequiredWithoutPemetaanHppNestedInput
  pendapatanPenjualan?: Prisma.AkunUpdateOneRequiredWithoutPemetaanPendapatanNestedInput
  utangUsaha?: Prisma.AkunUpdateOneRequiredWithoutPemetaanUtangNestedInput
  bebanJasa?: Prisma.AkunUpdateOneWithoutPemetaanBebanJasaNestedInput
  barangBelumDitagih?: Prisma.AkunUpdateOneWithoutPemetaanBarangBelumDitagihNestedInput
  selisihPersediaan?: Prisma.AkunUpdateOneWithoutPemetaanSelisihPersediaanNestedInput
}

export type PemetaanAkunUncheckedUpdateWithoutPersediaanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  piutangUsahaId?: Prisma.StringFieldUpdateOperationsInput | string
  hppId?: Prisma.StringFieldUpdateOperationsInput | string
  pendapatanPenjualanId?: Prisma.StringFieldUpdateOperationsInput | string
  utangUsahaId?: Prisma.StringFieldUpdateOperationsInput | string
  bebanJasaId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  barangBelumDitagihId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  selisihPersediaanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PemetaanAkunUpsertWithoutHppInput = {
  update: Prisma.XOR<Prisma.PemetaanAkunUpdateWithoutHppInput, Prisma.PemetaanAkunUncheckedUpdateWithoutHppInput>
  create: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutHppInput, Prisma.PemetaanAkunUncheckedCreateWithoutHppInput>
  where?: Prisma.PemetaanAkunWhereInput
}

export type PemetaanAkunUpdateToOneWithWhereWithoutHppInput = {
  where?: Prisma.PemetaanAkunWhereInput
  data: Prisma.XOR<Prisma.PemetaanAkunUpdateWithoutHppInput, Prisma.PemetaanAkunUncheckedUpdateWithoutHppInput>
}

export type PemetaanAkunUpdateWithoutHppInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  piutangUsaha?: Prisma.AkunUpdateOneRequiredWithoutPemetaanPiutangNestedInput
  persediaan?: Prisma.AkunUpdateOneRequiredWithoutPemetaanPersediaanNestedInput
  pendapatanPenjualan?: Prisma.AkunUpdateOneRequiredWithoutPemetaanPendapatanNestedInput
  utangUsaha?: Prisma.AkunUpdateOneRequiredWithoutPemetaanUtangNestedInput
  bebanJasa?: Prisma.AkunUpdateOneWithoutPemetaanBebanJasaNestedInput
  barangBelumDitagih?: Prisma.AkunUpdateOneWithoutPemetaanBarangBelumDitagihNestedInput
  selisihPersediaan?: Prisma.AkunUpdateOneWithoutPemetaanSelisihPersediaanNestedInput
}

export type PemetaanAkunUncheckedUpdateWithoutHppInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  piutangUsahaId?: Prisma.StringFieldUpdateOperationsInput | string
  persediaanId?: Prisma.StringFieldUpdateOperationsInput | string
  pendapatanPenjualanId?: Prisma.StringFieldUpdateOperationsInput | string
  utangUsahaId?: Prisma.StringFieldUpdateOperationsInput | string
  bebanJasaId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  barangBelumDitagihId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  selisihPersediaanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PemetaanAkunUpsertWithoutPendapatanPenjualanInput = {
  update: Prisma.XOR<Prisma.PemetaanAkunUpdateWithoutPendapatanPenjualanInput, Prisma.PemetaanAkunUncheckedUpdateWithoutPendapatanPenjualanInput>
  create: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutPendapatanPenjualanInput, Prisma.PemetaanAkunUncheckedCreateWithoutPendapatanPenjualanInput>
  where?: Prisma.PemetaanAkunWhereInput
}

export type PemetaanAkunUpdateToOneWithWhereWithoutPendapatanPenjualanInput = {
  where?: Prisma.PemetaanAkunWhereInput
  data: Prisma.XOR<Prisma.PemetaanAkunUpdateWithoutPendapatanPenjualanInput, Prisma.PemetaanAkunUncheckedUpdateWithoutPendapatanPenjualanInput>
}

export type PemetaanAkunUpdateWithoutPendapatanPenjualanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  piutangUsaha?: Prisma.AkunUpdateOneRequiredWithoutPemetaanPiutangNestedInput
  persediaan?: Prisma.AkunUpdateOneRequiredWithoutPemetaanPersediaanNestedInput
  hpp?: Prisma.AkunUpdateOneRequiredWithoutPemetaanHppNestedInput
  utangUsaha?: Prisma.AkunUpdateOneRequiredWithoutPemetaanUtangNestedInput
  bebanJasa?: Prisma.AkunUpdateOneWithoutPemetaanBebanJasaNestedInput
  barangBelumDitagih?: Prisma.AkunUpdateOneWithoutPemetaanBarangBelumDitagihNestedInput
  selisihPersediaan?: Prisma.AkunUpdateOneWithoutPemetaanSelisihPersediaanNestedInput
}

export type PemetaanAkunUncheckedUpdateWithoutPendapatanPenjualanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  piutangUsahaId?: Prisma.StringFieldUpdateOperationsInput | string
  persediaanId?: Prisma.StringFieldUpdateOperationsInput | string
  hppId?: Prisma.StringFieldUpdateOperationsInput | string
  utangUsahaId?: Prisma.StringFieldUpdateOperationsInput | string
  bebanJasaId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  barangBelumDitagihId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  selisihPersediaanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PemetaanAkunUpsertWithoutUtangUsahaInput = {
  update: Prisma.XOR<Prisma.PemetaanAkunUpdateWithoutUtangUsahaInput, Prisma.PemetaanAkunUncheckedUpdateWithoutUtangUsahaInput>
  create: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutUtangUsahaInput, Prisma.PemetaanAkunUncheckedCreateWithoutUtangUsahaInput>
  where?: Prisma.PemetaanAkunWhereInput
}

export type PemetaanAkunUpdateToOneWithWhereWithoutUtangUsahaInput = {
  where?: Prisma.PemetaanAkunWhereInput
  data: Prisma.XOR<Prisma.PemetaanAkunUpdateWithoutUtangUsahaInput, Prisma.PemetaanAkunUncheckedUpdateWithoutUtangUsahaInput>
}

export type PemetaanAkunUpdateWithoutUtangUsahaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  piutangUsaha?: Prisma.AkunUpdateOneRequiredWithoutPemetaanPiutangNestedInput
  persediaan?: Prisma.AkunUpdateOneRequiredWithoutPemetaanPersediaanNestedInput
  hpp?: Prisma.AkunUpdateOneRequiredWithoutPemetaanHppNestedInput
  pendapatanPenjualan?: Prisma.AkunUpdateOneRequiredWithoutPemetaanPendapatanNestedInput
  bebanJasa?: Prisma.AkunUpdateOneWithoutPemetaanBebanJasaNestedInput
  barangBelumDitagih?: Prisma.AkunUpdateOneWithoutPemetaanBarangBelumDitagihNestedInput
  selisihPersediaan?: Prisma.AkunUpdateOneWithoutPemetaanSelisihPersediaanNestedInput
}

export type PemetaanAkunUncheckedUpdateWithoutUtangUsahaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  piutangUsahaId?: Prisma.StringFieldUpdateOperationsInput | string
  persediaanId?: Prisma.StringFieldUpdateOperationsInput | string
  hppId?: Prisma.StringFieldUpdateOperationsInput | string
  pendapatanPenjualanId?: Prisma.StringFieldUpdateOperationsInput | string
  bebanJasaId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  barangBelumDitagihId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  selisihPersediaanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PemetaanAkunUpsertWithoutBebanJasaInput = {
  update: Prisma.XOR<Prisma.PemetaanAkunUpdateWithoutBebanJasaInput, Prisma.PemetaanAkunUncheckedUpdateWithoutBebanJasaInput>
  create: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutBebanJasaInput, Prisma.PemetaanAkunUncheckedCreateWithoutBebanJasaInput>
  where?: Prisma.PemetaanAkunWhereInput
}

export type PemetaanAkunUpdateToOneWithWhereWithoutBebanJasaInput = {
  where?: Prisma.PemetaanAkunWhereInput
  data: Prisma.XOR<Prisma.PemetaanAkunUpdateWithoutBebanJasaInput, Prisma.PemetaanAkunUncheckedUpdateWithoutBebanJasaInput>
}

export type PemetaanAkunUpdateWithoutBebanJasaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  piutangUsaha?: Prisma.AkunUpdateOneRequiredWithoutPemetaanPiutangNestedInput
  persediaan?: Prisma.AkunUpdateOneRequiredWithoutPemetaanPersediaanNestedInput
  hpp?: Prisma.AkunUpdateOneRequiredWithoutPemetaanHppNestedInput
  pendapatanPenjualan?: Prisma.AkunUpdateOneRequiredWithoutPemetaanPendapatanNestedInput
  utangUsaha?: Prisma.AkunUpdateOneRequiredWithoutPemetaanUtangNestedInput
  barangBelumDitagih?: Prisma.AkunUpdateOneWithoutPemetaanBarangBelumDitagihNestedInput
  selisihPersediaan?: Prisma.AkunUpdateOneWithoutPemetaanSelisihPersediaanNestedInput
}

export type PemetaanAkunUncheckedUpdateWithoutBebanJasaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  piutangUsahaId?: Prisma.StringFieldUpdateOperationsInput | string
  persediaanId?: Prisma.StringFieldUpdateOperationsInput | string
  hppId?: Prisma.StringFieldUpdateOperationsInput | string
  pendapatanPenjualanId?: Prisma.StringFieldUpdateOperationsInput | string
  utangUsahaId?: Prisma.StringFieldUpdateOperationsInput | string
  barangBelumDitagihId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  selisihPersediaanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PemetaanAkunUpsertWithoutBarangBelumDitagihInput = {
  update: Prisma.XOR<Prisma.PemetaanAkunUpdateWithoutBarangBelumDitagihInput, Prisma.PemetaanAkunUncheckedUpdateWithoutBarangBelumDitagihInput>
  create: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutBarangBelumDitagihInput, Prisma.PemetaanAkunUncheckedCreateWithoutBarangBelumDitagihInput>
  where?: Prisma.PemetaanAkunWhereInput
}

export type PemetaanAkunUpdateToOneWithWhereWithoutBarangBelumDitagihInput = {
  where?: Prisma.PemetaanAkunWhereInput
  data: Prisma.XOR<Prisma.PemetaanAkunUpdateWithoutBarangBelumDitagihInput, Prisma.PemetaanAkunUncheckedUpdateWithoutBarangBelumDitagihInput>
}

export type PemetaanAkunUpdateWithoutBarangBelumDitagihInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  piutangUsaha?: Prisma.AkunUpdateOneRequiredWithoutPemetaanPiutangNestedInput
  persediaan?: Prisma.AkunUpdateOneRequiredWithoutPemetaanPersediaanNestedInput
  hpp?: Prisma.AkunUpdateOneRequiredWithoutPemetaanHppNestedInput
  pendapatanPenjualan?: Prisma.AkunUpdateOneRequiredWithoutPemetaanPendapatanNestedInput
  utangUsaha?: Prisma.AkunUpdateOneRequiredWithoutPemetaanUtangNestedInput
  bebanJasa?: Prisma.AkunUpdateOneWithoutPemetaanBebanJasaNestedInput
  selisihPersediaan?: Prisma.AkunUpdateOneWithoutPemetaanSelisihPersediaanNestedInput
}

export type PemetaanAkunUncheckedUpdateWithoutBarangBelumDitagihInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  piutangUsahaId?: Prisma.StringFieldUpdateOperationsInput | string
  persediaanId?: Prisma.StringFieldUpdateOperationsInput | string
  hppId?: Prisma.StringFieldUpdateOperationsInput | string
  pendapatanPenjualanId?: Prisma.StringFieldUpdateOperationsInput | string
  utangUsahaId?: Prisma.StringFieldUpdateOperationsInput | string
  bebanJasaId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  selisihPersediaanId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PemetaanAkunUpsertWithoutSelisihPersediaanInput = {
  update: Prisma.XOR<Prisma.PemetaanAkunUpdateWithoutSelisihPersediaanInput, Prisma.PemetaanAkunUncheckedUpdateWithoutSelisihPersediaanInput>
  create: Prisma.XOR<Prisma.PemetaanAkunCreateWithoutSelisihPersediaanInput, Prisma.PemetaanAkunUncheckedCreateWithoutSelisihPersediaanInput>
  where?: Prisma.PemetaanAkunWhereInput
}

export type PemetaanAkunUpdateToOneWithWhereWithoutSelisihPersediaanInput = {
  where?: Prisma.PemetaanAkunWhereInput
  data: Prisma.XOR<Prisma.PemetaanAkunUpdateWithoutSelisihPersediaanInput, Prisma.PemetaanAkunUncheckedUpdateWithoutSelisihPersediaanInput>
}

export type PemetaanAkunUpdateWithoutSelisihPersediaanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  piutangUsaha?: Prisma.AkunUpdateOneRequiredWithoutPemetaanPiutangNestedInput
  persediaan?: Prisma.AkunUpdateOneRequiredWithoutPemetaanPersediaanNestedInput
  hpp?: Prisma.AkunUpdateOneRequiredWithoutPemetaanHppNestedInput
  pendapatanPenjualan?: Prisma.AkunUpdateOneRequiredWithoutPemetaanPendapatanNestedInput
  utangUsaha?: Prisma.AkunUpdateOneRequiredWithoutPemetaanUtangNestedInput
  bebanJasa?: Prisma.AkunUpdateOneWithoutPemetaanBebanJasaNestedInput
  barangBelumDitagih?: Prisma.AkunUpdateOneWithoutPemetaanBarangBelumDitagihNestedInput
}

export type PemetaanAkunUncheckedUpdateWithoutSelisihPersediaanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  piutangUsahaId?: Prisma.StringFieldUpdateOperationsInput | string
  persediaanId?: Prisma.StringFieldUpdateOperationsInput | string
  hppId?: Prisma.StringFieldUpdateOperationsInput | string
  pendapatanPenjualanId?: Prisma.StringFieldUpdateOperationsInput | string
  utangUsahaId?: Prisma.StringFieldUpdateOperationsInput | string
  bebanJasaId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  barangBelumDitagihId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type PemetaanAkunSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  piutangUsahaId?: boolean
  persediaanId?: boolean
  hppId?: boolean
  pendapatanPenjualanId?: boolean
  utangUsahaId?: boolean
  bebanJasaId?: boolean
  barangBelumDitagihId?: boolean
  selisihPersediaanId?: boolean
  piutangUsaha?: boolean | Prisma.AkunDefaultArgs<ExtArgs>
  persediaan?: boolean | Prisma.AkunDefaultArgs<ExtArgs>
  hpp?: boolean | Prisma.AkunDefaultArgs<ExtArgs>
  pendapatanPenjualan?: boolean | Prisma.AkunDefaultArgs<ExtArgs>
  utangUsaha?: boolean | Prisma.AkunDefaultArgs<ExtArgs>
  bebanJasa?: boolean | Prisma.PemetaanAkun$bebanJasaArgs<ExtArgs>
  barangBelumDitagih?: boolean | Prisma.PemetaanAkun$barangBelumDitagihArgs<ExtArgs>
  selisihPersediaan?: boolean | Prisma.PemetaanAkun$selisihPersediaanArgs<ExtArgs>
}, ExtArgs["result"]["pemetaanAkun"]>

export type PemetaanAkunSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  piutangUsahaId?: boolean
  persediaanId?: boolean
  hppId?: boolean
  pendapatanPenjualanId?: boolean
  utangUsahaId?: boolean
  bebanJasaId?: boolean
  barangBelumDitagihId?: boolean
  selisihPersediaanId?: boolean
  piutangUsaha?: boolean | Prisma.AkunDefaultArgs<ExtArgs>
  persediaan?: boolean | Prisma.AkunDefaultArgs<ExtArgs>
  hpp?: boolean | Prisma.AkunDefaultArgs<ExtArgs>
  pendapatanPenjualan?: boolean | Prisma.AkunDefaultArgs<ExtArgs>
  utangUsaha?: boolean | Prisma.AkunDefaultArgs<ExtArgs>
  bebanJasa?: boolean | Prisma.PemetaanAkun$bebanJasaArgs<ExtArgs>
  barangBelumDitagih?: boolean | Prisma.PemetaanAkun$barangBelumDitagihArgs<ExtArgs>
  selisihPersediaan?: boolean | Prisma.PemetaanAkun$selisihPersediaanArgs<ExtArgs>
}, ExtArgs["result"]["pemetaanAkun"]>

export type PemetaanAkunSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  piutangUsahaId?: boolean
  persediaanId?: boolean
  hppId?: boolean
  pendapatanPenjualanId?: boolean
  utangUsahaId?: boolean
  bebanJasaId?: boolean
  barangBelumDitagihId?: boolean
  selisihPersediaanId?: boolean
  piutangUsaha?: boolean | Prisma.AkunDefaultArgs<ExtArgs>
  persediaan?: boolean | Prisma.AkunDefaultArgs<ExtArgs>
  hpp?: boolean | Prisma.AkunDefaultArgs<ExtArgs>
  pendapatanPenjualan?: boolean | Prisma.AkunDefaultArgs<ExtArgs>
  utangUsaha?: boolean | Prisma.AkunDefaultArgs<ExtArgs>
  bebanJasa?: boolean | Prisma.PemetaanAkun$bebanJasaArgs<ExtArgs>
  barangBelumDitagih?: boolean | Prisma.PemetaanAkun$barangBelumDitagihArgs<ExtArgs>
  selisihPersediaan?: boolean | Prisma.PemetaanAkun$selisihPersediaanArgs<ExtArgs>
}, ExtArgs["result"]["pemetaanAkun"]>

export type PemetaanAkunSelectScalar = {
  id?: boolean
  piutangUsahaId?: boolean
  persediaanId?: boolean
  hppId?: boolean
  pendapatanPenjualanId?: boolean
  utangUsahaId?: boolean
  bebanJasaId?: boolean
  barangBelumDitagihId?: boolean
  selisihPersediaanId?: boolean
}

export type PemetaanAkunOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "piutangUsahaId" | "persediaanId" | "hppId" | "pendapatanPenjualanId" | "utangUsahaId" | "bebanJasaId" | "barangBelumDitagihId" | "selisihPersediaanId", ExtArgs["result"]["pemetaanAkun"]>
export type PemetaanAkunInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  piutangUsaha?: boolean | Prisma.AkunDefaultArgs<ExtArgs>
  persediaan?: boolean | Prisma.AkunDefaultArgs<ExtArgs>
  hpp?: boolean | Prisma.AkunDefaultArgs<ExtArgs>
  pendapatanPenjualan?: boolean | Prisma.AkunDefaultArgs<ExtArgs>
  utangUsaha?: boolean | Prisma.AkunDefaultArgs<ExtArgs>
  bebanJasa?: boolean | Prisma.PemetaanAkun$bebanJasaArgs<ExtArgs>
  barangBelumDitagih?: boolean | Prisma.PemetaanAkun$barangBelumDitagihArgs<ExtArgs>
  selisihPersediaan?: boolean | Prisma.PemetaanAkun$selisihPersediaanArgs<ExtArgs>
}
export type PemetaanAkunIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  piutangUsaha?: boolean | Prisma.AkunDefaultArgs<ExtArgs>
  persediaan?: boolean | Prisma.AkunDefaultArgs<ExtArgs>
  hpp?: boolean | Prisma.AkunDefaultArgs<ExtArgs>
  pendapatanPenjualan?: boolean | Prisma.AkunDefaultArgs<ExtArgs>
  utangUsaha?: boolean | Prisma.AkunDefaultArgs<ExtArgs>
  bebanJasa?: boolean | Prisma.PemetaanAkun$bebanJasaArgs<ExtArgs>
  barangBelumDitagih?: boolean | Prisma.PemetaanAkun$barangBelumDitagihArgs<ExtArgs>
  selisihPersediaan?: boolean | Prisma.PemetaanAkun$selisihPersediaanArgs<ExtArgs>
}
export type PemetaanAkunIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  piutangUsaha?: boolean | Prisma.AkunDefaultArgs<ExtArgs>
  persediaan?: boolean | Prisma.AkunDefaultArgs<ExtArgs>
  hpp?: boolean | Prisma.AkunDefaultArgs<ExtArgs>
  pendapatanPenjualan?: boolean | Prisma.AkunDefaultArgs<ExtArgs>
  utangUsaha?: boolean | Prisma.AkunDefaultArgs<ExtArgs>
  bebanJasa?: boolean | Prisma.PemetaanAkun$bebanJasaArgs<ExtArgs>
  barangBelumDitagih?: boolean | Prisma.PemetaanAkun$barangBelumDitagihArgs<ExtArgs>
  selisihPersediaan?: boolean | Prisma.PemetaanAkun$selisihPersediaanArgs<ExtArgs>
}

export type $PemetaanAkunPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PemetaanAkun"
  objects: {
    piutangUsaha: Prisma.$AkunPayload<ExtArgs>
    persediaan: Prisma.$AkunPayload<ExtArgs>
    hpp: Prisma.$AkunPayload<ExtArgs>
    pendapatanPenjualan: Prisma.$AkunPayload<ExtArgs>
    utangUsaha: Prisma.$AkunPayload<ExtArgs>
    bebanJasa: Prisma.$AkunPayload<ExtArgs> | null
    barangBelumDitagih: Prisma.$AkunPayload<ExtArgs> | null
    selisihPersediaan: Prisma.$AkunPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    piutangUsahaId: string
    persediaanId: string
    hppId: string
    pendapatanPenjualanId: string
    utangUsahaId: string
    /**
     * Beban untuk pembelian JASA (kosong = HPP)
     */
    bebanJasaId: string | null
    /**
     * Kewajiban sementara: barang sudah diterima (TB) tapi belum ditagih (FB)
     */
    barangBelumDitagihId: string | null
    /**
     * Selisih nilai persediaan (retur pembelian beda harga, penyesuaian stok)
     */
    selisihPersediaanId: string | null
  }, ExtArgs["result"]["pemetaanAkun"]>
  composites: {}
}

export type PemetaanAkunGetPayload<S extends boolean | null | undefined | PemetaanAkunDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PemetaanAkunPayload, S>

export type PemetaanAkunCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PemetaanAkunFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PemetaanAkunCountAggregateInputType | true
  }

export interface PemetaanAkunDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PemetaanAkun'], meta: { name: 'PemetaanAkun' } }
  /**
   * Find zero or one PemetaanAkun that matches the filter.
   * @param {PemetaanAkunFindUniqueArgs} args - Arguments to find a PemetaanAkun
   * @example
   * // Get one PemetaanAkun
   * const pemetaanAkun = await prisma.pemetaanAkun.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PemetaanAkunFindUniqueArgs>(args: Prisma.SelectSubset<T, PemetaanAkunFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PemetaanAkunClient<runtime.Types.Result.GetResult<Prisma.$PemetaanAkunPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PemetaanAkun that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PemetaanAkunFindUniqueOrThrowArgs} args - Arguments to find a PemetaanAkun
   * @example
   * // Get one PemetaanAkun
   * const pemetaanAkun = await prisma.pemetaanAkun.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PemetaanAkunFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PemetaanAkunFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PemetaanAkunClient<runtime.Types.Result.GetResult<Prisma.$PemetaanAkunPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PemetaanAkun that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PemetaanAkunFindFirstArgs} args - Arguments to find a PemetaanAkun
   * @example
   * // Get one PemetaanAkun
   * const pemetaanAkun = await prisma.pemetaanAkun.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PemetaanAkunFindFirstArgs>(args?: Prisma.SelectSubset<T, PemetaanAkunFindFirstArgs<ExtArgs>>): Prisma.Prisma__PemetaanAkunClient<runtime.Types.Result.GetResult<Prisma.$PemetaanAkunPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PemetaanAkun that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PemetaanAkunFindFirstOrThrowArgs} args - Arguments to find a PemetaanAkun
   * @example
   * // Get one PemetaanAkun
   * const pemetaanAkun = await prisma.pemetaanAkun.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PemetaanAkunFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PemetaanAkunFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PemetaanAkunClient<runtime.Types.Result.GetResult<Prisma.$PemetaanAkunPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PemetaanAkuns that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PemetaanAkunFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PemetaanAkuns
   * const pemetaanAkuns = await prisma.pemetaanAkun.findMany()
   * 
   * // Get first 10 PemetaanAkuns
   * const pemetaanAkuns = await prisma.pemetaanAkun.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const pemetaanAkunWithIdOnly = await prisma.pemetaanAkun.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PemetaanAkunFindManyArgs>(args?: Prisma.SelectSubset<T, PemetaanAkunFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PemetaanAkunPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PemetaanAkun.
   * @param {PemetaanAkunCreateArgs} args - Arguments to create a PemetaanAkun.
   * @example
   * // Create one PemetaanAkun
   * const PemetaanAkun = await prisma.pemetaanAkun.create({
   *   data: {
   *     // ... data to create a PemetaanAkun
   *   }
   * })
   * 
   */
  create<T extends PemetaanAkunCreateArgs>(args: Prisma.SelectSubset<T, PemetaanAkunCreateArgs<ExtArgs>>): Prisma.Prisma__PemetaanAkunClient<runtime.Types.Result.GetResult<Prisma.$PemetaanAkunPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PemetaanAkuns.
   * @param {PemetaanAkunCreateManyArgs} args - Arguments to create many PemetaanAkuns.
   * @example
   * // Create many PemetaanAkuns
   * const pemetaanAkun = await prisma.pemetaanAkun.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PemetaanAkunCreateManyArgs>(args?: Prisma.SelectSubset<T, PemetaanAkunCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PemetaanAkuns and returns the data saved in the database.
   * @param {PemetaanAkunCreateManyAndReturnArgs} args - Arguments to create many PemetaanAkuns.
   * @example
   * // Create many PemetaanAkuns
   * const pemetaanAkun = await prisma.pemetaanAkun.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PemetaanAkuns and only return the `id`
   * const pemetaanAkunWithIdOnly = await prisma.pemetaanAkun.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PemetaanAkunCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PemetaanAkunCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PemetaanAkunPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PemetaanAkun.
   * @param {PemetaanAkunDeleteArgs} args - Arguments to delete one PemetaanAkun.
   * @example
   * // Delete one PemetaanAkun
   * const PemetaanAkun = await prisma.pemetaanAkun.delete({
   *   where: {
   *     // ... filter to delete one PemetaanAkun
   *   }
   * })
   * 
   */
  delete<T extends PemetaanAkunDeleteArgs>(args: Prisma.SelectSubset<T, PemetaanAkunDeleteArgs<ExtArgs>>): Prisma.Prisma__PemetaanAkunClient<runtime.Types.Result.GetResult<Prisma.$PemetaanAkunPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PemetaanAkun.
   * @param {PemetaanAkunUpdateArgs} args - Arguments to update one PemetaanAkun.
   * @example
   * // Update one PemetaanAkun
   * const pemetaanAkun = await prisma.pemetaanAkun.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PemetaanAkunUpdateArgs>(args: Prisma.SelectSubset<T, PemetaanAkunUpdateArgs<ExtArgs>>): Prisma.Prisma__PemetaanAkunClient<runtime.Types.Result.GetResult<Prisma.$PemetaanAkunPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PemetaanAkuns.
   * @param {PemetaanAkunDeleteManyArgs} args - Arguments to filter PemetaanAkuns to delete.
   * @example
   * // Delete a few PemetaanAkuns
   * const { count } = await prisma.pemetaanAkun.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PemetaanAkunDeleteManyArgs>(args?: Prisma.SelectSubset<T, PemetaanAkunDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PemetaanAkuns.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PemetaanAkunUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PemetaanAkuns
   * const pemetaanAkun = await prisma.pemetaanAkun.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PemetaanAkunUpdateManyArgs>(args: Prisma.SelectSubset<T, PemetaanAkunUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PemetaanAkuns and returns the data updated in the database.
   * @param {PemetaanAkunUpdateManyAndReturnArgs} args - Arguments to update many PemetaanAkuns.
   * @example
   * // Update many PemetaanAkuns
   * const pemetaanAkun = await prisma.pemetaanAkun.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PemetaanAkuns and only return the `id`
   * const pemetaanAkunWithIdOnly = await prisma.pemetaanAkun.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PemetaanAkunUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PemetaanAkunUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PemetaanAkunPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PemetaanAkun.
   * @param {PemetaanAkunUpsertArgs} args - Arguments to update or create a PemetaanAkun.
   * @example
   * // Update or create a PemetaanAkun
   * const pemetaanAkun = await prisma.pemetaanAkun.upsert({
   *   create: {
   *     // ... data to create a PemetaanAkun
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PemetaanAkun we want to update
   *   }
   * })
   */
  upsert<T extends PemetaanAkunUpsertArgs>(args: Prisma.SelectSubset<T, PemetaanAkunUpsertArgs<ExtArgs>>): Prisma.Prisma__PemetaanAkunClient<runtime.Types.Result.GetResult<Prisma.$PemetaanAkunPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PemetaanAkuns.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PemetaanAkunCountArgs} args - Arguments to filter PemetaanAkuns to count.
   * @example
   * // Count the number of PemetaanAkuns
   * const count = await prisma.pemetaanAkun.count({
   *   where: {
   *     // ... the filter for the PemetaanAkuns we want to count
   *   }
   * })
  **/
  count<T extends PemetaanAkunCountArgs>(
    args?: Prisma.Subset<T, PemetaanAkunCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PemetaanAkunCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PemetaanAkun.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PemetaanAkunAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PemetaanAkunAggregateArgs>(args: Prisma.Subset<T, PemetaanAkunAggregateArgs>): Prisma.PrismaPromise<GetPemetaanAkunAggregateType<T>>

  /**
   * Group by PemetaanAkun.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PemetaanAkunGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PemetaanAkunGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PemetaanAkunGroupByArgs['orderBy'] }
      : { orderBy?: PemetaanAkunGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PemetaanAkunGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPemetaanAkunGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PemetaanAkun model
 */
readonly fields: PemetaanAkunFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PemetaanAkun.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PemetaanAkunClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  piutangUsaha<T extends Prisma.AkunDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AkunDefaultArgs<ExtArgs>>): Prisma.Prisma__AkunClient<runtime.Types.Result.GetResult<Prisma.$AkunPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  persediaan<T extends Prisma.AkunDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AkunDefaultArgs<ExtArgs>>): Prisma.Prisma__AkunClient<runtime.Types.Result.GetResult<Prisma.$AkunPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  hpp<T extends Prisma.AkunDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AkunDefaultArgs<ExtArgs>>): Prisma.Prisma__AkunClient<runtime.Types.Result.GetResult<Prisma.$AkunPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  pendapatanPenjualan<T extends Prisma.AkunDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AkunDefaultArgs<ExtArgs>>): Prisma.Prisma__AkunClient<runtime.Types.Result.GetResult<Prisma.$AkunPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  utangUsaha<T extends Prisma.AkunDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AkunDefaultArgs<ExtArgs>>): Prisma.Prisma__AkunClient<runtime.Types.Result.GetResult<Prisma.$AkunPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  bebanJasa<T extends Prisma.PemetaanAkun$bebanJasaArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PemetaanAkun$bebanJasaArgs<ExtArgs>>): Prisma.Prisma__AkunClient<runtime.Types.Result.GetResult<Prisma.$AkunPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  barangBelumDitagih<T extends Prisma.PemetaanAkun$barangBelumDitagihArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PemetaanAkun$barangBelumDitagihArgs<ExtArgs>>): Prisma.Prisma__AkunClient<runtime.Types.Result.GetResult<Prisma.$AkunPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  selisihPersediaan<T extends Prisma.PemetaanAkun$selisihPersediaanArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PemetaanAkun$selisihPersediaanArgs<ExtArgs>>): Prisma.Prisma__AkunClient<runtime.Types.Result.GetResult<Prisma.$AkunPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PemetaanAkun model
 */
export interface PemetaanAkunFieldRefs {
  readonly id: Prisma.FieldRef<"PemetaanAkun", 'String'>
  readonly piutangUsahaId: Prisma.FieldRef<"PemetaanAkun", 'String'>
  readonly persediaanId: Prisma.FieldRef<"PemetaanAkun", 'String'>
  readonly hppId: Prisma.FieldRef<"PemetaanAkun", 'String'>
  readonly pendapatanPenjualanId: Prisma.FieldRef<"PemetaanAkun", 'String'>
  readonly utangUsahaId: Prisma.FieldRef<"PemetaanAkun", 'String'>
  readonly bebanJasaId: Prisma.FieldRef<"PemetaanAkun", 'String'>
  readonly barangBelumDitagihId: Prisma.FieldRef<"PemetaanAkun", 'String'>
  readonly selisihPersediaanId: Prisma.FieldRef<"PemetaanAkun", 'String'>
}
    

// Custom InputTypes
/**
 * PemetaanAkun findUnique
 */
export type PemetaanAkunFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PemetaanAkun
   */
  select?: Prisma.PemetaanAkunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PemetaanAkun
   */
  omit?: Prisma.PemetaanAkunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PemetaanAkunInclude<ExtArgs> | null
  /**
   * Filter, which PemetaanAkun to fetch.
   */
  where: Prisma.PemetaanAkunWhereUniqueInput
}

/**
 * PemetaanAkun findUniqueOrThrow
 */
export type PemetaanAkunFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PemetaanAkun
   */
  select?: Prisma.PemetaanAkunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PemetaanAkun
   */
  omit?: Prisma.PemetaanAkunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PemetaanAkunInclude<ExtArgs> | null
  /**
   * Filter, which PemetaanAkun to fetch.
   */
  where: Prisma.PemetaanAkunWhereUniqueInput
}

/**
 * PemetaanAkun findFirst
 */
export type PemetaanAkunFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PemetaanAkun
   */
  select?: Prisma.PemetaanAkunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PemetaanAkun
   */
  omit?: Prisma.PemetaanAkunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PemetaanAkunInclude<ExtArgs> | null
  /**
   * Filter, which PemetaanAkun to fetch.
   */
  where?: Prisma.PemetaanAkunWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PemetaanAkuns to fetch.
   */
  orderBy?: Prisma.PemetaanAkunOrderByWithRelationInput | Prisma.PemetaanAkunOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PemetaanAkuns.
   */
  cursor?: Prisma.PemetaanAkunWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PemetaanAkuns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PemetaanAkuns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PemetaanAkuns.
   */
  distinct?: Prisma.PemetaanAkunScalarFieldEnum | Prisma.PemetaanAkunScalarFieldEnum[]
}

/**
 * PemetaanAkun findFirstOrThrow
 */
export type PemetaanAkunFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PemetaanAkun
   */
  select?: Prisma.PemetaanAkunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PemetaanAkun
   */
  omit?: Prisma.PemetaanAkunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PemetaanAkunInclude<ExtArgs> | null
  /**
   * Filter, which PemetaanAkun to fetch.
   */
  where?: Prisma.PemetaanAkunWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PemetaanAkuns to fetch.
   */
  orderBy?: Prisma.PemetaanAkunOrderByWithRelationInput | Prisma.PemetaanAkunOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PemetaanAkuns.
   */
  cursor?: Prisma.PemetaanAkunWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PemetaanAkuns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PemetaanAkuns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PemetaanAkuns.
   */
  distinct?: Prisma.PemetaanAkunScalarFieldEnum | Prisma.PemetaanAkunScalarFieldEnum[]
}

/**
 * PemetaanAkun findMany
 */
export type PemetaanAkunFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PemetaanAkun
   */
  select?: Prisma.PemetaanAkunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PemetaanAkun
   */
  omit?: Prisma.PemetaanAkunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PemetaanAkunInclude<ExtArgs> | null
  /**
   * Filter, which PemetaanAkuns to fetch.
   */
  where?: Prisma.PemetaanAkunWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PemetaanAkuns to fetch.
   */
  orderBy?: Prisma.PemetaanAkunOrderByWithRelationInput | Prisma.PemetaanAkunOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PemetaanAkuns.
   */
  cursor?: Prisma.PemetaanAkunWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PemetaanAkuns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PemetaanAkuns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PemetaanAkuns.
   */
  distinct?: Prisma.PemetaanAkunScalarFieldEnum | Prisma.PemetaanAkunScalarFieldEnum[]
}

/**
 * PemetaanAkun create
 */
export type PemetaanAkunCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PemetaanAkun
   */
  select?: Prisma.PemetaanAkunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PemetaanAkun
   */
  omit?: Prisma.PemetaanAkunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PemetaanAkunInclude<ExtArgs> | null
  /**
   * The data needed to create a PemetaanAkun.
   */
  data: Prisma.XOR<Prisma.PemetaanAkunCreateInput, Prisma.PemetaanAkunUncheckedCreateInput>
}

/**
 * PemetaanAkun createMany
 */
export type PemetaanAkunCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PemetaanAkuns.
   */
  data: Prisma.PemetaanAkunCreateManyInput | Prisma.PemetaanAkunCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PemetaanAkun createManyAndReturn
 */
export type PemetaanAkunCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PemetaanAkun
   */
  select?: Prisma.PemetaanAkunSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PemetaanAkun
   */
  omit?: Prisma.PemetaanAkunOmit<ExtArgs> | null
  /**
   * The data used to create many PemetaanAkuns.
   */
  data: Prisma.PemetaanAkunCreateManyInput | Prisma.PemetaanAkunCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PemetaanAkunIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PemetaanAkun update
 */
export type PemetaanAkunUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PemetaanAkun
   */
  select?: Prisma.PemetaanAkunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PemetaanAkun
   */
  omit?: Prisma.PemetaanAkunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PemetaanAkunInclude<ExtArgs> | null
  /**
   * The data needed to update a PemetaanAkun.
   */
  data: Prisma.XOR<Prisma.PemetaanAkunUpdateInput, Prisma.PemetaanAkunUncheckedUpdateInput>
  /**
   * Choose, which PemetaanAkun to update.
   */
  where: Prisma.PemetaanAkunWhereUniqueInput
}

/**
 * PemetaanAkun updateMany
 */
export type PemetaanAkunUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PemetaanAkuns.
   */
  data: Prisma.XOR<Prisma.PemetaanAkunUpdateManyMutationInput, Prisma.PemetaanAkunUncheckedUpdateManyInput>
  /**
   * Filter which PemetaanAkuns to update
   */
  where?: Prisma.PemetaanAkunWhereInput
  /**
   * Limit how many PemetaanAkuns to update.
   */
  limit?: number
}

/**
 * PemetaanAkun updateManyAndReturn
 */
export type PemetaanAkunUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PemetaanAkun
   */
  select?: Prisma.PemetaanAkunSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PemetaanAkun
   */
  omit?: Prisma.PemetaanAkunOmit<ExtArgs> | null
  /**
   * The data used to update PemetaanAkuns.
   */
  data: Prisma.XOR<Prisma.PemetaanAkunUpdateManyMutationInput, Prisma.PemetaanAkunUncheckedUpdateManyInput>
  /**
   * Filter which PemetaanAkuns to update
   */
  where?: Prisma.PemetaanAkunWhereInput
  /**
   * Limit how many PemetaanAkuns to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PemetaanAkunIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PemetaanAkun upsert
 */
export type PemetaanAkunUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PemetaanAkun
   */
  select?: Prisma.PemetaanAkunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PemetaanAkun
   */
  omit?: Prisma.PemetaanAkunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PemetaanAkunInclude<ExtArgs> | null
  /**
   * The filter to search for the PemetaanAkun to update in case it exists.
   */
  where: Prisma.PemetaanAkunWhereUniqueInput
  /**
   * In case the PemetaanAkun found by the `where` argument doesn't exist, create a new PemetaanAkun with this data.
   */
  create: Prisma.XOR<Prisma.PemetaanAkunCreateInput, Prisma.PemetaanAkunUncheckedCreateInput>
  /**
   * In case the PemetaanAkun was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PemetaanAkunUpdateInput, Prisma.PemetaanAkunUncheckedUpdateInput>
}

/**
 * PemetaanAkun delete
 */
export type PemetaanAkunDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PemetaanAkun
   */
  select?: Prisma.PemetaanAkunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PemetaanAkun
   */
  omit?: Prisma.PemetaanAkunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PemetaanAkunInclude<ExtArgs> | null
  /**
   * Filter which PemetaanAkun to delete.
   */
  where: Prisma.PemetaanAkunWhereUniqueInput
}

/**
 * PemetaanAkun deleteMany
 */
export type PemetaanAkunDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PemetaanAkuns to delete
   */
  where?: Prisma.PemetaanAkunWhereInput
  /**
   * Limit how many PemetaanAkuns to delete.
   */
  limit?: number
}

/**
 * PemetaanAkun.bebanJasa
 */
export type PemetaanAkun$bebanJasaArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Akun
   */
  select?: Prisma.AkunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Akun
   */
  omit?: Prisma.AkunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AkunInclude<ExtArgs> | null
  where?: Prisma.AkunWhereInput
}

/**
 * PemetaanAkun.barangBelumDitagih
 */
export type PemetaanAkun$barangBelumDitagihArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Akun
   */
  select?: Prisma.AkunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Akun
   */
  omit?: Prisma.AkunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AkunInclude<ExtArgs> | null
  where?: Prisma.AkunWhereInput
}

/**
 * PemetaanAkun.selisihPersediaan
 */
export type PemetaanAkun$selisihPersediaanArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Akun
   */
  select?: Prisma.AkunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Akun
   */
  omit?: Prisma.AkunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AkunInclude<ExtArgs> | null
  where?: Prisma.AkunWhereInput
}

/**
 * PemetaanAkun without action
 */
export type PemetaanAkunDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PemetaanAkun
   */
  select?: Prisma.PemetaanAkunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PemetaanAkun
   */
  omit?: Prisma.PemetaanAkunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PemetaanAkunInclude<ExtArgs> | null
}
