
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PermintaanAturUlang` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PermintaanAturUlang
 * Permintaan "lupa kata sandi" dari halaman masuk; ditangani Superadmin/Pemilik/Admin dengan tautan sekali pakai
 */
export type PermintaanAturUlangModel = runtime.Types.Result.DefaultSelection<Prisma.$PermintaanAturUlangPayload>

export type AggregatePermintaanAturUlang = {
  _count: PermintaanAturUlangCountAggregateOutputType | null
  _min: PermintaanAturUlangMinAggregateOutputType | null
  _max: PermintaanAturUlangMaxAggregateOutputType | null
}

export type PermintaanAturUlangMinAggregateOutputType = {
  id: string | null
  penggunaId: string | null
  dibuatPada: Date | null
  status: string | null
  token: string | null
  kedaluwarsa: Date | null
  ditanganiOleh: string | null
  ditanganiPada: Date | null
  selesaiPada: Date | null
}

export type PermintaanAturUlangMaxAggregateOutputType = {
  id: string | null
  penggunaId: string | null
  dibuatPada: Date | null
  status: string | null
  token: string | null
  kedaluwarsa: Date | null
  ditanganiOleh: string | null
  ditanganiPada: Date | null
  selesaiPada: Date | null
}

export type PermintaanAturUlangCountAggregateOutputType = {
  id: number
  penggunaId: number
  dibuatPada: number
  status: number
  token: number
  kedaluwarsa: number
  ditanganiOleh: number
  ditanganiPada: number
  selesaiPada: number
  _all: number
}


export type PermintaanAturUlangMinAggregateInputType = {
  id?: true
  penggunaId?: true
  dibuatPada?: true
  status?: true
  token?: true
  kedaluwarsa?: true
  ditanganiOleh?: true
  ditanganiPada?: true
  selesaiPada?: true
}

export type PermintaanAturUlangMaxAggregateInputType = {
  id?: true
  penggunaId?: true
  dibuatPada?: true
  status?: true
  token?: true
  kedaluwarsa?: true
  ditanganiOleh?: true
  ditanganiPada?: true
  selesaiPada?: true
}

export type PermintaanAturUlangCountAggregateInputType = {
  id?: true
  penggunaId?: true
  dibuatPada?: true
  status?: true
  token?: true
  kedaluwarsa?: true
  ditanganiOleh?: true
  ditanganiPada?: true
  selesaiPada?: true
  _all?: true
}

export type PermintaanAturUlangAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PermintaanAturUlang to aggregate.
   */
  where?: Prisma.PermintaanAturUlangWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PermintaanAturUlangs to fetch.
   */
  orderBy?: Prisma.PermintaanAturUlangOrderByWithRelationInput | Prisma.PermintaanAturUlangOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PermintaanAturUlangWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PermintaanAturUlangs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PermintaanAturUlangs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PermintaanAturUlangs
  **/
  _count?: true | PermintaanAturUlangCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PermintaanAturUlangMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PermintaanAturUlangMaxAggregateInputType
}

export type GetPermintaanAturUlangAggregateType<T extends PermintaanAturUlangAggregateArgs> = {
      [P in keyof T & keyof AggregatePermintaanAturUlang]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePermintaanAturUlang[P]>
    : Prisma.GetScalarType<T[P], AggregatePermintaanAturUlang[P]>
}




export type PermintaanAturUlangGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PermintaanAturUlangWhereInput
  orderBy?: Prisma.PermintaanAturUlangOrderByWithAggregationInput | Prisma.PermintaanAturUlangOrderByWithAggregationInput[]
  by: Prisma.PermintaanAturUlangScalarFieldEnum[] | Prisma.PermintaanAturUlangScalarFieldEnum
  having?: Prisma.PermintaanAturUlangScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PermintaanAturUlangCountAggregateInputType | true
  _min?: PermintaanAturUlangMinAggregateInputType
  _max?: PermintaanAturUlangMaxAggregateInputType
}

export type PermintaanAturUlangGroupByOutputType = {
  id: string
  penggunaId: string
  dibuatPada: Date
  status: string
  token: string | null
  kedaluwarsa: Date | null
  ditanganiOleh: string | null
  ditanganiPada: Date | null
  selesaiPada: Date | null
  _count: PermintaanAturUlangCountAggregateOutputType | null
  _min: PermintaanAturUlangMinAggregateOutputType | null
  _max: PermintaanAturUlangMaxAggregateOutputType | null
}

export type GetPermintaanAturUlangGroupByPayload<T extends PermintaanAturUlangGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PermintaanAturUlangGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PermintaanAturUlangGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PermintaanAturUlangGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PermintaanAturUlangGroupByOutputType[P]>
      }
    >
  >



export type PermintaanAturUlangWhereInput = {
  AND?: Prisma.PermintaanAturUlangWhereInput | Prisma.PermintaanAturUlangWhereInput[]
  OR?: Prisma.PermintaanAturUlangWhereInput[]
  NOT?: Prisma.PermintaanAturUlangWhereInput | Prisma.PermintaanAturUlangWhereInput[]
  id?: Prisma.StringFilter<"PermintaanAturUlang"> | string
  penggunaId?: Prisma.StringFilter<"PermintaanAturUlang"> | string
  dibuatPada?: Prisma.DateTimeFilter<"PermintaanAturUlang"> | Date | string
  status?: Prisma.StringFilter<"PermintaanAturUlang"> | string
  token?: Prisma.StringNullableFilter<"PermintaanAturUlang"> | string | null
  kedaluwarsa?: Prisma.DateTimeNullableFilter<"PermintaanAturUlang"> | Date | string | null
  ditanganiOleh?: Prisma.StringNullableFilter<"PermintaanAturUlang"> | string | null
  ditanganiPada?: Prisma.DateTimeNullableFilter<"PermintaanAturUlang"> | Date | string | null
  selesaiPada?: Prisma.DateTimeNullableFilter<"PermintaanAturUlang"> | Date | string | null
  pengguna?: Prisma.XOR<Prisma.PenggunaScalarRelationFilter, Prisma.PenggunaWhereInput>
}

export type PermintaanAturUlangOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  penggunaId?: Prisma.SortOrder
  dibuatPada?: Prisma.SortOrder
  status?: Prisma.SortOrder
  token?: Prisma.SortOrderInput | Prisma.SortOrder
  kedaluwarsa?: Prisma.SortOrderInput | Prisma.SortOrder
  ditanganiOleh?: Prisma.SortOrderInput | Prisma.SortOrder
  ditanganiPada?: Prisma.SortOrderInput | Prisma.SortOrder
  selesaiPada?: Prisma.SortOrderInput | Prisma.SortOrder
  pengguna?: Prisma.PenggunaOrderByWithRelationInput
}

export type PermintaanAturUlangWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  token?: string
  AND?: Prisma.PermintaanAturUlangWhereInput | Prisma.PermintaanAturUlangWhereInput[]
  OR?: Prisma.PermintaanAturUlangWhereInput[]
  NOT?: Prisma.PermintaanAturUlangWhereInput | Prisma.PermintaanAturUlangWhereInput[]
  penggunaId?: Prisma.StringFilter<"PermintaanAturUlang"> | string
  dibuatPada?: Prisma.DateTimeFilter<"PermintaanAturUlang"> | Date | string
  status?: Prisma.StringFilter<"PermintaanAturUlang"> | string
  kedaluwarsa?: Prisma.DateTimeNullableFilter<"PermintaanAturUlang"> | Date | string | null
  ditanganiOleh?: Prisma.StringNullableFilter<"PermintaanAturUlang"> | string | null
  ditanganiPada?: Prisma.DateTimeNullableFilter<"PermintaanAturUlang"> | Date | string | null
  selesaiPada?: Prisma.DateTimeNullableFilter<"PermintaanAturUlang"> | Date | string | null
  pengguna?: Prisma.XOR<Prisma.PenggunaScalarRelationFilter, Prisma.PenggunaWhereInput>
}, "id" | "token">

export type PermintaanAturUlangOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  penggunaId?: Prisma.SortOrder
  dibuatPada?: Prisma.SortOrder
  status?: Prisma.SortOrder
  token?: Prisma.SortOrderInput | Prisma.SortOrder
  kedaluwarsa?: Prisma.SortOrderInput | Prisma.SortOrder
  ditanganiOleh?: Prisma.SortOrderInput | Prisma.SortOrder
  ditanganiPada?: Prisma.SortOrderInput | Prisma.SortOrder
  selesaiPada?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.PermintaanAturUlangCountOrderByAggregateInput
  _max?: Prisma.PermintaanAturUlangMaxOrderByAggregateInput
  _min?: Prisma.PermintaanAturUlangMinOrderByAggregateInput
}

export type PermintaanAturUlangScalarWhereWithAggregatesInput = {
  AND?: Prisma.PermintaanAturUlangScalarWhereWithAggregatesInput | Prisma.PermintaanAturUlangScalarWhereWithAggregatesInput[]
  OR?: Prisma.PermintaanAturUlangScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PermintaanAturUlangScalarWhereWithAggregatesInput | Prisma.PermintaanAturUlangScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PermintaanAturUlang"> | string
  penggunaId?: Prisma.StringWithAggregatesFilter<"PermintaanAturUlang"> | string
  dibuatPada?: Prisma.DateTimeWithAggregatesFilter<"PermintaanAturUlang"> | Date | string
  status?: Prisma.StringWithAggregatesFilter<"PermintaanAturUlang"> | string
  token?: Prisma.StringNullableWithAggregatesFilter<"PermintaanAturUlang"> | string | null
  kedaluwarsa?: Prisma.DateTimeNullableWithAggregatesFilter<"PermintaanAturUlang"> | Date | string | null
  ditanganiOleh?: Prisma.StringNullableWithAggregatesFilter<"PermintaanAturUlang"> | string | null
  ditanganiPada?: Prisma.DateTimeNullableWithAggregatesFilter<"PermintaanAturUlang"> | Date | string | null
  selesaiPada?: Prisma.DateTimeNullableWithAggregatesFilter<"PermintaanAturUlang"> | Date | string | null
}

export type PermintaanAturUlangCreateInput = {
  id?: string
  dibuatPada?: Date | string
  status?: string
  token?: string | null
  kedaluwarsa?: Date | string | null
  ditanganiOleh?: string | null
  ditanganiPada?: Date | string | null
  selesaiPada?: Date | string | null
  pengguna: Prisma.PenggunaCreateNestedOneWithoutPermintaanAturUlangInput
}

export type PermintaanAturUlangUncheckedCreateInput = {
  id?: string
  penggunaId: string
  dibuatPada?: Date | string
  status?: string
  token?: string | null
  kedaluwarsa?: Date | string | null
  ditanganiOleh?: string | null
  ditanganiPada?: Date | string | null
  selesaiPada?: Date | string | null
}

export type PermintaanAturUlangUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dibuatPada?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kedaluwarsa?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ditanganiOleh?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ditanganiPada?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  selesaiPada?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  pengguna?: Prisma.PenggunaUpdateOneRequiredWithoutPermintaanAturUlangNestedInput
}

export type PermintaanAturUlangUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  penggunaId?: Prisma.StringFieldUpdateOperationsInput | string
  dibuatPada?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kedaluwarsa?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ditanganiOleh?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ditanganiPada?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  selesaiPada?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type PermintaanAturUlangCreateManyInput = {
  id?: string
  penggunaId: string
  dibuatPada?: Date | string
  status?: string
  token?: string | null
  kedaluwarsa?: Date | string | null
  ditanganiOleh?: string | null
  ditanganiPada?: Date | string | null
  selesaiPada?: Date | string | null
}

export type PermintaanAturUlangUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dibuatPada?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kedaluwarsa?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ditanganiOleh?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ditanganiPada?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  selesaiPada?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type PermintaanAturUlangUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  penggunaId?: Prisma.StringFieldUpdateOperationsInput | string
  dibuatPada?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kedaluwarsa?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ditanganiOleh?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ditanganiPada?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  selesaiPada?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type PermintaanAturUlangListRelationFilter = {
  every?: Prisma.PermintaanAturUlangWhereInput
  some?: Prisma.PermintaanAturUlangWhereInput
  none?: Prisma.PermintaanAturUlangWhereInput
}

export type PermintaanAturUlangOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PermintaanAturUlangCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  penggunaId?: Prisma.SortOrder
  dibuatPada?: Prisma.SortOrder
  status?: Prisma.SortOrder
  token?: Prisma.SortOrder
  kedaluwarsa?: Prisma.SortOrder
  ditanganiOleh?: Prisma.SortOrder
  ditanganiPada?: Prisma.SortOrder
  selesaiPada?: Prisma.SortOrder
}

export type PermintaanAturUlangMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  penggunaId?: Prisma.SortOrder
  dibuatPada?: Prisma.SortOrder
  status?: Prisma.SortOrder
  token?: Prisma.SortOrder
  kedaluwarsa?: Prisma.SortOrder
  ditanganiOleh?: Prisma.SortOrder
  ditanganiPada?: Prisma.SortOrder
  selesaiPada?: Prisma.SortOrder
}

export type PermintaanAturUlangMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  penggunaId?: Prisma.SortOrder
  dibuatPada?: Prisma.SortOrder
  status?: Prisma.SortOrder
  token?: Prisma.SortOrder
  kedaluwarsa?: Prisma.SortOrder
  ditanganiOleh?: Prisma.SortOrder
  ditanganiPada?: Prisma.SortOrder
  selesaiPada?: Prisma.SortOrder
}

export type PermintaanAturUlangCreateNestedManyWithoutPenggunaInput = {
  create?: Prisma.XOR<Prisma.PermintaanAturUlangCreateWithoutPenggunaInput, Prisma.PermintaanAturUlangUncheckedCreateWithoutPenggunaInput> | Prisma.PermintaanAturUlangCreateWithoutPenggunaInput[] | Prisma.PermintaanAturUlangUncheckedCreateWithoutPenggunaInput[]
  connectOrCreate?: Prisma.PermintaanAturUlangCreateOrConnectWithoutPenggunaInput | Prisma.PermintaanAturUlangCreateOrConnectWithoutPenggunaInput[]
  createMany?: Prisma.PermintaanAturUlangCreateManyPenggunaInputEnvelope
  connect?: Prisma.PermintaanAturUlangWhereUniqueInput | Prisma.PermintaanAturUlangWhereUniqueInput[]
}

export type PermintaanAturUlangUncheckedCreateNestedManyWithoutPenggunaInput = {
  create?: Prisma.XOR<Prisma.PermintaanAturUlangCreateWithoutPenggunaInput, Prisma.PermintaanAturUlangUncheckedCreateWithoutPenggunaInput> | Prisma.PermintaanAturUlangCreateWithoutPenggunaInput[] | Prisma.PermintaanAturUlangUncheckedCreateWithoutPenggunaInput[]
  connectOrCreate?: Prisma.PermintaanAturUlangCreateOrConnectWithoutPenggunaInput | Prisma.PermintaanAturUlangCreateOrConnectWithoutPenggunaInput[]
  createMany?: Prisma.PermintaanAturUlangCreateManyPenggunaInputEnvelope
  connect?: Prisma.PermintaanAturUlangWhereUniqueInput | Prisma.PermintaanAturUlangWhereUniqueInput[]
}

export type PermintaanAturUlangUpdateManyWithoutPenggunaNestedInput = {
  create?: Prisma.XOR<Prisma.PermintaanAturUlangCreateWithoutPenggunaInput, Prisma.PermintaanAturUlangUncheckedCreateWithoutPenggunaInput> | Prisma.PermintaanAturUlangCreateWithoutPenggunaInput[] | Prisma.PermintaanAturUlangUncheckedCreateWithoutPenggunaInput[]
  connectOrCreate?: Prisma.PermintaanAturUlangCreateOrConnectWithoutPenggunaInput | Prisma.PermintaanAturUlangCreateOrConnectWithoutPenggunaInput[]
  upsert?: Prisma.PermintaanAturUlangUpsertWithWhereUniqueWithoutPenggunaInput | Prisma.PermintaanAturUlangUpsertWithWhereUniqueWithoutPenggunaInput[]
  createMany?: Prisma.PermintaanAturUlangCreateManyPenggunaInputEnvelope
  set?: Prisma.PermintaanAturUlangWhereUniqueInput | Prisma.PermintaanAturUlangWhereUniqueInput[]
  disconnect?: Prisma.PermintaanAturUlangWhereUniqueInput | Prisma.PermintaanAturUlangWhereUniqueInput[]
  delete?: Prisma.PermintaanAturUlangWhereUniqueInput | Prisma.PermintaanAturUlangWhereUniqueInput[]
  connect?: Prisma.PermintaanAturUlangWhereUniqueInput | Prisma.PermintaanAturUlangWhereUniqueInput[]
  update?: Prisma.PermintaanAturUlangUpdateWithWhereUniqueWithoutPenggunaInput | Prisma.PermintaanAturUlangUpdateWithWhereUniqueWithoutPenggunaInput[]
  updateMany?: Prisma.PermintaanAturUlangUpdateManyWithWhereWithoutPenggunaInput | Prisma.PermintaanAturUlangUpdateManyWithWhereWithoutPenggunaInput[]
  deleteMany?: Prisma.PermintaanAturUlangScalarWhereInput | Prisma.PermintaanAturUlangScalarWhereInput[]
}

export type PermintaanAturUlangUncheckedUpdateManyWithoutPenggunaNestedInput = {
  create?: Prisma.XOR<Prisma.PermintaanAturUlangCreateWithoutPenggunaInput, Prisma.PermintaanAturUlangUncheckedCreateWithoutPenggunaInput> | Prisma.PermintaanAturUlangCreateWithoutPenggunaInput[] | Prisma.PermintaanAturUlangUncheckedCreateWithoutPenggunaInput[]
  connectOrCreate?: Prisma.PermintaanAturUlangCreateOrConnectWithoutPenggunaInput | Prisma.PermintaanAturUlangCreateOrConnectWithoutPenggunaInput[]
  upsert?: Prisma.PermintaanAturUlangUpsertWithWhereUniqueWithoutPenggunaInput | Prisma.PermintaanAturUlangUpsertWithWhereUniqueWithoutPenggunaInput[]
  createMany?: Prisma.PermintaanAturUlangCreateManyPenggunaInputEnvelope
  set?: Prisma.PermintaanAturUlangWhereUniqueInput | Prisma.PermintaanAturUlangWhereUniqueInput[]
  disconnect?: Prisma.PermintaanAturUlangWhereUniqueInput | Prisma.PermintaanAturUlangWhereUniqueInput[]
  delete?: Prisma.PermintaanAturUlangWhereUniqueInput | Prisma.PermintaanAturUlangWhereUniqueInput[]
  connect?: Prisma.PermintaanAturUlangWhereUniqueInput | Prisma.PermintaanAturUlangWhereUniqueInput[]
  update?: Prisma.PermintaanAturUlangUpdateWithWhereUniqueWithoutPenggunaInput | Prisma.PermintaanAturUlangUpdateWithWhereUniqueWithoutPenggunaInput[]
  updateMany?: Prisma.PermintaanAturUlangUpdateManyWithWhereWithoutPenggunaInput | Prisma.PermintaanAturUlangUpdateManyWithWhereWithoutPenggunaInput[]
  deleteMany?: Prisma.PermintaanAturUlangScalarWhereInput | Prisma.PermintaanAturUlangScalarWhereInput[]
}

export type PermintaanAturUlangCreateWithoutPenggunaInput = {
  id?: string
  dibuatPada?: Date | string
  status?: string
  token?: string | null
  kedaluwarsa?: Date | string | null
  ditanganiOleh?: string | null
  ditanganiPada?: Date | string | null
  selesaiPada?: Date | string | null
}

export type PermintaanAturUlangUncheckedCreateWithoutPenggunaInput = {
  id?: string
  dibuatPada?: Date | string
  status?: string
  token?: string | null
  kedaluwarsa?: Date | string | null
  ditanganiOleh?: string | null
  ditanganiPada?: Date | string | null
  selesaiPada?: Date | string | null
}

export type PermintaanAturUlangCreateOrConnectWithoutPenggunaInput = {
  where: Prisma.PermintaanAturUlangWhereUniqueInput
  create: Prisma.XOR<Prisma.PermintaanAturUlangCreateWithoutPenggunaInput, Prisma.PermintaanAturUlangUncheckedCreateWithoutPenggunaInput>
}

export type PermintaanAturUlangCreateManyPenggunaInputEnvelope = {
  data: Prisma.PermintaanAturUlangCreateManyPenggunaInput | Prisma.PermintaanAturUlangCreateManyPenggunaInput[]
  skipDuplicates?: boolean
}

export type PermintaanAturUlangUpsertWithWhereUniqueWithoutPenggunaInput = {
  where: Prisma.PermintaanAturUlangWhereUniqueInput
  update: Prisma.XOR<Prisma.PermintaanAturUlangUpdateWithoutPenggunaInput, Prisma.PermintaanAturUlangUncheckedUpdateWithoutPenggunaInput>
  create: Prisma.XOR<Prisma.PermintaanAturUlangCreateWithoutPenggunaInput, Prisma.PermintaanAturUlangUncheckedCreateWithoutPenggunaInput>
}

export type PermintaanAturUlangUpdateWithWhereUniqueWithoutPenggunaInput = {
  where: Prisma.PermintaanAturUlangWhereUniqueInput
  data: Prisma.XOR<Prisma.PermintaanAturUlangUpdateWithoutPenggunaInput, Prisma.PermintaanAturUlangUncheckedUpdateWithoutPenggunaInput>
}

export type PermintaanAturUlangUpdateManyWithWhereWithoutPenggunaInput = {
  where: Prisma.PermintaanAturUlangScalarWhereInput
  data: Prisma.XOR<Prisma.PermintaanAturUlangUpdateManyMutationInput, Prisma.PermintaanAturUlangUncheckedUpdateManyWithoutPenggunaInput>
}

export type PermintaanAturUlangScalarWhereInput = {
  AND?: Prisma.PermintaanAturUlangScalarWhereInput | Prisma.PermintaanAturUlangScalarWhereInput[]
  OR?: Prisma.PermintaanAturUlangScalarWhereInput[]
  NOT?: Prisma.PermintaanAturUlangScalarWhereInput | Prisma.PermintaanAturUlangScalarWhereInput[]
  id?: Prisma.StringFilter<"PermintaanAturUlang"> | string
  penggunaId?: Prisma.StringFilter<"PermintaanAturUlang"> | string
  dibuatPada?: Prisma.DateTimeFilter<"PermintaanAturUlang"> | Date | string
  status?: Prisma.StringFilter<"PermintaanAturUlang"> | string
  token?: Prisma.StringNullableFilter<"PermintaanAturUlang"> | string | null
  kedaluwarsa?: Prisma.DateTimeNullableFilter<"PermintaanAturUlang"> | Date | string | null
  ditanganiOleh?: Prisma.StringNullableFilter<"PermintaanAturUlang"> | string | null
  ditanganiPada?: Prisma.DateTimeNullableFilter<"PermintaanAturUlang"> | Date | string | null
  selesaiPada?: Prisma.DateTimeNullableFilter<"PermintaanAturUlang"> | Date | string | null
}

export type PermintaanAturUlangCreateManyPenggunaInput = {
  id?: string
  dibuatPada?: Date | string
  status?: string
  token?: string | null
  kedaluwarsa?: Date | string | null
  ditanganiOleh?: string | null
  ditanganiPada?: Date | string | null
  selesaiPada?: Date | string | null
}

export type PermintaanAturUlangUpdateWithoutPenggunaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dibuatPada?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kedaluwarsa?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ditanganiOleh?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ditanganiPada?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  selesaiPada?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type PermintaanAturUlangUncheckedUpdateWithoutPenggunaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dibuatPada?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kedaluwarsa?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ditanganiOleh?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ditanganiPada?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  selesaiPada?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type PermintaanAturUlangUncheckedUpdateManyWithoutPenggunaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dibuatPada?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kedaluwarsa?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ditanganiOleh?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ditanganiPada?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  selesaiPada?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type PermintaanAturUlangSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  penggunaId?: boolean
  dibuatPada?: boolean
  status?: boolean
  token?: boolean
  kedaluwarsa?: boolean
  ditanganiOleh?: boolean
  ditanganiPada?: boolean
  selesaiPada?: boolean
  pengguna?: boolean | Prisma.PenggunaDefaultArgs<ExtArgs>
}, ExtArgs["result"]["permintaanAturUlang"]>

export type PermintaanAturUlangSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  penggunaId?: boolean
  dibuatPada?: boolean
  status?: boolean
  token?: boolean
  kedaluwarsa?: boolean
  ditanganiOleh?: boolean
  ditanganiPada?: boolean
  selesaiPada?: boolean
  pengguna?: boolean | Prisma.PenggunaDefaultArgs<ExtArgs>
}, ExtArgs["result"]["permintaanAturUlang"]>

export type PermintaanAturUlangSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  penggunaId?: boolean
  dibuatPada?: boolean
  status?: boolean
  token?: boolean
  kedaluwarsa?: boolean
  ditanganiOleh?: boolean
  ditanganiPada?: boolean
  selesaiPada?: boolean
  pengguna?: boolean | Prisma.PenggunaDefaultArgs<ExtArgs>
}, ExtArgs["result"]["permintaanAturUlang"]>

export type PermintaanAturUlangSelectScalar = {
  id?: boolean
  penggunaId?: boolean
  dibuatPada?: boolean
  status?: boolean
  token?: boolean
  kedaluwarsa?: boolean
  ditanganiOleh?: boolean
  ditanganiPada?: boolean
  selesaiPada?: boolean
}

export type PermintaanAturUlangOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "penggunaId" | "dibuatPada" | "status" | "token" | "kedaluwarsa" | "ditanganiOleh" | "ditanganiPada" | "selesaiPada", ExtArgs["result"]["permintaanAturUlang"]>
export type PermintaanAturUlangInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pengguna?: boolean | Prisma.PenggunaDefaultArgs<ExtArgs>
}
export type PermintaanAturUlangIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pengguna?: boolean | Prisma.PenggunaDefaultArgs<ExtArgs>
}
export type PermintaanAturUlangIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pengguna?: boolean | Prisma.PenggunaDefaultArgs<ExtArgs>
}

export type $PermintaanAturUlangPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PermintaanAturUlang"
  objects: {
    pengguna: Prisma.$PenggunaPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    penggunaId: string
    dibuatPada: Date
    /**
     * MENUNGGU → TAUTAN (tautan dibuat) → SELESAI (kata sandi diganti) | DITOLAK
     */
    status: string
    /**
     * Token tautan sekali pakai (/atur-ulang/<token>), berlaku sampai `kedaluwarsa`
     */
    token: string | null
    kedaluwarsa: Date | null
    ditanganiOleh: string | null
    ditanganiPada: Date | null
    selesaiPada: Date | null
  }, ExtArgs["result"]["permintaanAturUlang"]>
  composites: {}
}

export type PermintaanAturUlangGetPayload<S extends boolean | null | undefined | PermintaanAturUlangDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PermintaanAturUlangPayload, S>

export type PermintaanAturUlangCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PermintaanAturUlangFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PermintaanAturUlangCountAggregateInputType | true
  }

export interface PermintaanAturUlangDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PermintaanAturUlang'], meta: { name: 'PermintaanAturUlang' } }
  /**
   * Find zero or one PermintaanAturUlang that matches the filter.
   * @param {PermintaanAturUlangFindUniqueArgs} args - Arguments to find a PermintaanAturUlang
   * @example
   * // Get one PermintaanAturUlang
   * const permintaanAturUlang = await prisma.permintaanAturUlang.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PermintaanAturUlangFindUniqueArgs>(args: Prisma.SelectSubset<T, PermintaanAturUlangFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PermintaanAturUlangClient<runtime.Types.Result.GetResult<Prisma.$PermintaanAturUlangPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PermintaanAturUlang that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PermintaanAturUlangFindUniqueOrThrowArgs} args - Arguments to find a PermintaanAturUlang
   * @example
   * // Get one PermintaanAturUlang
   * const permintaanAturUlang = await prisma.permintaanAturUlang.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PermintaanAturUlangFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PermintaanAturUlangFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PermintaanAturUlangClient<runtime.Types.Result.GetResult<Prisma.$PermintaanAturUlangPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PermintaanAturUlang that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PermintaanAturUlangFindFirstArgs} args - Arguments to find a PermintaanAturUlang
   * @example
   * // Get one PermintaanAturUlang
   * const permintaanAturUlang = await prisma.permintaanAturUlang.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PermintaanAturUlangFindFirstArgs>(args?: Prisma.SelectSubset<T, PermintaanAturUlangFindFirstArgs<ExtArgs>>): Prisma.Prisma__PermintaanAturUlangClient<runtime.Types.Result.GetResult<Prisma.$PermintaanAturUlangPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PermintaanAturUlang that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PermintaanAturUlangFindFirstOrThrowArgs} args - Arguments to find a PermintaanAturUlang
   * @example
   * // Get one PermintaanAturUlang
   * const permintaanAturUlang = await prisma.permintaanAturUlang.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PermintaanAturUlangFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PermintaanAturUlangFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PermintaanAturUlangClient<runtime.Types.Result.GetResult<Prisma.$PermintaanAturUlangPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PermintaanAturUlangs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PermintaanAturUlangFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PermintaanAturUlangs
   * const permintaanAturUlangs = await prisma.permintaanAturUlang.findMany()
   * 
   * // Get first 10 PermintaanAturUlangs
   * const permintaanAturUlangs = await prisma.permintaanAturUlang.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const permintaanAturUlangWithIdOnly = await prisma.permintaanAturUlang.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PermintaanAturUlangFindManyArgs>(args?: Prisma.SelectSubset<T, PermintaanAturUlangFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PermintaanAturUlangPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PermintaanAturUlang.
   * @param {PermintaanAturUlangCreateArgs} args - Arguments to create a PermintaanAturUlang.
   * @example
   * // Create one PermintaanAturUlang
   * const PermintaanAturUlang = await prisma.permintaanAturUlang.create({
   *   data: {
   *     // ... data to create a PermintaanAturUlang
   *   }
   * })
   * 
   */
  create<T extends PermintaanAturUlangCreateArgs>(args: Prisma.SelectSubset<T, PermintaanAturUlangCreateArgs<ExtArgs>>): Prisma.Prisma__PermintaanAturUlangClient<runtime.Types.Result.GetResult<Prisma.$PermintaanAturUlangPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PermintaanAturUlangs.
   * @param {PermintaanAturUlangCreateManyArgs} args - Arguments to create many PermintaanAturUlangs.
   * @example
   * // Create many PermintaanAturUlangs
   * const permintaanAturUlang = await prisma.permintaanAturUlang.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PermintaanAturUlangCreateManyArgs>(args?: Prisma.SelectSubset<T, PermintaanAturUlangCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PermintaanAturUlangs and returns the data saved in the database.
   * @param {PermintaanAturUlangCreateManyAndReturnArgs} args - Arguments to create many PermintaanAturUlangs.
   * @example
   * // Create many PermintaanAturUlangs
   * const permintaanAturUlang = await prisma.permintaanAturUlang.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PermintaanAturUlangs and only return the `id`
   * const permintaanAturUlangWithIdOnly = await prisma.permintaanAturUlang.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PermintaanAturUlangCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PermintaanAturUlangCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PermintaanAturUlangPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PermintaanAturUlang.
   * @param {PermintaanAturUlangDeleteArgs} args - Arguments to delete one PermintaanAturUlang.
   * @example
   * // Delete one PermintaanAturUlang
   * const PermintaanAturUlang = await prisma.permintaanAturUlang.delete({
   *   where: {
   *     // ... filter to delete one PermintaanAturUlang
   *   }
   * })
   * 
   */
  delete<T extends PermintaanAturUlangDeleteArgs>(args: Prisma.SelectSubset<T, PermintaanAturUlangDeleteArgs<ExtArgs>>): Prisma.Prisma__PermintaanAturUlangClient<runtime.Types.Result.GetResult<Prisma.$PermintaanAturUlangPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PermintaanAturUlang.
   * @param {PermintaanAturUlangUpdateArgs} args - Arguments to update one PermintaanAturUlang.
   * @example
   * // Update one PermintaanAturUlang
   * const permintaanAturUlang = await prisma.permintaanAturUlang.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PermintaanAturUlangUpdateArgs>(args: Prisma.SelectSubset<T, PermintaanAturUlangUpdateArgs<ExtArgs>>): Prisma.Prisma__PermintaanAturUlangClient<runtime.Types.Result.GetResult<Prisma.$PermintaanAturUlangPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PermintaanAturUlangs.
   * @param {PermintaanAturUlangDeleteManyArgs} args - Arguments to filter PermintaanAturUlangs to delete.
   * @example
   * // Delete a few PermintaanAturUlangs
   * const { count } = await prisma.permintaanAturUlang.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PermintaanAturUlangDeleteManyArgs>(args?: Prisma.SelectSubset<T, PermintaanAturUlangDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PermintaanAturUlangs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PermintaanAturUlangUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PermintaanAturUlangs
   * const permintaanAturUlang = await prisma.permintaanAturUlang.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PermintaanAturUlangUpdateManyArgs>(args: Prisma.SelectSubset<T, PermintaanAturUlangUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PermintaanAturUlangs and returns the data updated in the database.
   * @param {PermintaanAturUlangUpdateManyAndReturnArgs} args - Arguments to update many PermintaanAturUlangs.
   * @example
   * // Update many PermintaanAturUlangs
   * const permintaanAturUlang = await prisma.permintaanAturUlang.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PermintaanAturUlangs and only return the `id`
   * const permintaanAturUlangWithIdOnly = await prisma.permintaanAturUlang.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PermintaanAturUlangUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PermintaanAturUlangUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PermintaanAturUlangPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PermintaanAturUlang.
   * @param {PermintaanAturUlangUpsertArgs} args - Arguments to update or create a PermintaanAturUlang.
   * @example
   * // Update or create a PermintaanAturUlang
   * const permintaanAturUlang = await prisma.permintaanAturUlang.upsert({
   *   create: {
   *     // ... data to create a PermintaanAturUlang
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PermintaanAturUlang we want to update
   *   }
   * })
   */
  upsert<T extends PermintaanAturUlangUpsertArgs>(args: Prisma.SelectSubset<T, PermintaanAturUlangUpsertArgs<ExtArgs>>): Prisma.Prisma__PermintaanAturUlangClient<runtime.Types.Result.GetResult<Prisma.$PermintaanAturUlangPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PermintaanAturUlangs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PermintaanAturUlangCountArgs} args - Arguments to filter PermintaanAturUlangs to count.
   * @example
   * // Count the number of PermintaanAturUlangs
   * const count = await prisma.permintaanAturUlang.count({
   *   where: {
   *     // ... the filter for the PermintaanAturUlangs we want to count
   *   }
   * })
  **/
  count<T extends PermintaanAturUlangCountArgs>(
    args?: Prisma.Subset<T, PermintaanAturUlangCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PermintaanAturUlangCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PermintaanAturUlang.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PermintaanAturUlangAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PermintaanAturUlangAggregateArgs>(args: Prisma.Subset<T, PermintaanAturUlangAggregateArgs>): Prisma.PrismaPromise<GetPermintaanAturUlangAggregateType<T>>

  /**
   * Group by PermintaanAturUlang.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PermintaanAturUlangGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PermintaanAturUlangGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PermintaanAturUlangGroupByArgs['orderBy'] }
      : { orderBy?: PermintaanAturUlangGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PermintaanAturUlangGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPermintaanAturUlangGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PermintaanAturUlang model
 */
readonly fields: PermintaanAturUlangFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PermintaanAturUlang.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PermintaanAturUlangClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  pengguna<T extends Prisma.PenggunaDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PenggunaDefaultArgs<ExtArgs>>): Prisma.Prisma__PenggunaClient<runtime.Types.Result.GetResult<Prisma.$PenggunaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PermintaanAturUlang model
 */
export interface PermintaanAturUlangFieldRefs {
  readonly id: Prisma.FieldRef<"PermintaanAturUlang", 'String'>
  readonly penggunaId: Prisma.FieldRef<"PermintaanAturUlang", 'String'>
  readonly dibuatPada: Prisma.FieldRef<"PermintaanAturUlang", 'DateTime'>
  readonly status: Prisma.FieldRef<"PermintaanAturUlang", 'String'>
  readonly token: Prisma.FieldRef<"PermintaanAturUlang", 'String'>
  readonly kedaluwarsa: Prisma.FieldRef<"PermintaanAturUlang", 'DateTime'>
  readonly ditanganiOleh: Prisma.FieldRef<"PermintaanAturUlang", 'String'>
  readonly ditanganiPada: Prisma.FieldRef<"PermintaanAturUlang", 'DateTime'>
  readonly selesaiPada: Prisma.FieldRef<"PermintaanAturUlang", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PermintaanAturUlang findUnique
 */
export type PermintaanAturUlangFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PermintaanAturUlang
   */
  select?: Prisma.PermintaanAturUlangSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PermintaanAturUlang
   */
  omit?: Prisma.PermintaanAturUlangOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PermintaanAturUlangInclude<ExtArgs> | null
  /**
   * Filter, which PermintaanAturUlang to fetch.
   */
  where: Prisma.PermintaanAturUlangWhereUniqueInput
}

/**
 * PermintaanAturUlang findUniqueOrThrow
 */
export type PermintaanAturUlangFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PermintaanAturUlang
   */
  select?: Prisma.PermintaanAturUlangSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PermintaanAturUlang
   */
  omit?: Prisma.PermintaanAturUlangOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PermintaanAturUlangInclude<ExtArgs> | null
  /**
   * Filter, which PermintaanAturUlang to fetch.
   */
  where: Prisma.PermintaanAturUlangWhereUniqueInput
}

/**
 * PermintaanAturUlang findFirst
 */
export type PermintaanAturUlangFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PermintaanAturUlang
   */
  select?: Prisma.PermintaanAturUlangSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PermintaanAturUlang
   */
  omit?: Prisma.PermintaanAturUlangOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PermintaanAturUlangInclude<ExtArgs> | null
  /**
   * Filter, which PermintaanAturUlang to fetch.
   */
  where?: Prisma.PermintaanAturUlangWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PermintaanAturUlangs to fetch.
   */
  orderBy?: Prisma.PermintaanAturUlangOrderByWithRelationInput | Prisma.PermintaanAturUlangOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PermintaanAturUlangs.
   */
  cursor?: Prisma.PermintaanAturUlangWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PermintaanAturUlangs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PermintaanAturUlangs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PermintaanAturUlangs.
   */
  distinct?: Prisma.PermintaanAturUlangScalarFieldEnum | Prisma.PermintaanAturUlangScalarFieldEnum[]
}

/**
 * PermintaanAturUlang findFirstOrThrow
 */
export type PermintaanAturUlangFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PermintaanAturUlang
   */
  select?: Prisma.PermintaanAturUlangSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PermintaanAturUlang
   */
  omit?: Prisma.PermintaanAturUlangOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PermintaanAturUlangInclude<ExtArgs> | null
  /**
   * Filter, which PermintaanAturUlang to fetch.
   */
  where?: Prisma.PermintaanAturUlangWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PermintaanAturUlangs to fetch.
   */
  orderBy?: Prisma.PermintaanAturUlangOrderByWithRelationInput | Prisma.PermintaanAturUlangOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PermintaanAturUlangs.
   */
  cursor?: Prisma.PermintaanAturUlangWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PermintaanAturUlangs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PermintaanAturUlangs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PermintaanAturUlangs.
   */
  distinct?: Prisma.PermintaanAturUlangScalarFieldEnum | Prisma.PermintaanAturUlangScalarFieldEnum[]
}

/**
 * PermintaanAturUlang findMany
 */
export type PermintaanAturUlangFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PermintaanAturUlang
   */
  select?: Prisma.PermintaanAturUlangSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PermintaanAturUlang
   */
  omit?: Prisma.PermintaanAturUlangOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PermintaanAturUlangInclude<ExtArgs> | null
  /**
   * Filter, which PermintaanAturUlangs to fetch.
   */
  where?: Prisma.PermintaanAturUlangWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PermintaanAturUlangs to fetch.
   */
  orderBy?: Prisma.PermintaanAturUlangOrderByWithRelationInput | Prisma.PermintaanAturUlangOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PermintaanAturUlangs.
   */
  cursor?: Prisma.PermintaanAturUlangWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PermintaanAturUlangs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PermintaanAturUlangs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PermintaanAturUlangs.
   */
  distinct?: Prisma.PermintaanAturUlangScalarFieldEnum | Prisma.PermintaanAturUlangScalarFieldEnum[]
}

/**
 * PermintaanAturUlang create
 */
export type PermintaanAturUlangCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PermintaanAturUlang
   */
  select?: Prisma.PermintaanAturUlangSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PermintaanAturUlang
   */
  omit?: Prisma.PermintaanAturUlangOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PermintaanAturUlangInclude<ExtArgs> | null
  /**
   * The data needed to create a PermintaanAturUlang.
   */
  data: Prisma.XOR<Prisma.PermintaanAturUlangCreateInput, Prisma.PermintaanAturUlangUncheckedCreateInput>
}

/**
 * PermintaanAturUlang createMany
 */
export type PermintaanAturUlangCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PermintaanAturUlangs.
   */
  data: Prisma.PermintaanAturUlangCreateManyInput | Prisma.PermintaanAturUlangCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PermintaanAturUlang createManyAndReturn
 */
export type PermintaanAturUlangCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PermintaanAturUlang
   */
  select?: Prisma.PermintaanAturUlangSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PermintaanAturUlang
   */
  omit?: Prisma.PermintaanAturUlangOmit<ExtArgs> | null
  /**
   * The data used to create many PermintaanAturUlangs.
   */
  data: Prisma.PermintaanAturUlangCreateManyInput | Prisma.PermintaanAturUlangCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PermintaanAturUlangIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PermintaanAturUlang update
 */
export type PermintaanAturUlangUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PermintaanAturUlang
   */
  select?: Prisma.PermintaanAturUlangSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PermintaanAturUlang
   */
  omit?: Prisma.PermintaanAturUlangOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PermintaanAturUlangInclude<ExtArgs> | null
  /**
   * The data needed to update a PermintaanAturUlang.
   */
  data: Prisma.XOR<Prisma.PermintaanAturUlangUpdateInput, Prisma.PermintaanAturUlangUncheckedUpdateInput>
  /**
   * Choose, which PermintaanAturUlang to update.
   */
  where: Prisma.PermintaanAturUlangWhereUniqueInput
}

/**
 * PermintaanAturUlang updateMany
 */
export type PermintaanAturUlangUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PermintaanAturUlangs.
   */
  data: Prisma.XOR<Prisma.PermintaanAturUlangUpdateManyMutationInput, Prisma.PermintaanAturUlangUncheckedUpdateManyInput>
  /**
   * Filter which PermintaanAturUlangs to update
   */
  where?: Prisma.PermintaanAturUlangWhereInput
  /**
   * Limit how many PermintaanAturUlangs to update.
   */
  limit?: number
}

/**
 * PermintaanAturUlang updateManyAndReturn
 */
export type PermintaanAturUlangUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PermintaanAturUlang
   */
  select?: Prisma.PermintaanAturUlangSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PermintaanAturUlang
   */
  omit?: Prisma.PermintaanAturUlangOmit<ExtArgs> | null
  /**
   * The data used to update PermintaanAturUlangs.
   */
  data: Prisma.XOR<Prisma.PermintaanAturUlangUpdateManyMutationInput, Prisma.PermintaanAturUlangUncheckedUpdateManyInput>
  /**
   * Filter which PermintaanAturUlangs to update
   */
  where?: Prisma.PermintaanAturUlangWhereInput
  /**
   * Limit how many PermintaanAturUlangs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PermintaanAturUlangIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PermintaanAturUlang upsert
 */
export type PermintaanAturUlangUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PermintaanAturUlang
   */
  select?: Prisma.PermintaanAturUlangSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PermintaanAturUlang
   */
  omit?: Prisma.PermintaanAturUlangOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PermintaanAturUlangInclude<ExtArgs> | null
  /**
   * The filter to search for the PermintaanAturUlang to update in case it exists.
   */
  where: Prisma.PermintaanAturUlangWhereUniqueInput
  /**
   * In case the PermintaanAturUlang found by the `where` argument doesn't exist, create a new PermintaanAturUlang with this data.
   */
  create: Prisma.XOR<Prisma.PermintaanAturUlangCreateInput, Prisma.PermintaanAturUlangUncheckedCreateInput>
  /**
   * In case the PermintaanAturUlang was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PermintaanAturUlangUpdateInput, Prisma.PermintaanAturUlangUncheckedUpdateInput>
}

/**
 * PermintaanAturUlang delete
 */
export type PermintaanAturUlangDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PermintaanAturUlang
   */
  select?: Prisma.PermintaanAturUlangSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PermintaanAturUlang
   */
  omit?: Prisma.PermintaanAturUlangOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PermintaanAturUlangInclude<ExtArgs> | null
  /**
   * Filter which PermintaanAturUlang to delete.
   */
  where: Prisma.PermintaanAturUlangWhereUniqueInput
}

/**
 * PermintaanAturUlang deleteMany
 */
export type PermintaanAturUlangDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PermintaanAturUlangs to delete
   */
  where?: Prisma.PermintaanAturUlangWhereInput
  /**
   * Limit how many PermintaanAturUlangs to delete.
   */
  limit?: number
}

/**
 * PermintaanAturUlang without action
 */
export type PermintaanAturUlangDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PermintaanAturUlang
   */
  select?: Prisma.PermintaanAturUlangSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PermintaanAturUlang
   */
  omit?: Prisma.PermintaanAturUlangOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PermintaanAturUlangInclude<ExtArgs> | null
}
