
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ReturPembelian` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ReturPembelian
 * 
 */
export type ReturPembelianModel = runtime.Types.Result.DefaultSelection<Prisma.$ReturPembelianPayload>

export type AggregateReturPembelian = {
  _count: ReturPembelianCountAggregateOutputType | null
  _avg: ReturPembelianAvgAggregateOutputType | null
  _sum: ReturPembelianSumAggregateOutputType | null
  _min: ReturPembelianMinAggregateOutputType | null
  _max: ReturPembelianMaxAggregateOutputType | null
}

export type ReturPembelianAvgAggregateOutputType = {
  total: runtime.Decimal | null
  dpp: runtime.Decimal | null
  ppn: runtime.Decimal | null
}

export type ReturPembelianSumAggregateOutputType = {
  total: runtime.Decimal | null
  dpp: runtime.Decimal | null
  ppn: runtime.Decimal | null
}

export type ReturPembelianMinAggregateOutputType = {
  id: string | null
  nomor: string | null
  tanggal: Date | null
  fakturId: string | null
  gudangId: string | null
  alasan: string | null
  total: runtime.Decimal | null
  dpp: runtime.Decimal | null
  ppn: runtime.Decimal | null
  jurnalId: string | null
}

export type ReturPembelianMaxAggregateOutputType = {
  id: string | null
  nomor: string | null
  tanggal: Date | null
  fakturId: string | null
  gudangId: string | null
  alasan: string | null
  total: runtime.Decimal | null
  dpp: runtime.Decimal | null
  ppn: runtime.Decimal | null
  jurnalId: string | null
}

export type ReturPembelianCountAggregateOutputType = {
  id: number
  nomor: number
  tanggal: number
  fakturId: number
  gudangId: number
  alasan: number
  total: number
  dpp: number
  ppn: number
  jurnalId: number
  _all: number
}


export type ReturPembelianAvgAggregateInputType = {
  total?: true
  dpp?: true
  ppn?: true
}

export type ReturPembelianSumAggregateInputType = {
  total?: true
  dpp?: true
  ppn?: true
}

export type ReturPembelianMinAggregateInputType = {
  id?: true
  nomor?: true
  tanggal?: true
  fakturId?: true
  gudangId?: true
  alasan?: true
  total?: true
  dpp?: true
  ppn?: true
  jurnalId?: true
}

export type ReturPembelianMaxAggregateInputType = {
  id?: true
  nomor?: true
  tanggal?: true
  fakturId?: true
  gudangId?: true
  alasan?: true
  total?: true
  dpp?: true
  ppn?: true
  jurnalId?: true
}

export type ReturPembelianCountAggregateInputType = {
  id?: true
  nomor?: true
  tanggal?: true
  fakturId?: true
  gudangId?: true
  alasan?: true
  total?: true
  dpp?: true
  ppn?: true
  jurnalId?: true
  _all?: true
}

export type ReturPembelianAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ReturPembelian to aggregate.
   */
  where?: Prisma.ReturPembelianWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReturPembelians to fetch.
   */
  orderBy?: Prisma.ReturPembelianOrderByWithRelationInput | Prisma.ReturPembelianOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ReturPembelianWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReturPembelians from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReturPembelians.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ReturPembelians
  **/
  _count?: true | ReturPembelianCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ReturPembelianAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ReturPembelianSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ReturPembelianMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ReturPembelianMaxAggregateInputType
}

export type GetReturPembelianAggregateType<T extends ReturPembelianAggregateArgs> = {
      [P in keyof T & keyof AggregateReturPembelian]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateReturPembelian[P]>
    : Prisma.GetScalarType<T[P], AggregateReturPembelian[P]>
}




export type ReturPembelianGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ReturPembelianWhereInput
  orderBy?: Prisma.ReturPembelianOrderByWithAggregationInput | Prisma.ReturPembelianOrderByWithAggregationInput[]
  by: Prisma.ReturPembelianScalarFieldEnum[] | Prisma.ReturPembelianScalarFieldEnum
  having?: Prisma.ReturPembelianScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ReturPembelianCountAggregateInputType | true
  _avg?: ReturPembelianAvgAggregateInputType
  _sum?: ReturPembelianSumAggregateInputType
  _min?: ReturPembelianMinAggregateInputType
  _max?: ReturPembelianMaxAggregateInputType
}

export type ReturPembelianGroupByOutputType = {
  id: string
  nomor: string
  tanggal: Date
  fakturId: string
  gudangId: string
  alasan: string | null
  total: runtime.Decimal
  dpp: runtime.Decimal
  ppn: runtime.Decimal
  jurnalId: string | null
  _count: ReturPembelianCountAggregateOutputType | null
  _avg: ReturPembelianAvgAggregateOutputType | null
  _sum: ReturPembelianSumAggregateOutputType | null
  _min: ReturPembelianMinAggregateOutputType | null
  _max: ReturPembelianMaxAggregateOutputType | null
}

export type GetReturPembelianGroupByPayload<T extends ReturPembelianGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ReturPembelianGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ReturPembelianGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ReturPembelianGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ReturPembelianGroupByOutputType[P]>
      }
    >
  >



export type ReturPembelianWhereInput = {
  AND?: Prisma.ReturPembelianWhereInput | Prisma.ReturPembelianWhereInput[]
  OR?: Prisma.ReturPembelianWhereInput[]
  NOT?: Prisma.ReturPembelianWhereInput | Prisma.ReturPembelianWhereInput[]
  id?: Prisma.StringFilter<"ReturPembelian"> | string
  nomor?: Prisma.StringFilter<"ReturPembelian"> | string
  tanggal?: Prisma.DateTimeFilter<"ReturPembelian"> | Date | string
  fakturId?: Prisma.StringFilter<"ReturPembelian"> | string
  gudangId?: Prisma.StringFilter<"ReturPembelian"> | string
  alasan?: Prisma.StringNullableFilter<"ReturPembelian"> | string | null
  total?: Prisma.DecimalFilter<"ReturPembelian"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  dpp?: Prisma.DecimalFilter<"ReturPembelian"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  ppn?: Prisma.DecimalFilter<"ReturPembelian"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  jurnalId?: Prisma.StringNullableFilter<"ReturPembelian"> | string | null
  faktur?: Prisma.XOR<Prisma.FakturPembelianScalarRelationFilter, Prisma.FakturPembelianWhereInput>
  gudang?: Prisma.XOR<Prisma.GudangScalarRelationFilter, Prisma.GudangWhereInput>
  jurnal?: Prisma.XOR<Prisma.JurnalNullableScalarRelationFilter, Prisma.JurnalWhereInput> | null
  baris?: Prisma.BarisReturPembelianListRelationFilter
}

export type ReturPembelianOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  nomor?: Prisma.SortOrder
  tanggal?: Prisma.SortOrder
  fakturId?: Prisma.SortOrder
  gudangId?: Prisma.SortOrder
  alasan?: Prisma.SortOrderInput | Prisma.SortOrder
  total?: Prisma.SortOrder
  dpp?: Prisma.SortOrder
  ppn?: Prisma.SortOrder
  jurnalId?: Prisma.SortOrderInput | Prisma.SortOrder
  faktur?: Prisma.FakturPembelianOrderByWithRelationInput
  gudang?: Prisma.GudangOrderByWithRelationInput
  jurnal?: Prisma.JurnalOrderByWithRelationInput
  baris?: Prisma.BarisReturPembelianOrderByRelationAggregateInput
}

export type ReturPembelianWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  nomor?: string
  jurnalId?: string
  AND?: Prisma.ReturPembelianWhereInput | Prisma.ReturPembelianWhereInput[]
  OR?: Prisma.ReturPembelianWhereInput[]
  NOT?: Prisma.ReturPembelianWhereInput | Prisma.ReturPembelianWhereInput[]
  tanggal?: Prisma.DateTimeFilter<"ReturPembelian"> | Date | string
  fakturId?: Prisma.StringFilter<"ReturPembelian"> | string
  gudangId?: Prisma.StringFilter<"ReturPembelian"> | string
  alasan?: Prisma.StringNullableFilter<"ReturPembelian"> | string | null
  total?: Prisma.DecimalFilter<"ReturPembelian"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  dpp?: Prisma.DecimalFilter<"ReturPembelian"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  ppn?: Prisma.DecimalFilter<"ReturPembelian"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  faktur?: Prisma.XOR<Prisma.FakturPembelianScalarRelationFilter, Prisma.FakturPembelianWhereInput>
  gudang?: Prisma.XOR<Prisma.GudangScalarRelationFilter, Prisma.GudangWhereInput>
  jurnal?: Prisma.XOR<Prisma.JurnalNullableScalarRelationFilter, Prisma.JurnalWhereInput> | null
  baris?: Prisma.BarisReturPembelianListRelationFilter
}, "id" | "nomor" | "jurnalId">

export type ReturPembelianOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  nomor?: Prisma.SortOrder
  tanggal?: Prisma.SortOrder
  fakturId?: Prisma.SortOrder
  gudangId?: Prisma.SortOrder
  alasan?: Prisma.SortOrderInput | Prisma.SortOrder
  total?: Prisma.SortOrder
  dpp?: Prisma.SortOrder
  ppn?: Prisma.SortOrder
  jurnalId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ReturPembelianCountOrderByAggregateInput
  _avg?: Prisma.ReturPembelianAvgOrderByAggregateInput
  _max?: Prisma.ReturPembelianMaxOrderByAggregateInput
  _min?: Prisma.ReturPembelianMinOrderByAggregateInput
  _sum?: Prisma.ReturPembelianSumOrderByAggregateInput
}

export type ReturPembelianScalarWhereWithAggregatesInput = {
  AND?: Prisma.ReturPembelianScalarWhereWithAggregatesInput | Prisma.ReturPembelianScalarWhereWithAggregatesInput[]
  OR?: Prisma.ReturPembelianScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ReturPembelianScalarWhereWithAggregatesInput | Prisma.ReturPembelianScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ReturPembelian"> | string
  nomor?: Prisma.StringWithAggregatesFilter<"ReturPembelian"> | string
  tanggal?: Prisma.DateTimeWithAggregatesFilter<"ReturPembelian"> | Date | string
  fakturId?: Prisma.StringWithAggregatesFilter<"ReturPembelian"> | string
  gudangId?: Prisma.StringWithAggregatesFilter<"ReturPembelian"> | string
  alasan?: Prisma.StringNullableWithAggregatesFilter<"ReturPembelian"> | string | null
  total?: Prisma.DecimalWithAggregatesFilter<"ReturPembelian"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  dpp?: Prisma.DecimalWithAggregatesFilter<"ReturPembelian"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  ppn?: Prisma.DecimalWithAggregatesFilter<"ReturPembelian"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  jurnalId?: Prisma.StringNullableWithAggregatesFilter<"ReturPembelian"> | string | null
}

export type ReturPembelianCreateInput = {
  id?: string
  nomor: string
  tanggal?: Date | string
  alasan?: string | null
  total?: runtime.Decimal | runtime.DecimalJsLike | number | string
  dpp?: runtime.Decimal | runtime.DecimalJsLike | number | string
  ppn?: runtime.Decimal | runtime.DecimalJsLike | number | string
  faktur: Prisma.FakturPembelianCreateNestedOneWithoutReturInput
  gudang: Prisma.GudangCreateNestedOneWithoutReturPembelianInput
  jurnal?: Prisma.JurnalCreateNestedOneWithoutReturPembelianInput
  baris?: Prisma.BarisReturPembelianCreateNestedManyWithoutReturInput
}

export type ReturPembelianUncheckedCreateInput = {
  id?: string
  nomor: string
  tanggal?: Date | string
  fakturId: string
  gudangId: string
  alasan?: string | null
  total?: runtime.Decimal | runtime.DecimalJsLike | number | string
  dpp?: runtime.Decimal | runtime.DecimalJsLike | number | string
  ppn?: runtime.Decimal | runtime.DecimalJsLike | number | string
  jurnalId?: string | null
  baris?: Prisma.BarisReturPembelianUncheckedCreateNestedManyWithoutReturInput
}

export type ReturPembelianUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nomor?: Prisma.StringFieldUpdateOperationsInput | string
  tanggal?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  alasan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dpp?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  ppn?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  faktur?: Prisma.FakturPembelianUpdateOneRequiredWithoutReturNestedInput
  gudang?: Prisma.GudangUpdateOneRequiredWithoutReturPembelianNestedInput
  jurnal?: Prisma.JurnalUpdateOneWithoutReturPembelianNestedInput
  baris?: Prisma.BarisReturPembelianUpdateManyWithoutReturNestedInput
}

export type ReturPembelianUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nomor?: Prisma.StringFieldUpdateOperationsInput | string
  tanggal?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fakturId?: Prisma.StringFieldUpdateOperationsInput | string
  gudangId?: Prisma.StringFieldUpdateOperationsInput | string
  alasan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dpp?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  ppn?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  jurnalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  baris?: Prisma.BarisReturPembelianUncheckedUpdateManyWithoutReturNestedInput
}

export type ReturPembelianCreateManyInput = {
  id?: string
  nomor: string
  tanggal?: Date | string
  fakturId: string
  gudangId: string
  alasan?: string | null
  total?: runtime.Decimal | runtime.DecimalJsLike | number | string
  dpp?: runtime.Decimal | runtime.DecimalJsLike | number | string
  ppn?: runtime.Decimal | runtime.DecimalJsLike | number | string
  jurnalId?: string | null
}

export type ReturPembelianUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nomor?: Prisma.StringFieldUpdateOperationsInput | string
  tanggal?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  alasan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dpp?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  ppn?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type ReturPembelianUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nomor?: Prisma.StringFieldUpdateOperationsInput | string
  tanggal?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fakturId?: Prisma.StringFieldUpdateOperationsInput | string
  gudangId?: Prisma.StringFieldUpdateOperationsInput | string
  alasan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dpp?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  ppn?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  jurnalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ReturPembelianListRelationFilter = {
  every?: Prisma.ReturPembelianWhereInput
  some?: Prisma.ReturPembelianWhereInput
  none?: Prisma.ReturPembelianWhereInput
}

export type ReturPembelianOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ReturPembelianCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nomor?: Prisma.SortOrder
  tanggal?: Prisma.SortOrder
  fakturId?: Prisma.SortOrder
  gudangId?: Prisma.SortOrder
  alasan?: Prisma.SortOrder
  total?: Prisma.SortOrder
  dpp?: Prisma.SortOrder
  ppn?: Prisma.SortOrder
  jurnalId?: Prisma.SortOrder
}

export type ReturPembelianAvgOrderByAggregateInput = {
  total?: Prisma.SortOrder
  dpp?: Prisma.SortOrder
  ppn?: Prisma.SortOrder
}

export type ReturPembelianMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nomor?: Prisma.SortOrder
  tanggal?: Prisma.SortOrder
  fakturId?: Prisma.SortOrder
  gudangId?: Prisma.SortOrder
  alasan?: Prisma.SortOrder
  total?: Prisma.SortOrder
  dpp?: Prisma.SortOrder
  ppn?: Prisma.SortOrder
  jurnalId?: Prisma.SortOrder
}

export type ReturPembelianMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nomor?: Prisma.SortOrder
  tanggal?: Prisma.SortOrder
  fakturId?: Prisma.SortOrder
  gudangId?: Prisma.SortOrder
  alasan?: Prisma.SortOrder
  total?: Prisma.SortOrder
  dpp?: Prisma.SortOrder
  ppn?: Prisma.SortOrder
  jurnalId?: Prisma.SortOrder
}

export type ReturPembelianSumOrderByAggregateInput = {
  total?: Prisma.SortOrder
  dpp?: Prisma.SortOrder
  ppn?: Prisma.SortOrder
}

export type ReturPembelianScalarRelationFilter = {
  is?: Prisma.ReturPembelianWhereInput
  isNot?: Prisma.ReturPembelianWhereInput
}

export type ReturPembelianNullableScalarRelationFilter = {
  is?: Prisma.ReturPembelianWhereInput | null
  isNot?: Prisma.ReturPembelianWhereInput | null
}

export type ReturPembelianCreateNestedManyWithoutGudangInput = {
  create?: Prisma.XOR<Prisma.ReturPembelianCreateWithoutGudangInput, Prisma.ReturPembelianUncheckedCreateWithoutGudangInput> | Prisma.ReturPembelianCreateWithoutGudangInput[] | Prisma.ReturPembelianUncheckedCreateWithoutGudangInput[]
  connectOrCreate?: Prisma.ReturPembelianCreateOrConnectWithoutGudangInput | Prisma.ReturPembelianCreateOrConnectWithoutGudangInput[]
  createMany?: Prisma.ReturPembelianCreateManyGudangInputEnvelope
  connect?: Prisma.ReturPembelianWhereUniqueInput | Prisma.ReturPembelianWhereUniqueInput[]
}

export type ReturPembelianUncheckedCreateNestedManyWithoutGudangInput = {
  create?: Prisma.XOR<Prisma.ReturPembelianCreateWithoutGudangInput, Prisma.ReturPembelianUncheckedCreateWithoutGudangInput> | Prisma.ReturPembelianCreateWithoutGudangInput[] | Prisma.ReturPembelianUncheckedCreateWithoutGudangInput[]
  connectOrCreate?: Prisma.ReturPembelianCreateOrConnectWithoutGudangInput | Prisma.ReturPembelianCreateOrConnectWithoutGudangInput[]
  createMany?: Prisma.ReturPembelianCreateManyGudangInputEnvelope
  connect?: Prisma.ReturPembelianWhereUniqueInput | Prisma.ReturPembelianWhereUniqueInput[]
}

export type ReturPembelianUpdateManyWithoutGudangNestedInput = {
  create?: Prisma.XOR<Prisma.ReturPembelianCreateWithoutGudangInput, Prisma.ReturPembelianUncheckedCreateWithoutGudangInput> | Prisma.ReturPembelianCreateWithoutGudangInput[] | Prisma.ReturPembelianUncheckedCreateWithoutGudangInput[]
  connectOrCreate?: Prisma.ReturPembelianCreateOrConnectWithoutGudangInput | Prisma.ReturPembelianCreateOrConnectWithoutGudangInput[]
  upsert?: Prisma.ReturPembelianUpsertWithWhereUniqueWithoutGudangInput | Prisma.ReturPembelianUpsertWithWhereUniqueWithoutGudangInput[]
  createMany?: Prisma.ReturPembelianCreateManyGudangInputEnvelope
  set?: Prisma.ReturPembelianWhereUniqueInput | Prisma.ReturPembelianWhereUniqueInput[]
  disconnect?: Prisma.ReturPembelianWhereUniqueInput | Prisma.ReturPembelianWhereUniqueInput[]
  delete?: Prisma.ReturPembelianWhereUniqueInput | Prisma.ReturPembelianWhereUniqueInput[]
  connect?: Prisma.ReturPembelianWhereUniqueInput | Prisma.ReturPembelianWhereUniqueInput[]
  update?: Prisma.ReturPembelianUpdateWithWhereUniqueWithoutGudangInput | Prisma.ReturPembelianUpdateWithWhereUniqueWithoutGudangInput[]
  updateMany?: Prisma.ReturPembelianUpdateManyWithWhereWithoutGudangInput | Prisma.ReturPembelianUpdateManyWithWhereWithoutGudangInput[]
  deleteMany?: Prisma.ReturPembelianScalarWhereInput | Prisma.ReturPembelianScalarWhereInput[]
}

export type ReturPembelianUncheckedUpdateManyWithoutGudangNestedInput = {
  create?: Prisma.XOR<Prisma.ReturPembelianCreateWithoutGudangInput, Prisma.ReturPembelianUncheckedCreateWithoutGudangInput> | Prisma.ReturPembelianCreateWithoutGudangInput[] | Prisma.ReturPembelianUncheckedCreateWithoutGudangInput[]
  connectOrCreate?: Prisma.ReturPembelianCreateOrConnectWithoutGudangInput | Prisma.ReturPembelianCreateOrConnectWithoutGudangInput[]
  upsert?: Prisma.ReturPembelianUpsertWithWhereUniqueWithoutGudangInput | Prisma.ReturPembelianUpsertWithWhereUniqueWithoutGudangInput[]
  createMany?: Prisma.ReturPembelianCreateManyGudangInputEnvelope
  set?: Prisma.ReturPembelianWhereUniqueInput | Prisma.ReturPembelianWhereUniqueInput[]
  disconnect?: Prisma.ReturPembelianWhereUniqueInput | Prisma.ReturPembelianWhereUniqueInput[]
  delete?: Prisma.ReturPembelianWhereUniqueInput | Prisma.ReturPembelianWhereUniqueInput[]
  connect?: Prisma.ReturPembelianWhereUniqueInput | Prisma.ReturPembelianWhereUniqueInput[]
  update?: Prisma.ReturPembelianUpdateWithWhereUniqueWithoutGudangInput | Prisma.ReturPembelianUpdateWithWhereUniqueWithoutGudangInput[]
  updateMany?: Prisma.ReturPembelianUpdateManyWithWhereWithoutGudangInput | Prisma.ReturPembelianUpdateManyWithWhereWithoutGudangInput[]
  deleteMany?: Prisma.ReturPembelianScalarWhereInput | Prisma.ReturPembelianScalarWhereInput[]
}

export type ReturPembelianCreateNestedManyWithoutFakturInput = {
  create?: Prisma.XOR<Prisma.ReturPembelianCreateWithoutFakturInput, Prisma.ReturPembelianUncheckedCreateWithoutFakturInput> | Prisma.ReturPembelianCreateWithoutFakturInput[] | Prisma.ReturPembelianUncheckedCreateWithoutFakturInput[]
  connectOrCreate?: Prisma.ReturPembelianCreateOrConnectWithoutFakturInput | Prisma.ReturPembelianCreateOrConnectWithoutFakturInput[]
  createMany?: Prisma.ReturPembelianCreateManyFakturInputEnvelope
  connect?: Prisma.ReturPembelianWhereUniqueInput | Prisma.ReturPembelianWhereUniqueInput[]
}

export type ReturPembelianUncheckedCreateNestedManyWithoutFakturInput = {
  create?: Prisma.XOR<Prisma.ReturPembelianCreateWithoutFakturInput, Prisma.ReturPembelianUncheckedCreateWithoutFakturInput> | Prisma.ReturPembelianCreateWithoutFakturInput[] | Prisma.ReturPembelianUncheckedCreateWithoutFakturInput[]
  connectOrCreate?: Prisma.ReturPembelianCreateOrConnectWithoutFakturInput | Prisma.ReturPembelianCreateOrConnectWithoutFakturInput[]
  createMany?: Prisma.ReturPembelianCreateManyFakturInputEnvelope
  connect?: Prisma.ReturPembelianWhereUniqueInput | Prisma.ReturPembelianWhereUniqueInput[]
}

export type ReturPembelianUpdateManyWithoutFakturNestedInput = {
  create?: Prisma.XOR<Prisma.ReturPembelianCreateWithoutFakturInput, Prisma.ReturPembelianUncheckedCreateWithoutFakturInput> | Prisma.ReturPembelianCreateWithoutFakturInput[] | Prisma.ReturPembelianUncheckedCreateWithoutFakturInput[]
  connectOrCreate?: Prisma.ReturPembelianCreateOrConnectWithoutFakturInput | Prisma.ReturPembelianCreateOrConnectWithoutFakturInput[]
  upsert?: Prisma.ReturPembelianUpsertWithWhereUniqueWithoutFakturInput | Prisma.ReturPembelianUpsertWithWhereUniqueWithoutFakturInput[]
  createMany?: Prisma.ReturPembelianCreateManyFakturInputEnvelope
  set?: Prisma.ReturPembelianWhereUniqueInput | Prisma.ReturPembelianWhereUniqueInput[]
  disconnect?: Prisma.ReturPembelianWhereUniqueInput | Prisma.ReturPembelianWhereUniqueInput[]
  delete?: Prisma.ReturPembelianWhereUniqueInput | Prisma.ReturPembelianWhereUniqueInput[]
  connect?: Prisma.ReturPembelianWhereUniqueInput | Prisma.ReturPembelianWhereUniqueInput[]
  update?: Prisma.ReturPembelianUpdateWithWhereUniqueWithoutFakturInput | Prisma.ReturPembelianUpdateWithWhereUniqueWithoutFakturInput[]
  updateMany?: Prisma.ReturPembelianUpdateManyWithWhereWithoutFakturInput | Prisma.ReturPembelianUpdateManyWithWhereWithoutFakturInput[]
  deleteMany?: Prisma.ReturPembelianScalarWhereInput | Prisma.ReturPembelianScalarWhereInput[]
}

export type ReturPembelianUncheckedUpdateManyWithoutFakturNestedInput = {
  create?: Prisma.XOR<Prisma.ReturPembelianCreateWithoutFakturInput, Prisma.ReturPembelianUncheckedCreateWithoutFakturInput> | Prisma.ReturPembelianCreateWithoutFakturInput[] | Prisma.ReturPembelianUncheckedCreateWithoutFakturInput[]
  connectOrCreate?: Prisma.ReturPembelianCreateOrConnectWithoutFakturInput | Prisma.ReturPembelianCreateOrConnectWithoutFakturInput[]
  upsert?: Prisma.ReturPembelianUpsertWithWhereUniqueWithoutFakturInput | Prisma.ReturPembelianUpsertWithWhereUniqueWithoutFakturInput[]
  createMany?: Prisma.ReturPembelianCreateManyFakturInputEnvelope
  set?: Prisma.ReturPembelianWhereUniqueInput | Prisma.ReturPembelianWhereUniqueInput[]
  disconnect?: Prisma.ReturPembelianWhereUniqueInput | Prisma.ReturPembelianWhereUniqueInput[]
  delete?: Prisma.ReturPembelianWhereUniqueInput | Prisma.ReturPembelianWhereUniqueInput[]
  connect?: Prisma.ReturPembelianWhereUniqueInput | Prisma.ReturPembelianWhereUniqueInput[]
  update?: Prisma.ReturPembelianUpdateWithWhereUniqueWithoutFakturInput | Prisma.ReturPembelianUpdateWithWhereUniqueWithoutFakturInput[]
  updateMany?: Prisma.ReturPembelianUpdateManyWithWhereWithoutFakturInput | Prisma.ReturPembelianUpdateManyWithWhereWithoutFakturInput[]
  deleteMany?: Prisma.ReturPembelianScalarWhereInput | Prisma.ReturPembelianScalarWhereInput[]
}

export type ReturPembelianCreateNestedOneWithoutBarisInput = {
  create?: Prisma.XOR<Prisma.ReturPembelianCreateWithoutBarisInput, Prisma.ReturPembelianUncheckedCreateWithoutBarisInput>
  connectOrCreate?: Prisma.ReturPembelianCreateOrConnectWithoutBarisInput
  connect?: Prisma.ReturPembelianWhereUniqueInput
}

export type ReturPembelianUpdateOneRequiredWithoutBarisNestedInput = {
  create?: Prisma.XOR<Prisma.ReturPembelianCreateWithoutBarisInput, Prisma.ReturPembelianUncheckedCreateWithoutBarisInput>
  connectOrCreate?: Prisma.ReturPembelianCreateOrConnectWithoutBarisInput
  upsert?: Prisma.ReturPembelianUpsertWithoutBarisInput
  connect?: Prisma.ReturPembelianWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ReturPembelianUpdateToOneWithWhereWithoutBarisInput, Prisma.ReturPembelianUpdateWithoutBarisInput>, Prisma.ReturPembelianUncheckedUpdateWithoutBarisInput>
}

export type ReturPembelianCreateNestedOneWithoutJurnalInput = {
  create?: Prisma.XOR<Prisma.ReturPembelianCreateWithoutJurnalInput, Prisma.ReturPembelianUncheckedCreateWithoutJurnalInput>
  connectOrCreate?: Prisma.ReturPembelianCreateOrConnectWithoutJurnalInput
  connect?: Prisma.ReturPembelianWhereUniqueInput
}

export type ReturPembelianUncheckedCreateNestedOneWithoutJurnalInput = {
  create?: Prisma.XOR<Prisma.ReturPembelianCreateWithoutJurnalInput, Prisma.ReturPembelianUncheckedCreateWithoutJurnalInput>
  connectOrCreate?: Prisma.ReturPembelianCreateOrConnectWithoutJurnalInput
  connect?: Prisma.ReturPembelianWhereUniqueInput
}

export type ReturPembelianUpdateOneWithoutJurnalNestedInput = {
  create?: Prisma.XOR<Prisma.ReturPembelianCreateWithoutJurnalInput, Prisma.ReturPembelianUncheckedCreateWithoutJurnalInput>
  connectOrCreate?: Prisma.ReturPembelianCreateOrConnectWithoutJurnalInput
  upsert?: Prisma.ReturPembelianUpsertWithoutJurnalInput
  disconnect?: Prisma.ReturPembelianWhereInput | boolean
  delete?: Prisma.ReturPembelianWhereInput | boolean
  connect?: Prisma.ReturPembelianWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ReturPembelianUpdateToOneWithWhereWithoutJurnalInput, Prisma.ReturPembelianUpdateWithoutJurnalInput>, Prisma.ReturPembelianUncheckedUpdateWithoutJurnalInput>
}

export type ReturPembelianUncheckedUpdateOneWithoutJurnalNestedInput = {
  create?: Prisma.XOR<Prisma.ReturPembelianCreateWithoutJurnalInput, Prisma.ReturPembelianUncheckedCreateWithoutJurnalInput>
  connectOrCreate?: Prisma.ReturPembelianCreateOrConnectWithoutJurnalInput
  upsert?: Prisma.ReturPembelianUpsertWithoutJurnalInput
  disconnect?: Prisma.ReturPembelianWhereInput | boolean
  delete?: Prisma.ReturPembelianWhereInput | boolean
  connect?: Prisma.ReturPembelianWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ReturPembelianUpdateToOneWithWhereWithoutJurnalInput, Prisma.ReturPembelianUpdateWithoutJurnalInput>, Prisma.ReturPembelianUncheckedUpdateWithoutJurnalInput>
}

export type ReturPembelianCreateWithoutGudangInput = {
  id?: string
  nomor: string
  tanggal?: Date | string
  alasan?: string | null
  total?: runtime.Decimal | runtime.DecimalJsLike | number | string
  dpp?: runtime.Decimal | runtime.DecimalJsLike | number | string
  ppn?: runtime.Decimal | runtime.DecimalJsLike | number | string
  faktur: Prisma.FakturPembelianCreateNestedOneWithoutReturInput
  jurnal?: Prisma.JurnalCreateNestedOneWithoutReturPembelianInput
  baris?: Prisma.BarisReturPembelianCreateNestedManyWithoutReturInput
}

export type ReturPembelianUncheckedCreateWithoutGudangInput = {
  id?: string
  nomor: string
  tanggal?: Date | string
  fakturId: string
  alasan?: string | null
  total?: runtime.Decimal | runtime.DecimalJsLike | number | string
  dpp?: runtime.Decimal | runtime.DecimalJsLike | number | string
  ppn?: runtime.Decimal | runtime.DecimalJsLike | number | string
  jurnalId?: string | null
  baris?: Prisma.BarisReturPembelianUncheckedCreateNestedManyWithoutReturInput
}

export type ReturPembelianCreateOrConnectWithoutGudangInput = {
  where: Prisma.ReturPembelianWhereUniqueInput
  create: Prisma.XOR<Prisma.ReturPembelianCreateWithoutGudangInput, Prisma.ReturPembelianUncheckedCreateWithoutGudangInput>
}

export type ReturPembelianCreateManyGudangInputEnvelope = {
  data: Prisma.ReturPembelianCreateManyGudangInput | Prisma.ReturPembelianCreateManyGudangInput[]
  skipDuplicates?: boolean
}

export type ReturPembelianUpsertWithWhereUniqueWithoutGudangInput = {
  where: Prisma.ReturPembelianWhereUniqueInput
  update: Prisma.XOR<Prisma.ReturPembelianUpdateWithoutGudangInput, Prisma.ReturPembelianUncheckedUpdateWithoutGudangInput>
  create: Prisma.XOR<Prisma.ReturPembelianCreateWithoutGudangInput, Prisma.ReturPembelianUncheckedCreateWithoutGudangInput>
}

export type ReturPembelianUpdateWithWhereUniqueWithoutGudangInput = {
  where: Prisma.ReturPembelianWhereUniqueInput
  data: Prisma.XOR<Prisma.ReturPembelianUpdateWithoutGudangInput, Prisma.ReturPembelianUncheckedUpdateWithoutGudangInput>
}

export type ReturPembelianUpdateManyWithWhereWithoutGudangInput = {
  where: Prisma.ReturPembelianScalarWhereInput
  data: Prisma.XOR<Prisma.ReturPembelianUpdateManyMutationInput, Prisma.ReturPembelianUncheckedUpdateManyWithoutGudangInput>
}

export type ReturPembelianScalarWhereInput = {
  AND?: Prisma.ReturPembelianScalarWhereInput | Prisma.ReturPembelianScalarWhereInput[]
  OR?: Prisma.ReturPembelianScalarWhereInput[]
  NOT?: Prisma.ReturPembelianScalarWhereInput | Prisma.ReturPembelianScalarWhereInput[]
  id?: Prisma.StringFilter<"ReturPembelian"> | string
  nomor?: Prisma.StringFilter<"ReturPembelian"> | string
  tanggal?: Prisma.DateTimeFilter<"ReturPembelian"> | Date | string
  fakturId?: Prisma.StringFilter<"ReturPembelian"> | string
  gudangId?: Prisma.StringFilter<"ReturPembelian"> | string
  alasan?: Prisma.StringNullableFilter<"ReturPembelian"> | string | null
  total?: Prisma.DecimalFilter<"ReturPembelian"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  dpp?: Prisma.DecimalFilter<"ReturPembelian"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  ppn?: Prisma.DecimalFilter<"ReturPembelian"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  jurnalId?: Prisma.StringNullableFilter<"ReturPembelian"> | string | null
}

export type ReturPembelianCreateWithoutFakturInput = {
  id?: string
  nomor: string
  tanggal?: Date | string
  alasan?: string | null
  total?: runtime.Decimal | runtime.DecimalJsLike | number | string
  dpp?: runtime.Decimal | runtime.DecimalJsLike | number | string
  ppn?: runtime.Decimal | runtime.DecimalJsLike | number | string
  gudang: Prisma.GudangCreateNestedOneWithoutReturPembelianInput
  jurnal?: Prisma.JurnalCreateNestedOneWithoutReturPembelianInput
  baris?: Prisma.BarisReturPembelianCreateNestedManyWithoutReturInput
}

export type ReturPembelianUncheckedCreateWithoutFakturInput = {
  id?: string
  nomor: string
  tanggal?: Date | string
  gudangId: string
  alasan?: string | null
  total?: runtime.Decimal | runtime.DecimalJsLike | number | string
  dpp?: runtime.Decimal | runtime.DecimalJsLike | number | string
  ppn?: runtime.Decimal | runtime.DecimalJsLike | number | string
  jurnalId?: string | null
  baris?: Prisma.BarisReturPembelianUncheckedCreateNestedManyWithoutReturInput
}

export type ReturPembelianCreateOrConnectWithoutFakturInput = {
  where: Prisma.ReturPembelianWhereUniqueInput
  create: Prisma.XOR<Prisma.ReturPembelianCreateWithoutFakturInput, Prisma.ReturPembelianUncheckedCreateWithoutFakturInput>
}

export type ReturPembelianCreateManyFakturInputEnvelope = {
  data: Prisma.ReturPembelianCreateManyFakturInput | Prisma.ReturPembelianCreateManyFakturInput[]
  skipDuplicates?: boolean
}

export type ReturPembelianUpsertWithWhereUniqueWithoutFakturInput = {
  where: Prisma.ReturPembelianWhereUniqueInput
  update: Prisma.XOR<Prisma.ReturPembelianUpdateWithoutFakturInput, Prisma.ReturPembelianUncheckedUpdateWithoutFakturInput>
  create: Prisma.XOR<Prisma.ReturPembelianCreateWithoutFakturInput, Prisma.ReturPembelianUncheckedCreateWithoutFakturInput>
}

export type ReturPembelianUpdateWithWhereUniqueWithoutFakturInput = {
  where: Prisma.ReturPembelianWhereUniqueInput
  data: Prisma.XOR<Prisma.ReturPembelianUpdateWithoutFakturInput, Prisma.ReturPembelianUncheckedUpdateWithoutFakturInput>
}

export type ReturPembelianUpdateManyWithWhereWithoutFakturInput = {
  where: Prisma.ReturPembelianScalarWhereInput
  data: Prisma.XOR<Prisma.ReturPembelianUpdateManyMutationInput, Prisma.ReturPembelianUncheckedUpdateManyWithoutFakturInput>
}

export type ReturPembelianCreateWithoutBarisInput = {
  id?: string
  nomor: string
  tanggal?: Date | string
  alasan?: string | null
  total?: runtime.Decimal | runtime.DecimalJsLike | number | string
  dpp?: runtime.Decimal | runtime.DecimalJsLike | number | string
  ppn?: runtime.Decimal | runtime.DecimalJsLike | number | string
  faktur: Prisma.FakturPembelianCreateNestedOneWithoutReturInput
  gudang: Prisma.GudangCreateNestedOneWithoutReturPembelianInput
  jurnal?: Prisma.JurnalCreateNestedOneWithoutReturPembelianInput
}

export type ReturPembelianUncheckedCreateWithoutBarisInput = {
  id?: string
  nomor: string
  tanggal?: Date | string
  fakturId: string
  gudangId: string
  alasan?: string | null
  total?: runtime.Decimal | runtime.DecimalJsLike | number | string
  dpp?: runtime.Decimal | runtime.DecimalJsLike | number | string
  ppn?: runtime.Decimal | runtime.DecimalJsLike | number | string
  jurnalId?: string | null
}

export type ReturPembelianCreateOrConnectWithoutBarisInput = {
  where: Prisma.ReturPembelianWhereUniqueInput
  create: Prisma.XOR<Prisma.ReturPembelianCreateWithoutBarisInput, Prisma.ReturPembelianUncheckedCreateWithoutBarisInput>
}

export type ReturPembelianUpsertWithoutBarisInput = {
  update: Prisma.XOR<Prisma.ReturPembelianUpdateWithoutBarisInput, Prisma.ReturPembelianUncheckedUpdateWithoutBarisInput>
  create: Prisma.XOR<Prisma.ReturPembelianCreateWithoutBarisInput, Prisma.ReturPembelianUncheckedCreateWithoutBarisInput>
  where?: Prisma.ReturPembelianWhereInput
}

export type ReturPembelianUpdateToOneWithWhereWithoutBarisInput = {
  where?: Prisma.ReturPembelianWhereInput
  data: Prisma.XOR<Prisma.ReturPembelianUpdateWithoutBarisInput, Prisma.ReturPembelianUncheckedUpdateWithoutBarisInput>
}

export type ReturPembelianUpdateWithoutBarisInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nomor?: Prisma.StringFieldUpdateOperationsInput | string
  tanggal?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  alasan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dpp?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  ppn?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  faktur?: Prisma.FakturPembelianUpdateOneRequiredWithoutReturNestedInput
  gudang?: Prisma.GudangUpdateOneRequiredWithoutReturPembelianNestedInput
  jurnal?: Prisma.JurnalUpdateOneWithoutReturPembelianNestedInput
}

export type ReturPembelianUncheckedUpdateWithoutBarisInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nomor?: Prisma.StringFieldUpdateOperationsInput | string
  tanggal?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fakturId?: Prisma.StringFieldUpdateOperationsInput | string
  gudangId?: Prisma.StringFieldUpdateOperationsInput | string
  alasan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dpp?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  ppn?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  jurnalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ReturPembelianCreateWithoutJurnalInput = {
  id?: string
  nomor: string
  tanggal?: Date | string
  alasan?: string | null
  total?: runtime.Decimal | runtime.DecimalJsLike | number | string
  dpp?: runtime.Decimal | runtime.DecimalJsLike | number | string
  ppn?: runtime.Decimal | runtime.DecimalJsLike | number | string
  faktur: Prisma.FakturPembelianCreateNestedOneWithoutReturInput
  gudang: Prisma.GudangCreateNestedOneWithoutReturPembelianInput
  baris?: Prisma.BarisReturPembelianCreateNestedManyWithoutReturInput
}

export type ReturPembelianUncheckedCreateWithoutJurnalInput = {
  id?: string
  nomor: string
  tanggal?: Date | string
  fakturId: string
  gudangId: string
  alasan?: string | null
  total?: runtime.Decimal | runtime.DecimalJsLike | number | string
  dpp?: runtime.Decimal | runtime.DecimalJsLike | number | string
  ppn?: runtime.Decimal | runtime.DecimalJsLike | number | string
  baris?: Prisma.BarisReturPembelianUncheckedCreateNestedManyWithoutReturInput
}

export type ReturPembelianCreateOrConnectWithoutJurnalInput = {
  where: Prisma.ReturPembelianWhereUniqueInput
  create: Prisma.XOR<Prisma.ReturPembelianCreateWithoutJurnalInput, Prisma.ReturPembelianUncheckedCreateWithoutJurnalInput>
}

export type ReturPembelianUpsertWithoutJurnalInput = {
  update: Prisma.XOR<Prisma.ReturPembelianUpdateWithoutJurnalInput, Prisma.ReturPembelianUncheckedUpdateWithoutJurnalInput>
  create: Prisma.XOR<Prisma.ReturPembelianCreateWithoutJurnalInput, Prisma.ReturPembelianUncheckedCreateWithoutJurnalInput>
  where?: Prisma.ReturPembelianWhereInput
}

export type ReturPembelianUpdateToOneWithWhereWithoutJurnalInput = {
  where?: Prisma.ReturPembelianWhereInput
  data: Prisma.XOR<Prisma.ReturPembelianUpdateWithoutJurnalInput, Prisma.ReturPembelianUncheckedUpdateWithoutJurnalInput>
}

export type ReturPembelianUpdateWithoutJurnalInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nomor?: Prisma.StringFieldUpdateOperationsInput | string
  tanggal?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  alasan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dpp?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  ppn?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  faktur?: Prisma.FakturPembelianUpdateOneRequiredWithoutReturNestedInput
  gudang?: Prisma.GudangUpdateOneRequiredWithoutReturPembelianNestedInput
  baris?: Prisma.BarisReturPembelianUpdateManyWithoutReturNestedInput
}

export type ReturPembelianUncheckedUpdateWithoutJurnalInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nomor?: Prisma.StringFieldUpdateOperationsInput | string
  tanggal?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fakturId?: Prisma.StringFieldUpdateOperationsInput | string
  gudangId?: Prisma.StringFieldUpdateOperationsInput | string
  alasan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dpp?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  ppn?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  baris?: Prisma.BarisReturPembelianUncheckedUpdateManyWithoutReturNestedInput
}

export type ReturPembelianCreateManyGudangInput = {
  id?: string
  nomor: string
  tanggal?: Date | string
  fakturId: string
  alasan?: string | null
  total?: runtime.Decimal | runtime.DecimalJsLike | number | string
  dpp?: runtime.Decimal | runtime.DecimalJsLike | number | string
  ppn?: runtime.Decimal | runtime.DecimalJsLike | number | string
  jurnalId?: string | null
}

export type ReturPembelianUpdateWithoutGudangInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nomor?: Prisma.StringFieldUpdateOperationsInput | string
  tanggal?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  alasan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dpp?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  ppn?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  faktur?: Prisma.FakturPembelianUpdateOneRequiredWithoutReturNestedInput
  jurnal?: Prisma.JurnalUpdateOneWithoutReturPembelianNestedInput
  baris?: Prisma.BarisReturPembelianUpdateManyWithoutReturNestedInput
}

export type ReturPembelianUncheckedUpdateWithoutGudangInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nomor?: Prisma.StringFieldUpdateOperationsInput | string
  tanggal?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fakturId?: Prisma.StringFieldUpdateOperationsInput | string
  alasan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dpp?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  ppn?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  jurnalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  baris?: Prisma.BarisReturPembelianUncheckedUpdateManyWithoutReturNestedInput
}

export type ReturPembelianUncheckedUpdateManyWithoutGudangInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nomor?: Prisma.StringFieldUpdateOperationsInput | string
  tanggal?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fakturId?: Prisma.StringFieldUpdateOperationsInput | string
  alasan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dpp?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  ppn?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  jurnalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ReturPembelianCreateManyFakturInput = {
  id?: string
  nomor: string
  tanggal?: Date | string
  gudangId: string
  alasan?: string | null
  total?: runtime.Decimal | runtime.DecimalJsLike | number | string
  dpp?: runtime.Decimal | runtime.DecimalJsLike | number | string
  ppn?: runtime.Decimal | runtime.DecimalJsLike | number | string
  jurnalId?: string | null
}

export type ReturPembelianUpdateWithoutFakturInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nomor?: Prisma.StringFieldUpdateOperationsInput | string
  tanggal?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  alasan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dpp?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  ppn?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  gudang?: Prisma.GudangUpdateOneRequiredWithoutReturPembelianNestedInput
  jurnal?: Prisma.JurnalUpdateOneWithoutReturPembelianNestedInput
  baris?: Prisma.BarisReturPembelianUpdateManyWithoutReturNestedInput
}

export type ReturPembelianUncheckedUpdateWithoutFakturInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nomor?: Prisma.StringFieldUpdateOperationsInput | string
  tanggal?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  gudangId?: Prisma.StringFieldUpdateOperationsInput | string
  alasan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dpp?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  ppn?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  jurnalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  baris?: Prisma.BarisReturPembelianUncheckedUpdateManyWithoutReturNestedInput
}

export type ReturPembelianUncheckedUpdateManyWithoutFakturInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nomor?: Prisma.StringFieldUpdateOperationsInput | string
  tanggal?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  gudangId?: Prisma.StringFieldUpdateOperationsInput | string
  alasan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dpp?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  ppn?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  jurnalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type ReturPembelianCountOutputType
 */

export type ReturPembelianCountOutputType = {
  baris: number
}

export type ReturPembelianCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  baris?: boolean | ReturPembelianCountOutputTypeCountBarisArgs
}

/**
 * ReturPembelianCountOutputType without action
 */
export type ReturPembelianCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReturPembelianCountOutputType
   */
  select?: Prisma.ReturPembelianCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ReturPembelianCountOutputType without action
 */
export type ReturPembelianCountOutputTypeCountBarisArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BarisReturPembelianWhereInput
}


export type ReturPembelianSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nomor?: boolean
  tanggal?: boolean
  fakturId?: boolean
  gudangId?: boolean
  alasan?: boolean
  total?: boolean
  dpp?: boolean
  ppn?: boolean
  jurnalId?: boolean
  faktur?: boolean | Prisma.FakturPembelianDefaultArgs<ExtArgs>
  gudang?: boolean | Prisma.GudangDefaultArgs<ExtArgs>
  jurnal?: boolean | Prisma.ReturPembelian$jurnalArgs<ExtArgs>
  baris?: boolean | Prisma.ReturPembelian$barisArgs<ExtArgs>
  _count?: boolean | Prisma.ReturPembelianCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["returPembelian"]>

export type ReturPembelianSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nomor?: boolean
  tanggal?: boolean
  fakturId?: boolean
  gudangId?: boolean
  alasan?: boolean
  total?: boolean
  dpp?: boolean
  ppn?: boolean
  jurnalId?: boolean
  faktur?: boolean | Prisma.FakturPembelianDefaultArgs<ExtArgs>
  gudang?: boolean | Prisma.GudangDefaultArgs<ExtArgs>
  jurnal?: boolean | Prisma.ReturPembelian$jurnalArgs<ExtArgs>
}, ExtArgs["result"]["returPembelian"]>

export type ReturPembelianSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nomor?: boolean
  tanggal?: boolean
  fakturId?: boolean
  gudangId?: boolean
  alasan?: boolean
  total?: boolean
  dpp?: boolean
  ppn?: boolean
  jurnalId?: boolean
  faktur?: boolean | Prisma.FakturPembelianDefaultArgs<ExtArgs>
  gudang?: boolean | Prisma.GudangDefaultArgs<ExtArgs>
  jurnal?: boolean | Prisma.ReturPembelian$jurnalArgs<ExtArgs>
}, ExtArgs["result"]["returPembelian"]>

export type ReturPembelianSelectScalar = {
  id?: boolean
  nomor?: boolean
  tanggal?: boolean
  fakturId?: boolean
  gudangId?: boolean
  alasan?: boolean
  total?: boolean
  dpp?: boolean
  ppn?: boolean
  jurnalId?: boolean
}

export type ReturPembelianOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "nomor" | "tanggal" | "fakturId" | "gudangId" | "alasan" | "total" | "dpp" | "ppn" | "jurnalId", ExtArgs["result"]["returPembelian"]>
export type ReturPembelianInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  faktur?: boolean | Prisma.FakturPembelianDefaultArgs<ExtArgs>
  gudang?: boolean | Prisma.GudangDefaultArgs<ExtArgs>
  jurnal?: boolean | Prisma.ReturPembelian$jurnalArgs<ExtArgs>
  baris?: boolean | Prisma.ReturPembelian$barisArgs<ExtArgs>
  _count?: boolean | Prisma.ReturPembelianCountOutputTypeDefaultArgs<ExtArgs>
}
export type ReturPembelianIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  faktur?: boolean | Prisma.FakturPembelianDefaultArgs<ExtArgs>
  gudang?: boolean | Prisma.GudangDefaultArgs<ExtArgs>
  jurnal?: boolean | Prisma.ReturPembelian$jurnalArgs<ExtArgs>
}
export type ReturPembelianIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  faktur?: boolean | Prisma.FakturPembelianDefaultArgs<ExtArgs>
  gudang?: boolean | Prisma.GudangDefaultArgs<ExtArgs>
  jurnal?: boolean | Prisma.ReturPembelian$jurnalArgs<ExtArgs>
}

export type $ReturPembelianPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ReturPembelian"
  objects: {
    faktur: Prisma.$FakturPembelianPayload<ExtArgs>
    gudang: Prisma.$GudangPayload<ExtArgs>
    jurnal: Prisma.$JurnalPayload<ExtArgs> | null
    baris: Prisma.$BarisReturPembelianPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    nomor: string
    tanggal: Date
    fakturId: string
    gudangId: string
    alasan: string | null
    total: runtime.Decimal
    dpp: runtime.Decimal
    ppn: runtime.Decimal
    jurnalId: string | null
  }, ExtArgs["result"]["returPembelian"]>
  composites: {}
}

export type ReturPembelianGetPayload<S extends boolean | null | undefined | ReturPembelianDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ReturPembelianPayload, S>

export type ReturPembelianCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ReturPembelianFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ReturPembelianCountAggregateInputType | true
  }

export interface ReturPembelianDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ReturPembelian'], meta: { name: 'ReturPembelian' } }
  /**
   * Find zero or one ReturPembelian that matches the filter.
   * @param {ReturPembelianFindUniqueArgs} args - Arguments to find a ReturPembelian
   * @example
   * // Get one ReturPembelian
   * const returPembelian = await prisma.returPembelian.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ReturPembelianFindUniqueArgs>(args: Prisma.SelectSubset<T, ReturPembelianFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ReturPembelianClient<runtime.Types.Result.GetResult<Prisma.$ReturPembelianPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ReturPembelian that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ReturPembelianFindUniqueOrThrowArgs} args - Arguments to find a ReturPembelian
   * @example
   * // Get one ReturPembelian
   * const returPembelian = await prisma.returPembelian.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ReturPembelianFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ReturPembelianFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ReturPembelianClient<runtime.Types.Result.GetResult<Prisma.$ReturPembelianPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ReturPembelian that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReturPembelianFindFirstArgs} args - Arguments to find a ReturPembelian
   * @example
   * // Get one ReturPembelian
   * const returPembelian = await prisma.returPembelian.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ReturPembelianFindFirstArgs>(args?: Prisma.SelectSubset<T, ReturPembelianFindFirstArgs<ExtArgs>>): Prisma.Prisma__ReturPembelianClient<runtime.Types.Result.GetResult<Prisma.$ReturPembelianPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ReturPembelian that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReturPembelianFindFirstOrThrowArgs} args - Arguments to find a ReturPembelian
   * @example
   * // Get one ReturPembelian
   * const returPembelian = await prisma.returPembelian.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ReturPembelianFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ReturPembelianFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ReturPembelianClient<runtime.Types.Result.GetResult<Prisma.$ReturPembelianPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ReturPembelians that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReturPembelianFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ReturPembelians
   * const returPembelians = await prisma.returPembelian.findMany()
   * 
   * // Get first 10 ReturPembelians
   * const returPembelians = await prisma.returPembelian.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const returPembelianWithIdOnly = await prisma.returPembelian.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ReturPembelianFindManyArgs>(args?: Prisma.SelectSubset<T, ReturPembelianFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReturPembelianPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ReturPembelian.
   * @param {ReturPembelianCreateArgs} args - Arguments to create a ReturPembelian.
   * @example
   * // Create one ReturPembelian
   * const ReturPembelian = await prisma.returPembelian.create({
   *   data: {
   *     // ... data to create a ReturPembelian
   *   }
   * })
   * 
   */
  create<T extends ReturPembelianCreateArgs>(args: Prisma.SelectSubset<T, ReturPembelianCreateArgs<ExtArgs>>): Prisma.Prisma__ReturPembelianClient<runtime.Types.Result.GetResult<Prisma.$ReturPembelianPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ReturPembelians.
   * @param {ReturPembelianCreateManyArgs} args - Arguments to create many ReturPembelians.
   * @example
   * // Create many ReturPembelians
   * const returPembelian = await prisma.returPembelian.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ReturPembelianCreateManyArgs>(args?: Prisma.SelectSubset<T, ReturPembelianCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ReturPembelians and returns the data saved in the database.
   * @param {ReturPembelianCreateManyAndReturnArgs} args - Arguments to create many ReturPembelians.
   * @example
   * // Create many ReturPembelians
   * const returPembelian = await prisma.returPembelian.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ReturPembelians and only return the `id`
   * const returPembelianWithIdOnly = await prisma.returPembelian.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ReturPembelianCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ReturPembelianCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReturPembelianPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ReturPembelian.
   * @param {ReturPembelianDeleteArgs} args - Arguments to delete one ReturPembelian.
   * @example
   * // Delete one ReturPembelian
   * const ReturPembelian = await prisma.returPembelian.delete({
   *   where: {
   *     // ... filter to delete one ReturPembelian
   *   }
   * })
   * 
   */
  delete<T extends ReturPembelianDeleteArgs>(args: Prisma.SelectSubset<T, ReturPembelianDeleteArgs<ExtArgs>>): Prisma.Prisma__ReturPembelianClient<runtime.Types.Result.GetResult<Prisma.$ReturPembelianPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ReturPembelian.
   * @param {ReturPembelianUpdateArgs} args - Arguments to update one ReturPembelian.
   * @example
   * // Update one ReturPembelian
   * const returPembelian = await prisma.returPembelian.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ReturPembelianUpdateArgs>(args: Prisma.SelectSubset<T, ReturPembelianUpdateArgs<ExtArgs>>): Prisma.Prisma__ReturPembelianClient<runtime.Types.Result.GetResult<Prisma.$ReturPembelianPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ReturPembelians.
   * @param {ReturPembelianDeleteManyArgs} args - Arguments to filter ReturPembelians to delete.
   * @example
   * // Delete a few ReturPembelians
   * const { count } = await prisma.returPembelian.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ReturPembelianDeleteManyArgs>(args?: Prisma.SelectSubset<T, ReturPembelianDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ReturPembelians.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReturPembelianUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ReturPembelians
   * const returPembelian = await prisma.returPembelian.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ReturPembelianUpdateManyArgs>(args: Prisma.SelectSubset<T, ReturPembelianUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ReturPembelians and returns the data updated in the database.
   * @param {ReturPembelianUpdateManyAndReturnArgs} args - Arguments to update many ReturPembelians.
   * @example
   * // Update many ReturPembelians
   * const returPembelian = await prisma.returPembelian.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ReturPembelians and only return the `id`
   * const returPembelianWithIdOnly = await prisma.returPembelian.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ReturPembelianUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ReturPembelianUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReturPembelianPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ReturPembelian.
   * @param {ReturPembelianUpsertArgs} args - Arguments to update or create a ReturPembelian.
   * @example
   * // Update or create a ReturPembelian
   * const returPembelian = await prisma.returPembelian.upsert({
   *   create: {
   *     // ... data to create a ReturPembelian
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ReturPembelian we want to update
   *   }
   * })
   */
  upsert<T extends ReturPembelianUpsertArgs>(args: Prisma.SelectSubset<T, ReturPembelianUpsertArgs<ExtArgs>>): Prisma.Prisma__ReturPembelianClient<runtime.Types.Result.GetResult<Prisma.$ReturPembelianPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ReturPembelians.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReturPembelianCountArgs} args - Arguments to filter ReturPembelians to count.
   * @example
   * // Count the number of ReturPembelians
   * const count = await prisma.returPembelian.count({
   *   where: {
   *     // ... the filter for the ReturPembelians we want to count
   *   }
   * })
  **/
  count<T extends ReturPembelianCountArgs>(
    args?: Prisma.Subset<T, ReturPembelianCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ReturPembelianCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ReturPembelian.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReturPembelianAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ReturPembelianAggregateArgs>(args: Prisma.Subset<T, ReturPembelianAggregateArgs>): Prisma.PrismaPromise<GetReturPembelianAggregateType<T>>

  /**
   * Group by ReturPembelian.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReturPembelianGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ReturPembelianGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ReturPembelianGroupByArgs['orderBy'] }
      : { orderBy?: ReturPembelianGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ReturPembelianGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetReturPembelianGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ReturPembelian model
 */
readonly fields: ReturPembelianFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ReturPembelian.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ReturPembelianClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  faktur<T extends Prisma.FakturPembelianDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FakturPembelianDefaultArgs<ExtArgs>>): Prisma.Prisma__FakturPembelianClient<runtime.Types.Result.GetResult<Prisma.$FakturPembelianPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  gudang<T extends Prisma.GudangDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GudangDefaultArgs<ExtArgs>>): Prisma.Prisma__GudangClient<runtime.Types.Result.GetResult<Prisma.$GudangPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  jurnal<T extends Prisma.ReturPembelian$jurnalArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ReturPembelian$jurnalArgs<ExtArgs>>): Prisma.Prisma__JurnalClient<runtime.Types.Result.GetResult<Prisma.$JurnalPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  baris<T extends Prisma.ReturPembelian$barisArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ReturPembelian$barisArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BarisReturPembelianPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ReturPembelian model
 */
export interface ReturPembelianFieldRefs {
  readonly id: Prisma.FieldRef<"ReturPembelian", 'String'>
  readonly nomor: Prisma.FieldRef<"ReturPembelian", 'String'>
  readonly tanggal: Prisma.FieldRef<"ReturPembelian", 'DateTime'>
  readonly fakturId: Prisma.FieldRef<"ReturPembelian", 'String'>
  readonly gudangId: Prisma.FieldRef<"ReturPembelian", 'String'>
  readonly alasan: Prisma.FieldRef<"ReturPembelian", 'String'>
  readonly total: Prisma.FieldRef<"ReturPembelian", 'Decimal'>
  readonly dpp: Prisma.FieldRef<"ReturPembelian", 'Decimal'>
  readonly ppn: Prisma.FieldRef<"ReturPembelian", 'Decimal'>
  readonly jurnalId: Prisma.FieldRef<"ReturPembelian", 'String'>
}
    

// Custom InputTypes
/**
 * ReturPembelian findUnique
 */
export type ReturPembelianFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReturPembelian
   */
  select?: Prisma.ReturPembelianSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReturPembelian
   */
  omit?: Prisma.ReturPembelianOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReturPembelianInclude<ExtArgs> | null
  /**
   * Filter, which ReturPembelian to fetch.
   */
  where: Prisma.ReturPembelianWhereUniqueInput
}

/**
 * ReturPembelian findUniqueOrThrow
 */
export type ReturPembelianFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReturPembelian
   */
  select?: Prisma.ReturPembelianSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReturPembelian
   */
  omit?: Prisma.ReturPembelianOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReturPembelianInclude<ExtArgs> | null
  /**
   * Filter, which ReturPembelian to fetch.
   */
  where: Prisma.ReturPembelianWhereUniqueInput
}

/**
 * ReturPembelian findFirst
 */
export type ReturPembelianFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReturPembelian
   */
  select?: Prisma.ReturPembelianSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReturPembelian
   */
  omit?: Prisma.ReturPembelianOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReturPembelianInclude<ExtArgs> | null
  /**
   * Filter, which ReturPembelian to fetch.
   */
  where?: Prisma.ReturPembelianWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReturPembelians to fetch.
   */
  orderBy?: Prisma.ReturPembelianOrderByWithRelationInput | Prisma.ReturPembelianOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ReturPembelians.
   */
  cursor?: Prisma.ReturPembelianWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReturPembelians from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReturPembelians.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ReturPembelians.
   */
  distinct?: Prisma.ReturPembelianScalarFieldEnum | Prisma.ReturPembelianScalarFieldEnum[]
}

/**
 * ReturPembelian findFirstOrThrow
 */
export type ReturPembelianFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReturPembelian
   */
  select?: Prisma.ReturPembelianSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReturPembelian
   */
  omit?: Prisma.ReturPembelianOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReturPembelianInclude<ExtArgs> | null
  /**
   * Filter, which ReturPembelian to fetch.
   */
  where?: Prisma.ReturPembelianWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReturPembelians to fetch.
   */
  orderBy?: Prisma.ReturPembelianOrderByWithRelationInput | Prisma.ReturPembelianOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ReturPembelians.
   */
  cursor?: Prisma.ReturPembelianWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReturPembelians from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReturPembelians.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ReturPembelians.
   */
  distinct?: Prisma.ReturPembelianScalarFieldEnum | Prisma.ReturPembelianScalarFieldEnum[]
}

/**
 * ReturPembelian findMany
 */
export type ReturPembelianFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReturPembelian
   */
  select?: Prisma.ReturPembelianSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReturPembelian
   */
  omit?: Prisma.ReturPembelianOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReturPembelianInclude<ExtArgs> | null
  /**
   * Filter, which ReturPembelians to fetch.
   */
  where?: Prisma.ReturPembelianWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReturPembelians to fetch.
   */
  orderBy?: Prisma.ReturPembelianOrderByWithRelationInput | Prisma.ReturPembelianOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ReturPembelians.
   */
  cursor?: Prisma.ReturPembelianWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReturPembelians from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReturPembelians.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ReturPembelians.
   */
  distinct?: Prisma.ReturPembelianScalarFieldEnum | Prisma.ReturPembelianScalarFieldEnum[]
}

/**
 * ReturPembelian create
 */
export type ReturPembelianCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReturPembelian
   */
  select?: Prisma.ReturPembelianSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReturPembelian
   */
  omit?: Prisma.ReturPembelianOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReturPembelianInclude<ExtArgs> | null
  /**
   * The data needed to create a ReturPembelian.
   */
  data: Prisma.XOR<Prisma.ReturPembelianCreateInput, Prisma.ReturPembelianUncheckedCreateInput>
}

/**
 * ReturPembelian createMany
 */
export type ReturPembelianCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ReturPembelians.
   */
  data: Prisma.ReturPembelianCreateManyInput | Prisma.ReturPembelianCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ReturPembelian createManyAndReturn
 */
export type ReturPembelianCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReturPembelian
   */
  select?: Prisma.ReturPembelianSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ReturPembelian
   */
  omit?: Prisma.ReturPembelianOmit<ExtArgs> | null
  /**
   * The data used to create many ReturPembelians.
   */
  data: Prisma.ReturPembelianCreateManyInput | Prisma.ReturPembelianCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReturPembelianIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ReturPembelian update
 */
export type ReturPembelianUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReturPembelian
   */
  select?: Prisma.ReturPembelianSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReturPembelian
   */
  omit?: Prisma.ReturPembelianOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReturPembelianInclude<ExtArgs> | null
  /**
   * The data needed to update a ReturPembelian.
   */
  data: Prisma.XOR<Prisma.ReturPembelianUpdateInput, Prisma.ReturPembelianUncheckedUpdateInput>
  /**
   * Choose, which ReturPembelian to update.
   */
  where: Prisma.ReturPembelianWhereUniqueInput
}

/**
 * ReturPembelian updateMany
 */
export type ReturPembelianUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ReturPembelians.
   */
  data: Prisma.XOR<Prisma.ReturPembelianUpdateManyMutationInput, Prisma.ReturPembelianUncheckedUpdateManyInput>
  /**
   * Filter which ReturPembelians to update
   */
  where?: Prisma.ReturPembelianWhereInput
  /**
   * Limit how many ReturPembelians to update.
   */
  limit?: number
}

/**
 * ReturPembelian updateManyAndReturn
 */
export type ReturPembelianUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReturPembelian
   */
  select?: Prisma.ReturPembelianSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ReturPembelian
   */
  omit?: Prisma.ReturPembelianOmit<ExtArgs> | null
  /**
   * The data used to update ReturPembelians.
   */
  data: Prisma.XOR<Prisma.ReturPembelianUpdateManyMutationInput, Prisma.ReturPembelianUncheckedUpdateManyInput>
  /**
   * Filter which ReturPembelians to update
   */
  where?: Prisma.ReturPembelianWhereInput
  /**
   * Limit how many ReturPembelians to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReturPembelianIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ReturPembelian upsert
 */
export type ReturPembelianUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReturPembelian
   */
  select?: Prisma.ReturPembelianSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReturPembelian
   */
  omit?: Prisma.ReturPembelianOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReturPembelianInclude<ExtArgs> | null
  /**
   * The filter to search for the ReturPembelian to update in case it exists.
   */
  where: Prisma.ReturPembelianWhereUniqueInput
  /**
   * In case the ReturPembelian found by the `where` argument doesn't exist, create a new ReturPembelian with this data.
   */
  create: Prisma.XOR<Prisma.ReturPembelianCreateInput, Prisma.ReturPembelianUncheckedCreateInput>
  /**
   * In case the ReturPembelian was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ReturPembelianUpdateInput, Prisma.ReturPembelianUncheckedUpdateInput>
}

/**
 * ReturPembelian delete
 */
export type ReturPembelianDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReturPembelian
   */
  select?: Prisma.ReturPembelianSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReturPembelian
   */
  omit?: Prisma.ReturPembelianOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReturPembelianInclude<ExtArgs> | null
  /**
   * Filter which ReturPembelian to delete.
   */
  where: Prisma.ReturPembelianWhereUniqueInput
}

/**
 * ReturPembelian deleteMany
 */
export type ReturPembelianDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ReturPembelians to delete
   */
  where?: Prisma.ReturPembelianWhereInput
  /**
   * Limit how many ReturPembelians to delete.
   */
  limit?: number
}

/**
 * ReturPembelian.jurnal
 */
export type ReturPembelian$jurnalArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Jurnal
   */
  select?: Prisma.JurnalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Jurnal
   */
  omit?: Prisma.JurnalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JurnalInclude<ExtArgs> | null
  where?: Prisma.JurnalWhereInput
}

/**
 * ReturPembelian.baris
 */
export type ReturPembelian$barisArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarisReturPembelian
   */
  select?: Prisma.BarisReturPembelianSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BarisReturPembelian
   */
  omit?: Prisma.BarisReturPembelianOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BarisReturPembelianInclude<ExtArgs> | null
  where?: Prisma.BarisReturPembelianWhereInput
  orderBy?: Prisma.BarisReturPembelianOrderByWithRelationInput | Prisma.BarisReturPembelianOrderByWithRelationInput[]
  cursor?: Prisma.BarisReturPembelianWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BarisReturPembelianScalarFieldEnum | Prisma.BarisReturPembelianScalarFieldEnum[]
}

/**
 * ReturPembelian without action
 */
export type ReturPembelianDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReturPembelian
   */
  select?: Prisma.ReturPembelianSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReturPembelian
   */
  omit?: Prisma.ReturPembelianOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReturPembelianInclude<ExtArgs> | null
}
